// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: application_metadata_message.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationMetadataMessage_Type int32

const (
	ApplicationMetadataMessage_UNKNOWN                                         ApplicationMetadataMessage_Type = 0
	ApplicationMetadataMessage_CHAT_MESSAGE                                    ApplicationMetadataMessage_Type = 1
	ApplicationMetadataMessage_CONTACT_UPDATE                                  ApplicationMetadataMessage_Type = 2
	ApplicationMetadataMessage_MEMBERSHIP_UPDATE_MESSAGE                       ApplicationMetadataMessage_Type = 3
	ApplicationMetadataMessage_SYNC_PAIR_INSTALLATION                          ApplicationMetadataMessage_Type = 4
	ApplicationMetadataMessage_SYNC_INSTALLATION_CONTACT_V2                    ApplicationMetadataMessage_Type = 12
	ApplicationMetadataMessage_SYNC_INSTALLATION_ACCOUNT                       ApplicationMetadataMessage_Type = 13
	ApplicationMetadataMessage_CONTACT_CODE_ADVERTISEMENT                      ApplicationMetadataMessage_Type = 15
	ApplicationMetadataMessage_PUSH_NOTIFICATION_REGISTRATION                  ApplicationMetadataMessage_Type = 16
	ApplicationMetadataMessage_PUSH_NOTIFICATION_REGISTRATION_RESPONSE         ApplicationMetadataMessage_Type = 17
	ApplicationMetadataMessage_PUSH_NOTIFICATION_QUERY                         ApplicationMetadataMessage_Type = 18
	ApplicationMetadataMessage_PUSH_NOTIFICATION_QUERY_RESPONSE                ApplicationMetadataMessage_Type = 19
	ApplicationMetadataMessage_PUSH_NOTIFICATION_REQUEST                       ApplicationMetadataMessage_Type = 20
	ApplicationMetadataMessage_PUSH_NOTIFICATION_RESPONSE                      ApplicationMetadataMessage_Type = 21
	ApplicationMetadataMessage_EMOJI_REACTION                                  ApplicationMetadataMessage_Type = 22
	ApplicationMetadataMessage_GROUP_CHAT_INVITATION                           ApplicationMetadataMessage_Type = 23
	ApplicationMetadataMessage_CHAT_IDENTITY                                   ApplicationMetadataMessage_Type = 24
	ApplicationMetadataMessage_COMMUNITY_DESCRIPTION                           ApplicationMetadataMessage_Type = 25
	ApplicationMetadataMessage_COMMUNITY_REQUEST_TO_JOIN                       ApplicationMetadataMessage_Type = 27
	ApplicationMetadataMessage_PIN_MESSAGE                                     ApplicationMetadataMessage_Type = 28
	ApplicationMetadataMessage_EDIT_MESSAGE                                    ApplicationMetadataMessage_Type = 29
	ApplicationMetadataMessage_STATUS_UPDATE                                   ApplicationMetadataMessage_Type = 30
	ApplicationMetadataMessage_DELETE_MESSAGE                                  ApplicationMetadataMessage_Type = 31
	ApplicationMetadataMessage_SYNC_INSTALLATION_COMMUNITY                     ApplicationMetadataMessage_Type = 32
	ApplicationMetadataMessage_ANONYMOUS_METRIC_BATCH                          ApplicationMetadataMessage_Type = 33
	ApplicationMetadataMessage_SYNC_CHAT_REMOVED                               ApplicationMetadataMessage_Type = 34
	ApplicationMetadataMessage_SYNC_CHAT_MESSAGES_READ                         ApplicationMetadataMessage_Type = 35
	ApplicationMetadataMessage_SYNC_ACTIVITY_CENTER_READ                       ApplicationMetadataMessage_Type = 37
	ApplicationMetadataMessage_SYNC_ACTIVITY_CENTER_ACCEPTED                   ApplicationMetadataMessage_Type = 38
	ApplicationMetadataMessage_SYNC_ACTIVITY_CENTER_DISMISSED                  ApplicationMetadataMessage_Type = 39
	ApplicationMetadataMessage_SYNC_BOOKMARK                                   ApplicationMetadataMessage_Type = 40
	ApplicationMetadataMessage_SYNC_CLEAR_HISTORY                              ApplicationMetadataMessage_Type = 41
	ApplicationMetadataMessage_SYNC_SETTING                                    ApplicationMetadataMessage_Type = 42
	ApplicationMetadataMessage_COMMUNITY_MESSAGE_ARCHIVE_LINK                  ApplicationMetadataMessage_Type = 43
	ApplicationMetadataMessage_SYNC_PROFILE_PICTURES                           ApplicationMetadataMessage_Type = 44
	ApplicationMetadataMessage_SYNC_ACCOUNT                                    ApplicationMetadataMessage_Type = 45
	ApplicationMetadataMessage_ACCEPT_CONTACT_REQUEST                          ApplicationMetadataMessage_Type = 46
	ApplicationMetadataMessage_RETRACT_CONTACT_REQUEST                         ApplicationMetadataMessage_Type = 47
	ApplicationMetadataMessage_COMMUNITY_REQUEST_TO_JOIN_RESPONSE              ApplicationMetadataMessage_Type = 48
	ApplicationMetadataMessage_SYNC_COMMUNITY_SETTINGS                         ApplicationMetadataMessage_Type = 49
	ApplicationMetadataMessage_REQUEST_CONTACT_VERIFICATION                    ApplicationMetadataMessage_Type = 50
	ApplicationMetadataMessage_ACCEPT_CONTACT_VERIFICATION                     ApplicationMetadataMessage_Type = 51
	ApplicationMetadataMessage_DECLINE_CONTACT_VERIFICATION                    ApplicationMetadataMessage_Type = 52
	ApplicationMetadataMessage_SYNC_TRUSTED_USER                               ApplicationMetadataMessage_Type = 53
	ApplicationMetadataMessage_SYNC_VERIFICATION_REQUEST                       ApplicationMetadataMessage_Type = 54
	ApplicationMetadataMessage_SYNC_CONTACT_REQUEST_DECISION                   ApplicationMetadataMessage_Type = 56
	ApplicationMetadataMessage_COMMUNITY_REQUEST_TO_LEAVE                      ApplicationMetadataMessage_Type = 57
	ApplicationMetadataMessage_SYNC_DELETE_FOR_ME_MESSAGE                      ApplicationMetadataMessage_Type = 58
	ApplicationMetadataMessage_SYNC_SAVED_ADDRESS                              ApplicationMetadataMessage_Type = 59
	ApplicationMetadataMessage_COMMUNITY_CANCEL_REQUEST_TO_JOIN                ApplicationMetadataMessage_Type = 60
	ApplicationMetadataMessage_CANCEL_CONTACT_VERIFICATION                     ApplicationMetadataMessage_Type = 61
	ApplicationMetadataMessage_SYNC_KEYPAIR                                    ApplicationMetadataMessage_Type = 62
	ApplicationMetadataMessage_SYNC_ENS_USERNAME_DETAIL                        ApplicationMetadataMessage_Type = 64
	ApplicationMetadataMessage_COMMUNITY_EVENTS_MESSAGE                        ApplicationMetadataMessage_Type = 67
	ApplicationMetadataMessage_COMMUNITY_EDIT_SHARED_ADDRESSES                 ApplicationMetadataMessage_Type = 68
	ApplicationMetadataMessage_SYNC_ACCOUNT_CUSTOMIZATION_COLOR                ApplicationMetadataMessage_Type = 69
	ApplicationMetadataMessage_SYNC_ACCOUNTS_POSITIONS                         ApplicationMetadataMessage_Type = 70
	ApplicationMetadataMessage_COMMUNITY_PRIVILEGED_USER_SYNC_MESSAGE          ApplicationMetadataMessage_Type = 72
	ApplicationMetadataMessage_SYNC_CHAT                                       ApplicationMetadataMessage_Type = 74
	ApplicationMetadataMessage_SYNC_ACTIVITY_CENTER_DELETED                    ApplicationMetadataMessage_Type = 75
	ApplicationMetadataMessage_SYNC_ACTIVITY_CENTER_UNREAD                     ApplicationMetadataMessage_Type = 76
	ApplicationMetadataMessage_SYNC_ACTIVITY_CENTER_COMMUNITY_REQUEST_DECISION ApplicationMetadataMessage_Type = 77
	ApplicationMetadataMessage_SYNC_TOKEN_PREFERENCES                          ApplicationMetadataMessage_Type = 78
	ApplicationMetadataMessage_SYNC_COLLECTIBLE_PREFERENCES                    ApplicationMetadataMessage_Type = 80
	ApplicationMetadataMessage_COMMUNITY_USER_KICKED                           ApplicationMetadataMessage_Type = 81
	ApplicationMetadataMessage_SYNC_PROFILE_SHOWCASE_PREFERENCES               ApplicationMetadataMessage_Type = 82
	ApplicationMetadataMessage_COMMUNITY_REEVALUATE_PERMISSIONS_REQUEST        ApplicationMetadataMessage_Type = 84
	ApplicationMetadataMessage_DELETE_COMMUNITY_MEMBER_MESSAGES                ApplicationMetadataMessage_Type = 85
	ApplicationMetadataMessage_COMMUNITY_UPDATE_GRANT                          ApplicationMetadataMessage_Type = 86
	ApplicationMetadataMessage_COMMUNITY_ENCRYPTION_KEYS_REQUEST               ApplicationMetadataMessage_Type = 87
	ApplicationMetadataMessage_COMMUNITY_TOKEN_ACTION                          ApplicationMetadataMessage_Type = 88
	ApplicationMetadataMessage_COMMUNITY_SHARED_ADDRESSES_REQUEST              ApplicationMetadataMessage_Type = 89
	ApplicationMetadataMessage_COMMUNITY_SHARED_ADDRESSES_RESPONSE             ApplicationMetadataMessage_Type = 90
	ApplicationMetadataMessage_BACKED_UP_MESSAGE_BATCH                         ApplicationMetadataMessage_Type = 91
)

// Enum value maps for ApplicationMetadataMessage_Type.
var (
	ApplicationMetadataMessage_Type_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "CHAT_MESSAGE",
		2:  "CONTACT_UPDATE",
		3:  "MEMBERSHIP_UPDATE_MESSAGE",
		4:  "SYNC_PAIR_INSTALLATION",
		12: "SYNC_INSTALLATION_CONTACT_V2",
		13: "SYNC_INSTALLATION_ACCOUNT",
		15: "CONTACT_CODE_ADVERTISEMENT",
		16: "PUSH_NOTIFICATION_REGISTRATION",
		17: "PUSH_NOTIFICATION_REGISTRATION_RESPONSE",
		18: "PUSH_NOTIFICATION_QUERY",
		19: "PUSH_NOTIFICATION_QUERY_RESPONSE",
		20: "PUSH_NOTIFICATION_REQUEST",
		21: "PUSH_NOTIFICATION_RESPONSE",
		22: "EMOJI_REACTION",
		23: "GROUP_CHAT_INVITATION",
		24: "CHAT_IDENTITY",
		25: "COMMUNITY_DESCRIPTION",
		27: "COMMUNITY_REQUEST_TO_JOIN",
		28: "PIN_MESSAGE",
		29: "EDIT_MESSAGE",
		30: "STATUS_UPDATE",
		31: "DELETE_MESSAGE",
		32: "SYNC_INSTALLATION_COMMUNITY",
		33: "ANONYMOUS_METRIC_BATCH",
		34: "SYNC_CHAT_REMOVED",
		35: "SYNC_CHAT_MESSAGES_READ",
		37: "SYNC_ACTIVITY_CENTER_READ",
		38: "SYNC_ACTIVITY_CENTER_ACCEPTED",
		39: "SYNC_ACTIVITY_CENTER_DISMISSED",
		40: "SYNC_BOOKMARK",
		41: "SYNC_CLEAR_HISTORY",
		42: "SYNC_SETTING",
		43: "COMMUNITY_MESSAGE_ARCHIVE_LINK",
		44: "SYNC_PROFILE_PICTURES",
		45: "SYNC_ACCOUNT",
		46: "ACCEPT_CONTACT_REQUEST",
		47: "RETRACT_CONTACT_REQUEST",
		48: "COMMUNITY_REQUEST_TO_JOIN_RESPONSE",
		49: "SYNC_COMMUNITY_SETTINGS",
		50: "REQUEST_CONTACT_VERIFICATION",
		51: "ACCEPT_CONTACT_VERIFICATION",
		52: "DECLINE_CONTACT_VERIFICATION",
		53: "SYNC_TRUSTED_USER",
		54: "SYNC_VERIFICATION_REQUEST",
		56: "SYNC_CONTACT_REQUEST_DECISION",
		57: "COMMUNITY_REQUEST_TO_LEAVE",
		58: "SYNC_DELETE_FOR_ME_MESSAGE",
		59: "SYNC_SAVED_ADDRESS",
		60: "COMMUNITY_CANCEL_REQUEST_TO_JOIN",
		61: "CANCEL_CONTACT_VERIFICATION",
		62: "SYNC_KEYPAIR",
		64: "SYNC_ENS_USERNAME_DETAIL",
		67: "COMMUNITY_EVENTS_MESSAGE",
		68: "COMMUNITY_EDIT_SHARED_ADDRESSES",
		69: "SYNC_ACCOUNT_CUSTOMIZATION_COLOR",
		70: "SYNC_ACCOUNTS_POSITIONS",
		72: "COMMUNITY_PRIVILEGED_USER_SYNC_MESSAGE",
		74: "SYNC_CHAT",
		75: "SYNC_ACTIVITY_CENTER_DELETED",
		76: "SYNC_ACTIVITY_CENTER_UNREAD",
		77: "SYNC_ACTIVITY_CENTER_COMMUNITY_REQUEST_DECISION",
		78: "SYNC_TOKEN_PREFERENCES",
		80: "SYNC_COLLECTIBLE_PREFERENCES",
		81: "COMMUNITY_USER_KICKED",
		82: "SYNC_PROFILE_SHOWCASE_PREFERENCES",
		84: "COMMUNITY_REEVALUATE_PERMISSIONS_REQUEST",
		85: "DELETE_COMMUNITY_MEMBER_MESSAGES",
		86: "COMMUNITY_UPDATE_GRANT",
		87: "COMMUNITY_ENCRYPTION_KEYS_REQUEST",
		88: "COMMUNITY_TOKEN_ACTION",
		89: "COMMUNITY_SHARED_ADDRESSES_REQUEST",
		90: "COMMUNITY_SHARED_ADDRESSES_RESPONSE",
		91: "BACKED_UP_MESSAGE_BATCH",
	}
	ApplicationMetadataMessage_Type_value = map[string]int32{
		"UNKNOWN":                                         0,
		"CHAT_MESSAGE":                                    1,
		"CONTACT_UPDATE":                                  2,
		"MEMBERSHIP_UPDATE_MESSAGE":                       3,
		"SYNC_PAIR_INSTALLATION":                          4,
		"SYNC_INSTALLATION_CONTACT_V2":                    12,
		"SYNC_INSTALLATION_ACCOUNT":                       13,
		"CONTACT_CODE_ADVERTISEMENT":                      15,
		"PUSH_NOTIFICATION_REGISTRATION":                  16,
		"PUSH_NOTIFICATION_REGISTRATION_RESPONSE":         17,
		"PUSH_NOTIFICATION_QUERY":                         18,
		"PUSH_NOTIFICATION_QUERY_RESPONSE":                19,
		"PUSH_NOTIFICATION_REQUEST":                       20,
		"PUSH_NOTIFICATION_RESPONSE":                      21,
		"EMOJI_REACTION":                                  22,
		"GROUP_CHAT_INVITATION":                           23,
		"CHAT_IDENTITY":                                   24,
		"COMMUNITY_DESCRIPTION":                           25,
		"COMMUNITY_REQUEST_TO_JOIN":                       27,
		"PIN_MESSAGE":                                     28,
		"EDIT_MESSAGE":                                    29,
		"STATUS_UPDATE":                                   30,
		"DELETE_MESSAGE":                                  31,
		"SYNC_INSTALLATION_COMMUNITY":                     32,
		"ANONYMOUS_METRIC_BATCH":                          33,
		"SYNC_CHAT_REMOVED":                               34,
		"SYNC_CHAT_MESSAGES_READ":                         35,
		"SYNC_ACTIVITY_CENTER_READ":                       37,
		"SYNC_ACTIVITY_CENTER_ACCEPTED":                   38,
		"SYNC_ACTIVITY_CENTER_DISMISSED":                  39,
		"SYNC_BOOKMARK":                                   40,
		"SYNC_CLEAR_HISTORY":                              41,
		"SYNC_SETTING":                                    42,
		"COMMUNITY_MESSAGE_ARCHIVE_LINK":                  43,
		"SYNC_PROFILE_PICTURES":                           44,
		"SYNC_ACCOUNT":                                    45,
		"ACCEPT_CONTACT_REQUEST":                          46,
		"RETRACT_CONTACT_REQUEST":                         47,
		"COMMUNITY_REQUEST_TO_JOIN_RESPONSE":              48,
		"SYNC_COMMUNITY_SETTINGS":                         49,
		"REQUEST_CONTACT_VERIFICATION":                    50,
		"ACCEPT_CONTACT_VERIFICATION":                     51,
		"DECLINE_CONTACT_VERIFICATION":                    52,
		"SYNC_TRUSTED_USER":                               53,
		"SYNC_VERIFICATION_REQUEST":                       54,
		"SYNC_CONTACT_REQUEST_DECISION":                   56,
		"COMMUNITY_REQUEST_TO_LEAVE":                      57,
		"SYNC_DELETE_FOR_ME_MESSAGE":                      58,
		"SYNC_SAVED_ADDRESS":                              59,
		"COMMUNITY_CANCEL_REQUEST_TO_JOIN":                60,
		"CANCEL_CONTACT_VERIFICATION":                     61,
		"SYNC_KEYPAIR":                                    62,
		"SYNC_ENS_USERNAME_DETAIL":                        64,
		"COMMUNITY_EVENTS_MESSAGE":                        67,
		"COMMUNITY_EDIT_SHARED_ADDRESSES":                 68,
		"SYNC_ACCOUNT_CUSTOMIZATION_COLOR":                69,
		"SYNC_ACCOUNTS_POSITIONS":                         70,
		"COMMUNITY_PRIVILEGED_USER_SYNC_MESSAGE":          72,
		"SYNC_CHAT":                                       74,
		"SYNC_ACTIVITY_CENTER_DELETED":                    75,
		"SYNC_ACTIVITY_CENTER_UNREAD":                     76,
		"SYNC_ACTIVITY_CENTER_COMMUNITY_REQUEST_DECISION": 77,
		"SYNC_TOKEN_PREFERENCES":                          78,
		"SYNC_COLLECTIBLE_PREFERENCES":                    80,
		"COMMUNITY_USER_KICKED":                           81,
		"SYNC_PROFILE_SHOWCASE_PREFERENCES":               82,
		"COMMUNITY_REEVALUATE_PERMISSIONS_REQUEST":        84,
		"DELETE_COMMUNITY_MEMBER_MESSAGES":                85,
		"COMMUNITY_UPDATE_GRANT":                          86,
		"COMMUNITY_ENCRYPTION_KEYS_REQUEST":               87,
		"COMMUNITY_TOKEN_ACTION":                          88,
		"COMMUNITY_SHARED_ADDRESSES_REQUEST":              89,
		"COMMUNITY_SHARED_ADDRESSES_RESPONSE":             90,
		"BACKED_UP_MESSAGE_BATCH":                         91,
	}
)

func (x ApplicationMetadataMessage_Type) Enum() *ApplicationMetadataMessage_Type {
	p := new(ApplicationMetadataMessage_Type)
	*p = x
	return p
}

func (x ApplicationMetadataMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicationMetadataMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_application_metadata_message_proto_enumTypes[0].Descriptor()
}

func (ApplicationMetadataMessage_Type) Type() protoreflect.EnumType {
	return &file_application_metadata_message_proto_enumTypes[0]
}

func (x ApplicationMetadataMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicationMetadataMessage_Type.Descriptor instead.
func (ApplicationMetadataMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_application_metadata_message_proto_rawDescGZIP(), []int{0, 0}
}

type ApplicationMetadataMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signature of the payload field
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// This is the encoded protobuf of the application level message, i.e ChatMessage
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// The type of protobuf message sent
	Type          ApplicationMetadataMessage_Type `protobuf:"varint,3,opt,name=type,proto3,enum=protobuf.ApplicationMetadataMessage_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationMetadataMessage) Reset() {
	*x = ApplicationMetadataMessage{}
	mi := &file_application_metadata_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationMetadataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationMetadataMessage) ProtoMessage() {}

func (x *ApplicationMetadataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_application_metadata_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationMetadataMessage.ProtoReflect.Descriptor instead.
func (*ApplicationMetadataMessage) Descriptor() ([]byte, []int) {
	return file_application_metadata_message_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationMetadataMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ApplicationMetadataMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ApplicationMetadataMessage) GetType() ApplicationMetadataMessage_Type {
	if x != nil {
		return x.Type
	}
	return ApplicationMetadataMessage_UNKNOWN
}

var File_application_metadata_message_proto protoreflect.FileDescriptor

const file_application_metadata_message_proto_rawDesc = "" +
	"\n" +
	"\"application_metadata_message.proto\x12\bprotobuf\"\xb4\x13\n" +
	"\x1aApplicationMetadataMessage\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12=\n" +
	"\x04type\x18\x03 \x01(\x0e2).protobuf.ApplicationMetadataMessage.TypeR\x04type\"\x9e\x12\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x10\n" +
	"\fCHAT_MESSAGE\x10\x01\x12\x12\n" +
	"\x0eCONTACT_UPDATE\x10\x02\x12\x1d\n" +
	"\x19MEMBERSHIP_UPDATE_MESSAGE\x10\x03\x12\x1a\n" +
	"\x16SYNC_PAIR_INSTALLATION\x10\x04\x12 \n" +
	"\x1cSYNC_INSTALLATION_CONTACT_V2\x10\f\x12\x1d\n" +
	"\x19SYNC_INSTALLATION_ACCOUNT\x10\r\x12\x1e\n" +
	"\x1aCONTACT_CODE_ADVERTISEMENT\x10\x0f\x12\"\n" +
	"\x1ePUSH_NOTIFICATION_REGISTRATION\x10\x10\x12+\n" +
	"'PUSH_NOTIFICATION_REGISTRATION_RESPONSE\x10\x11\x12\x1b\n" +
	"\x17PUSH_NOTIFICATION_QUERY\x10\x12\x12$\n" +
	" PUSH_NOTIFICATION_QUERY_RESPONSE\x10\x13\x12\x1d\n" +
	"\x19PUSH_NOTIFICATION_REQUEST\x10\x14\x12\x1e\n" +
	"\x1aPUSH_NOTIFICATION_RESPONSE\x10\x15\x12\x12\n" +
	"\x0eEMOJI_REACTION\x10\x16\x12\x19\n" +
	"\x15GROUP_CHAT_INVITATION\x10\x17\x12\x11\n" +
	"\rCHAT_IDENTITY\x10\x18\x12\x19\n" +
	"\x15COMMUNITY_DESCRIPTION\x10\x19\x12\x1d\n" +
	"\x19COMMUNITY_REQUEST_TO_JOIN\x10\x1b\x12\x0f\n" +
	"\vPIN_MESSAGE\x10\x1c\x12\x10\n" +
	"\fEDIT_MESSAGE\x10\x1d\x12\x11\n" +
	"\rSTATUS_UPDATE\x10\x1e\x12\x12\n" +
	"\x0eDELETE_MESSAGE\x10\x1f\x12\x1f\n" +
	"\x1bSYNC_INSTALLATION_COMMUNITY\x10 \x12\x1a\n" +
	"\x16ANONYMOUS_METRIC_BATCH\x10!\x12\x15\n" +
	"\x11SYNC_CHAT_REMOVED\x10\"\x12\x1b\n" +
	"\x17SYNC_CHAT_MESSAGES_READ\x10#\x12\x1d\n" +
	"\x19SYNC_ACTIVITY_CENTER_READ\x10%\x12!\n" +
	"\x1dSYNC_ACTIVITY_CENTER_ACCEPTED\x10&\x12\"\n" +
	"\x1eSYNC_ACTIVITY_CENTER_DISMISSED\x10'\x12\x11\n" +
	"\rSYNC_BOOKMARK\x10(\x12\x16\n" +
	"\x12SYNC_CLEAR_HISTORY\x10)\x12\x10\n" +
	"\fSYNC_SETTING\x10*\x12\"\n" +
	"\x1eCOMMUNITY_MESSAGE_ARCHIVE_LINK\x10+\x12\x19\n" +
	"\x15SYNC_PROFILE_PICTURES\x10,\x12\x10\n" +
	"\fSYNC_ACCOUNT\x10-\x12\x1a\n" +
	"\x16ACCEPT_CONTACT_REQUEST\x10.\x12\x1b\n" +
	"\x17RETRACT_CONTACT_REQUEST\x10/\x12&\n" +
	"\"COMMUNITY_REQUEST_TO_JOIN_RESPONSE\x100\x12\x1b\n" +
	"\x17SYNC_COMMUNITY_SETTINGS\x101\x12 \n" +
	"\x1cREQUEST_CONTACT_VERIFICATION\x102\x12\x1f\n" +
	"\x1bACCEPT_CONTACT_VERIFICATION\x103\x12 \n" +
	"\x1cDECLINE_CONTACT_VERIFICATION\x104\x12\x15\n" +
	"\x11SYNC_TRUSTED_USER\x105\x12\x1d\n" +
	"\x19SYNC_VERIFICATION_REQUEST\x106\x12!\n" +
	"\x1dSYNC_CONTACT_REQUEST_DECISION\x108\x12\x1e\n" +
	"\x1aCOMMUNITY_REQUEST_TO_LEAVE\x109\x12\x1e\n" +
	"\x1aSYNC_DELETE_FOR_ME_MESSAGE\x10:\x12\x16\n" +
	"\x12SYNC_SAVED_ADDRESS\x10;\x12$\n" +
	" COMMUNITY_CANCEL_REQUEST_TO_JOIN\x10<\x12\x1f\n" +
	"\x1bCANCEL_CONTACT_VERIFICATION\x10=\x12\x10\n" +
	"\fSYNC_KEYPAIR\x10>\x12\x1c\n" +
	"\x18SYNC_ENS_USERNAME_DETAIL\x10@\x12\x1c\n" +
	"\x18COMMUNITY_EVENTS_MESSAGE\x10C\x12#\n" +
	"\x1fCOMMUNITY_EDIT_SHARED_ADDRESSES\x10D\x12$\n" +
	" SYNC_ACCOUNT_CUSTOMIZATION_COLOR\x10E\x12\x1b\n" +
	"\x17SYNC_ACCOUNTS_POSITIONS\x10F\x12*\n" +
	"&COMMUNITY_PRIVILEGED_USER_SYNC_MESSAGE\x10H\x12\r\n" +
	"\tSYNC_CHAT\x10J\x12 \n" +
	"\x1cSYNC_ACTIVITY_CENTER_DELETED\x10K\x12\x1f\n" +
	"\x1bSYNC_ACTIVITY_CENTER_UNREAD\x10L\x123\n" +
	"/SYNC_ACTIVITY_CENTER_COMMUNITY_REQUEST_DECISION\x10M\x12\x1a\n" +
	"\x16SYNC_TOKEN_PREFERENCES\x10N\x12 \n" +
	"\x1cSYNC_COLLECTIBLE_PREFERENCES\x10P\x12\x19\n" +
	"\x15COMMUNITY_USER_KICKED\x10Q\x12%\n" +
	"!SYNC_PROFILE_SHOWCASE_PREFERENCES\x10R\x12,\n" +
	"(COMMUNITY_REEVALUATE_PERMISSIONS_REQUEST\x10T\x12$\n" +
	" DELETE_COMMUNITY_MEMBER_MESSAGES\x10U\x12\x1a\n" +
	"\x16COMMUNITY_UPDATE_GRANT\x10V\x12%\n" +
	"!COMMUNITY_ENCRYPTION_KEYS_REQUEST\x10W\x12\x1a\n" +
	"\x16COMMUNITY_TOKEN_ACTION\x10X\x12&\n" +
	"\"COMMUNITY_SHARED_ADDRESSES_REQUEST\x10Y\x12'\n" +
	"#COMMUNITY_SHARED_ADDRESSES_RESPONSE\x10Z\x12\x1b\n" +
	"\x17BACKED_UP_MESSAGE_BATCH\x10[\"\x04\b\x05\x10\x05\"\x04\b\x06\x10\x06\"\x04\b\a\x10\a\"\x04\b\b\x10\b\"\x04\b\t\x10\t\"\x04\b\n" +
	"\x10\n" +
	"\"\x04\b\v\x10\v\"\x04\b\x0e\x10\x0e\"\x04\b\x1a\x10\x1a\"\x04\b$\x10$\"\x04\b?\x10?\"\x04\bA\x10A\"\x04\bB\x10B\"\x04\bG\x10G\"\x04\bI\x10I\"\x04\bO\x10O\"\x04\bS\x10SB\rZ\v./;protobufb\x06proto3"

var (
	file_application_metadata_message_proto_rawDescOnce sync.Once
	file_application_metadata_message_proto_rawDescData []byte
)

func file_application_metadata_message_proto_rawDescGZIP() []byte {
	file_application_metadata_message_proto_rawDescOnce.Do(func() {
		file_application_metadata_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_application_metadata_message_proto_rawDesc), len(file_application_metadata_message_proto_rawDesc)))
	})
	return file_application_metadata_message_proto_rawDescData
}

var file_application_metadata_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_application_metadata_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_application_metadata_message_proto_goTypes = []any{
	(ApplicationMetadataMessage_Type)(0), // 0: protobuf.ApplicationMetadataMessage.Type
	(*ApplicationMetadataMessage)(nil),   // 1: protobuf.ApplicationMetadataMessage
}
var file_application_metadata_message_proto_depIdxs = []int32{
	0, // 0: protobuf.ApplicationMetadataMessage.type:type_name -> protobuf.ApplicationMetadataMessage.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_application_metadata_message_proto_init() }
func file_application_metadata_message_proto_init() {
	if File_application_metadata_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_application_metadata_message_proto_rawDesc), len(file_application_metadata_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_application_metadata_message_proto_goTypes,
		DependencyIndexes: file_application_metadata_message_proto_depIdxs,
		EnumInfos:         file_application_metadata_message_proto_enumTypes,
		MessageInfos:      file_application_metadata_message_proto_msgTypes,
	}.Build()
	File_application_metadata_message_proto = out.File
	file_application_metadata_message_proto_goTypes = nil
	file_application_metadata_message_proto_depIdxs = nil
}
