_extends: probot-settings

github-team:
  slug: 'go'

prchecklist:
  title: Pull Request Checklist
  checklist:
    - 'Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status_go.html))?'
