_extends: probot-settings

github-team:
  slug: 'go'

prchecklist:
  title: Pull Request Checklist
  checklist:
    - 'Have you updated the documentation, if impacted (e.g. [docs.status.im](https://status.im/docs/))?'
    - 'Have you tested changes with mobile?'
    - 'Have you tested changes with desktop?'

stale:
  daysUntilStale: 90
  daysUntilPullRequestStale: 14
  daysUntilClose: 7
  exemptLabels:
    - 'wall of shame'
    - security
  staleLabel: stale
  markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.
  closeComment: >
    This issue has been automatically closed. Please re-open if this issue
    is important to you.
