coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

# When modifying this file, please validate using:
# make codecov-validate
