version: "2"
run:
  modules-download-mode: vendor
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - unconvert
  settings:
    dupl:
      threshold: 50
    errcheck:
      check-type-assertions: false
      check-blank: false
    goconst:
      min-len: 3
      min-occurrences: 2
    gosec:
      excludes:
        - G115
  exclusions:
    generated: lax
    presets:
      - std-error-handling
      - legacy
    paths:
    - contracts/
    rules:
      - linters:
          - goconst
        path: eth-node/keystore/passphrase\.go
        text: make it a constant
      - linters:
          - goconst
        path: protocol/message_handler\.go
        text: make it a constant
      - linters:
          - goconst
        path: protocol/.*_test\.go
        text: make it a constant
      - path: (.+)\.go$
        text: composite literal uses unkeyed fields
      - path: (.+)\.go$
        text: 'G304: Potential file inclusion via variable'
      - path: (.+)\.go$
        text: 'G104: Errors unhandled.'
      - path: (.+)\.go$
        text: lib._Ctype_char, which can be annoying to use
      - path: (.+)\.go$
        text: SA1019

formatters:
  enable:
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/status-im/status-go
  exclusions:
    generated: strict
    paths:
    - static
    - vendor