run:
  concurrency: 4
  deadline: 1m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - static
  skip-files:
    - .*_mock.go
    - jail/doc.go

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 16
  maligned:
    suggest-new: true
  dupl:
    threshold: 50
  goconst:
    min-len: 3
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosec
    - goconst
    - gocyclo
    - gofmt
    - golint
    - govet
    - ineffassign
    - interfacer
    - megacheck
    - misspell
    - structcheck
    - typecheck
    - unconvert
    - varcheck
  fast: false

issues:
  exclude:
    - "composite literal uses unkeyed fields" # govet
    - "G304: Potential file inclusion via variable" # gosec
    - "G104: Errors unhandled." #gosec
