[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "github.com/karalabe/hid"
    non-go = false
    unused-packages = false

  [[prune.project]]
    name = "github.com/ethereum/go-ethereum"
    unused-packages = false
    non-go = false


# * * * * * constrained `status-go` dependencies * * * * *
# (for the full dependency list see `Gopkg.lock`)

[[constraint]]
  name = "github.com/beevik/ntp"
  version = "=0.2.0"

[[constraint]]
  # `btcutil` is required to be compatible with `btcd`
  name = "github.com/btcsuite/btcutil"
  revision = "dcd4997b0664bcfd6ef48e4ae9da8396e08b1cd9"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "=v1.8.21"
  source = "github.com/status-im/go-ethereum"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "=1.2.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-crypto"
  version = "=v1.6.2"

[[constraint]]
  name = "github.com/NaySoftware/go-fcm"
  source = "github.com/status-im/go-fcm"
  version = "=v1.0.0-status"

[[constraint]]
  name = "github.com/status-im/whisper"
  version = "=v1.4.6"

[[constraint]]
  name = "golang.org/x/text"
  revision = "e19ae1496984b1c655b8044a65c0300a3c878dd3"

# * * * * * `status-im/rendezvous` dependencies * * * * *
# When upgrading upstream, upgrade these values with releases/tags.
[[override]]
  name = "github.com/status-im/go-multiaddr-ethv4"
  version = "=v1.0.0"

# * * * * * `status-im/migrate` dependencies * * * * *
# When upgrading upstream, upgrade these values with releases/tags.
[[override]]
  name = "github.com/mutecomm/go-sqlcipher"
  revision = "f799951b4ab269c2ce24913961af2cb5d681cc43"

# * * * * * `status-im/whisper` dependencies * * * * *
# When upgrading upstream, upgrade these values with releases/tags.
[[override]]
  name = "golang.org/x/sync"
  revision = "fd80eb99c8f653c847d294a001bdf2a3a6f768f5"

[[override]]
  name = "golang.org/x/crypto"
  revision = "ff983b9c42bc9fbf91556e191cc8efb585c16908"

# * * * * * `go-libp2p` dependencies * * * * *
# When upgrading upstream, upgrade these values with releases/tags.
[[override]]
  name = "github.com/gxed/GoEndian"
  revision = "0f5c6873267e5abf306ffcdfcfa4bf77517ef4a7"

[[override]]
  name = "github.com/gxed/eventfd"
  revision = "80a92cca79a8041496ccc9dd773fcb52a57ec6f9"

[[override]]
  name = "golang.org/x/sys"
  revision = "11551d06cbcc94edc80a0facaccbda56473c19c1"

[[override]]
  name = "github.com/whyrusleeping/go-logging"
  revision = "0457bb6b88fc1973573aaf6b5145d8d3ae972390"

[[override]]
  name = "github.com/whyrusleeping/go-notifier"
  revision = "097c5d47330ff6a823f67e3515faa13566a62c6f"

[[override]]
  name = "github.com/whyrusleeping/go-smux-multistream"
  revision = "c707bf3c25fa380b20b54907790efde288775938"

[[override]]
  name = "github.com/whyrusleeping/go-smux-yamux"
  revision = "eac25f3e2d47aae211e457e7664b52634c95eea8"

[[override]]
  name = "github.com/whyrusleeping/mafmt"
  revision = "1dc32401ee9fdd3f6cdb3405ec984d5dae877b2a"

[[override]]
  name = "github.com/whyrusleeping/multiaddr-filter"
  revision = "e903e4adabd70b78bc9293b6ee4f359afb3f9f59"

[[override]]
  name = "github.com/whyrusleeping/yamux"
  revision = "35d045d4429ecf19430a2b94efc590bc40f2f7af"

# * * * * * `go-libp2p-crypto` dependencies * * * * *
# When upgrading upstream, upgrade these values with releases/tags.
[[override]]
  name = "github.com/agl/ed2551"
  revision = "5312a61534124124185d41f09206b9fef1d88403"

[[override]]
  name = "github.com/agl/ed25519"
  revision = "5312a61534124124185d41f09206b9fef1d88403"

[[override]]
  name = "github.com/gxed/hashland"
  revision = "d9f6b97f8db22dd1e090fd0bbbe98f09cc7dd0a8"

[[override]]
  name = "github.com/jbenet/go-temp-err-catcher"
  revision = "aac704a3f4f27190b4ccc05f303a4931fd1241ff"

[[override]]
  name = "github.com/jbenet/goprocess"
  revision = "b497e2f366b8624394fb2e89c10ab607bebdde0b"

[[override]]
  name = "github.com/libp2p/go-conn-security-multistream"
  revision = "df26ef91ad66a626a4b7147fd95d18962395a20e"

[[override]]
  name = "github.com/minio/blake2b-simd"
  revision = "3f5f724cb5b182a5c278d6d3d55b40e7f8c2efb4"

[[override]]
  name = "github.com/minio/sha256-simd"
  revision = "ad98a36ba0da87206e3378c556abbfeaeaa98668"

# * * * * * `go-libp2p-peer` dependencies * * * * *
# When upgrading upstream, upgrade these values with releases/tags.
[[override]]
  name = "github.com/mr-tron/base58"
  revision = "4df4dc6e86a912614d09719d10cad427b087cbfb"

# * * * * * `go-ethereum` dependencies * * * * *
# Pinned down SHAs from `go-ethereum/vendor/vendor.json`
# When upgrading upstream, upgrade these values with releases/tags.
[[override]]
  name = "github.com/aristanetworks/goarista"
  revision = "ea17b1a17847fb6e4c0a91de0b674704693469b0"

[[override]]
  name = "github.com/fjl/memsize"
  revision = "f6d5545993d68e9e42df43eb57958f898dea3623"

[[override]]
  name = "github.com/btcsuite/btcd"
  revision = "d06c0bb181529331be8f8d9350288c420d9e60e4"

[[override]]
  name = "github.com/davecgh/go-spew"
  revision = "346938d642f2ec3594ed81d874461961cd0faa76"

[[override]]
  name = "github.com/edsrzf/mmap-go"
  revision = "935e0e8a636ca4ba70b713f3e38a19e1b77739e8"

[[override]]
  name = "github.com/go-stack/stack"
  revision = "54be5f394ed2c3e19dac9134a40a95ba5a017f7b"

[[override]]
  name = "github.com/golang/snappy"
  revision = "553a641470496b2327abcac10b36396bd98e45c9"

[[override]]
  name = "github.com/hashicorp/golang-lru"
  revision = "0a025b7e63adc15a622f29b0b2c4c3848243bbf6"

[[override]]
  name = "github.com/huin/goupnp"
  revision = "679507af18f3c7ba2bcc7905392ce23e148661c3"

[[override]]
  name = "github.com/jackpal/go-nat-pmp"
  revision = "1fa385a6f45828c83361136b45b1a21a12139493"

[[override]]
  name = "github.com/karalabe/hid"
  revision = "f00545f9f3748e591590be3732d913c77525b10f"

[[override]]
  name = "github.com/mattn/go-colorable"
  revision = "5411d3eea5978e6cdc258b30de592b60df6aba96"

[[override]]
  name = "github.com/mattn/go-isatty"
  revision = "3fb116b820352b7f0c281308a4d6250c22d94e27"

[[override]]
  name = "gopkg.in/natefinch/npipe.v2"
  revision = "c1b8fa8bdccecb0b8db834ee0b92fdbcfa606dd6"

[[override]]
  name = "gopkg.in/olebedev/go-duktape.v3"
  revision = "abf0ba0be5d5d36b1f9266463cc320b9a5ab224e"

[[override]]
  name = "github.com/pborman/uuid"
  revision = "1b00554d822231195d1babd97ff4a781231955c9"

[[override]]
  name = "github.com/pmezard/go-difflib"
  revision = "792786c7400a136282c1664665ae0a8db921c6c2"

[[override]]
  name = "github.com/prometheus/prometheus"
  revision = "3101606756c53221ed58ba94ecba6b26adf89dcc"

[[override]]
  name = "github.com/rcrowley/go-metrics"
  revision = "1f30fe9094a513ce4c700b9a54458bbb0c96996c"

[[override]]
  name = "github.com/rjeczalik/notify"
  version="=v0.9.2"

[[override]]
  name = "github.com/robertkrimen/otto"
  # (@mandrigin): This supposed to be contrained as:
  #
  # revision = "6a77b7cbc37d0c39f7d5fa5766826e541df31fd5"
  #
  # but it has relative imports that break everything.
  # The following revision only differs from the source
  # with fixing relative imports.
  revision = "9c716adcc8cedb0c0e3c02be549f4ad20e0b216c"

[[override]]
  name = "github.com/rs/cors"
  revision = "a62a804a8a009876ca59105f7899938a1349f4b3"

[[override]]
  name = "github.com/rs/xhandler"
  revision = "ed27b6fd65218132ee50cd95f38474a3d8a2cd12"

[[override]]
  name = "github.com/stretchr/testify"
  revision = "890a5c3458b43e6104ff5da8dfa139d013d77544"

[[override]]
  name = "github.com/syndtr/goleveldb"
  revision = "5d6fca44a948d2be89a9702de7717f0168403d3d"

[[override]]
  name = "github.com/multiformats/go-multiaddr"
  revision = "f36800afeb9c141e1adb7da099e6f010dfd4c419"

[[override]]
  name = "golang.org/x/net"
  revision = "5ccada7d0a7ba9aeb5d3aca8d3501b4c2a509fec"

# 1.0.8
[[override]]
  name = "github.com/multiformats/go-multihash"
  revision = "8be2a682ab9f254311de1375145a2f78a809b07d"

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"

[[constraint]]
  name = "github.com/status-im/rendezvous"
  version = "=v1.1.0"

[[override]]
  name = "github.com/deckarep/golang-set"
  revision = "504e848d77ea4752b3057b8fb46da0e7f746ccf3"

[[constraint]]
  name = "github.com/status-im/doubleratchet"
  version = "=v2.0.0"

[[constraint]]
  name = "github.com/status-im/migrate"
  version = "=v3.5.1-status"
