global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'wnode'
    static_configs:
      - targets: ['docker.for.mac.localhost:32794', 'docker.for.mac.localhost:32792']
