ALTER TABLE user_messages ADD COLUMN replace_message TEXT NOT NULL DEFAULT "";
ALTER TABLE user_messages ADD COLUMN rtl BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE user_messages ADD COLUMN line_count INT NOT NULL DEFAULT 0;
