ALTER TABLE chats ADD COLUMN synced_to INTEGER DEFAULT 0;
ALTER TABLE chats ADD COLUMN synced_from INTEGER DEFAULT 0;
ALTER TABLE user_messages ADD COLUMN gap_from INTEGER;
ALTER TABLE user_messages ADD COLUMN gap_to INTEGER;
