version: "3.9"

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "fd00:0:0:1::/64"
          gateway: "fd00:0:0:1::1"

services:
  anvil:
    networks:
      - default

  foundry:
    networks:
      - default
