services:
  boot-1:
    image: wakuorg/nwaku:v0.34.0
    entrypoint: [
      "/usr/bin/wakunode",
      "--discv5-discovery=true",
      "--discv5-enr-auto-update=True",
      "--discv5-udp-port=9000",
      "--cluster-id=16",
      # Docker DNS server
      "--dns-addrs-name-server=127.0.0.11",
      "--dns4-domain-name=boot-1",
      "--filter=true",
      "--keep-alive=true",
      "--lightpush=true",
      "--log-level=DEBUG",
      "--max-connections=18000",
      "--nodekey=03ce9122016be1f80a23df36525103bed1c7c4b9a0ff7605d97553ed8ed96bcf",
      "--peer-exchange=true",
      "--relay=true",
      "--rest-address=0.0.0.0",
      "--rest-admin",
      "--shard=32",
      "--shard=64",
      "--staticnode=/dns4/store/tcp/60002/p2p/16Uiu2HAmCDqxtfF1DwBqs7UJ4TgSnjoh6j1RtE1hhQxLLao84jLi",
      "--storenode=/dns4/store/tcp/60002/p2p/16Uiu2HAmCDqxtfF1DwBqs7UJ4TgSnjoh6j1RtE1hhQxLLao84jLi",
      "--tcp-port=60001"
    ]
    depends_on:
      - store

    healthcheck:
      test: ["CMD-SHELL", "curl -X GET -H 'Content-Type: application/json' http://0.0.0.0:8645 || exit 0"]
    ports:
      - "8645:8645/tcp"

  store:
    image: wakuorg/nwaku:v0.34.0
    entrypoint: [
      "/usr/bin/wakunode",
      "--discv5-discovery=true",
      "--discv5-enr-auto-update=True",
      "--discv5-udp-port=9000",
      "--discv5-bootstrap-node=enr:-La4QKi-GOzezuylyUIOA_6MFpbMUvhcVLg7v1KCXLR37tO6c5hgjAF6nzUbGM_9HG4LEM69JjTenYH0ZNFwOPg-UXIBgmlkgnY0gmlwhKwTAASKbXVsdGlhZGRyc40ACzYGYm9vdC0xBuphgnJzhwAQAgAgAECJc2VjcDI1NmsxoQJ-L7RtImvRuvgn_pQnJsag8tbaqPZ7mBM4Z1scEreWGoN0Y3CC6mGDdWRwgiMohXdha3UyDQ",
      "--cluster-id=16",
      # Docker DNS server
#      "--dns-discovery-name-server=127.0.0.11",
      "--dns-addrs-name-server=127.0.0.11",
      "--dns4-domain-name=store",
      "--keep-alive=true",
      "--log-level=DEBUG",
      "--max-connections=18000",
      "--nodekey=3190bc9b55b18dbc171997a7a67abcd5bbf0c81002ad9617b1cb67f2f15daa64",
      "--peer-exchange=false",
      "--relay=true",
      "--rest-address=0.0.0.0",
      "--rest-admin",
      "--shard=32",
      "--shard=64",
#      "--staticnode=/dns4/boot-1/tcp/60001/p2p/16Uiu2HAm3vFYHkGRURyJ6F7bwDyzMLtPEuCg4DU89T7km2u8Fjyb",
      "--store=true",
      "--tcp-port=60002"
    ]
    healthcheck:
      test: ["CMD-SHELL", "curl -X GET -H 'Content-Type: application/json' http://0.0.0.0:8645 || exit 0"]
#      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8645/admin/v1/peers | jq 'length>0' | grep -q true"]
#      interval: 5s
#      timeout: 60s
#      retries: 100
#      start_period: 10s
    ports:
      - "8646:8645/tcp"

  node-1:
    image: wakuorg/nwaku:v0.34.0
    entrypoint: [
      "/usr/bin/wakunode",
      "--discv5-discovery=true",
      "--discv5-enr-auto-update=True",
      "--discv5-udp-port=9000",
      "--discv5-bootstrap-node=enr:-La4QKi-GOzezuylyUIOA_6MFpbMUvhcVLg7v1KCXLR37tO6c5hgjAF6nzUbGM_9HG4LEM69JjTenYH0ZNFwOPg-UXIBgmlkgnY0gmlwhKwTAASKbXVsdGlhZGRyc40ACzYGYm9vdC0xBuphgnJzhwAQAgAgAECJc2VjcDI1NmsxoQJ-L7RtImvRuvgn_pQnJsag8tbaqPZ7mBM4Z1scEreWGoN0Y3CC6mGDdWRwgiMohXdha3UyDQ",
      "--cluster-id=16",
      # Docker DNS server
      "--dns-addrs-name-server=127.0.0.11",
      "--dns4-domain-name=node-1",
      "--filter=true",
      "--keep-alive=true",
      "--lightpush=true",
      "--log-level=DEBUG",
      "--max-connections=18000",
      "--nodekey=451ee0adb90a7970dca8a757bca58e9a66c02dcf928e1c55e9b49319a2407ac0",
      "--peer-exchange=true",
      "--relay=true",
      "--rest-address=0.0.0.0",
      "--rest-admin",
      "--shard=32",
      "--shard=64",
      "--tcp-port=60003"
    ]
#    depends_on:
#      store:
#        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "curl -X GET -H 'Content-Type: application/json' http://0.0.0.0:8645 || exit 0"]
    ports:
      - "8647:8645/tcp"