version: "3.9"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.11.0.0/24

services:
  anvil:
    networks:
      - default

  foundry:
    networks:
      - default
