package protocol

type Currency struct {
	Id          string `json:"id"`
	ShortName   string `json:"shortName"`
	Name        string `json:"name"`
	Symbol      string `json:"symbol"`
	Emoji       string `json:"emoji"`
	ImageSource string `json:"imageSource"` // used by desktop app
	IsToken     bool   `json:"isToken"`
	IsPopular   bool   `json:"isPopular"` // to help the UI to show popular currencies in separate section
}

// This list serves as a common currencies data which can be used across platforms
// This data is moved from status-desktop
// https://github.com/status-im/status-desktop/blob/2b415bdc5359f424fbfcabf1b5319bc3a8595921/ui/imports/shared/stores/CurrenciesStore.qml#L30
var currencyList = []*Currency{
	&Currency{
		Id:          "usd",
		ShortName:   "USD",
		Name:        "United States Dollar",
		Symbol:      "$",
		Emoji:       "🇺🇸",
		ImageSource: "../../assets/twemoji/svg/1f1fa-1f1f8.svg",
		IsPopular:   true,
		IsToken:     false,
	},
	&Currency{
		Id:          "gbp",
		ShortName:   "GBP",
		Name:        "Great Britain Pound",
		Symbol:      "£",
		Emoji:       "🇬🇧",
		ImageSource: "../../assets/twemoji/svg/1f1ec-1f1e7.svg",
		IsPopular:   true,
		IsToken:     false,
	},
	&Currency{
		Id:          "eur",
		ShortName:   "EUR",
		Name:        "Euro",
		Symbol:      "€",
		Emoji:       "🇪🇺",
		ImageSource: "../../assets/twemoji/svg/1f1ea-1f1fa.svg",
		IsPopular:   true,
		IsToken:     false,
	},
	&Currency{
		Id:          "rub",
		ShortName:   "RUB",
		Name:        "Russian Ruble",
		Symbol:      "₽",
		Emoji:       "🇷🇺",
		ImageSource: "../../assets/twemoji/svg/1f1f7-1f1fa.svg",
		IsPopular:   true,
		IsToken:     false,
	},
	&Currency{
		Id:          "krw",
		ShortName:   "KRW",
		Name:        "South Korean Won",
		Symbol:      "₩",
		Emoji:       "🇰🇷",
		ImageSource: "../../assets/twemoji/svg/1f1f0-1f1f7.svg",
		IsPopular:   true,
		IsToken:     false,
	},
	&Currency{
		Id:          "eth",
		ShortName:   "ETH",
		Name:        "Ethereum",
		Symbol:      "",
		Emoji:       "",
		ImageSource: "../../../../imports/assets/png/tokens/ETH.png",
		IsPopular:   false,
		IsToken:     true,
	},
	&Currency{
		Id:          "btc",
		ShortName:   "BTC",
		Name:        "Bitcoin",
		Symbol:      "",
		Emoji:       "",
		ImageSource: "../../../../imports/assets/png/tokens/WBTC.png",
		IsPopular:   false,
		IsToken:     true,
	},
	&Currency{
		Id:          "snt",
		ShortName:   "SNT",
		Name:        "Status Network Token",
		Symbol:      "",
		Emoji:       "",
		ImageSource: "../../../../imports/assets/png/tokens/SNT.png",
		IsPopular:   false,
		IsToken:     true,
	},
	&Currency{
		Id:          "dai",
		ShortName:   "DAI",
		Name:        "DAI",
		Symbol:      "",
		Emoji:       "",
		ImageSource: "../../../../imports/assets/png/tokens/DAI.png",
		IsPopular:   false,
		IsToken:     true,
	},
	&Currency{
		Id:          "aed",
		ShortName:   "AED",
		Name:        "United Arab Emirates Dirham",
		Symbol:      "د.إ",
		Emoji:       "🇦🇪",
		ImageSource: "../../assets/twemoji/svg/1f1e6-1f1ea.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "afn",
		ShortName:   "AFN",
		Name:        "Afghan Afghani",
		Symbol:      "؋",
		Emoji:       "🇦🇫",
		ImageSource: "../../assets/twemoji/svg/1f1e6-1f1eb.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "ars",
		ShortName:   "ARS",
		Name:        "Argentine Peso",
		Symbol:      "$",
		Emoji:       "🇦🇷",
		ImageSource: "../../assets/twemoji/svg/1f1e6-1f1f7.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "aud",
		ShortName:   "AUD",
		Name:        "Australian Dollar",
		Symbol:      "$",
		Emoji:       "🇦🇺",
		ImageSource: "../../assets/twemoji/svg/1f1e6-1f1fa.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "bbd",
		ShortName:   "BBD",
		Name:        "Barbadian Dollar",
		Symbol:      "$",
		Emoji:       "🇧🇧",
		ImageSource: "../../assets/twemoji/svg/1f1e7-1f1e7.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "bdt",
		ShortName:   "BDT",
		Name:        "Bangladeshi Taka",
		Symbol:      "Tk",
		Emoji:       "🇧🇩",
		ImageSource: "../../assets/twemoji/svg/1f1e7-1f1e9.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "bgn",
		ShortName:   "BGN",
		Name:        "Bulgarian Lev",
		Symbol:      "лв",
		Emoji:       "🇧🇬",
		ImageSource: "../../assets/twemoji/svg/1f1e7-1f1ec.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "bhd",
		ShortName:   "BHD",
		Name:        "Bahraini Dinar",
		Symbol:      "BD",
		Emoji:       "🇧🇭",
		ImageSource: "../../assets/twemoji/svg/1f1e7-1f1ed.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "bnd",
		ShortName:   "BND",
		Name:        "Brunei Dollar",
		Symbol:      "$",
		Emoji:       "🇧🇳",
		ImageSource: "../../assets/twemoji/svg/1f1e7-1f1f3.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "bob",
		ShortName:   "BOB",
		Name:        "Bolivian Boliviano",
		Symbol:      "$b",
		Emoji:       "🇧🇴",
		ImageSource: "../../assets/twemoji/svg/1f1e7-1f1f4.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "brl",
		ShortName:   "BRL",
		Name:        "Brazilian Real",
		Symbol:      "R$",
		Emoji:       "🇧🇷",
		ImageSource: "../../assets/twemoji/svg/1f1e7-1f1f7.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "btn",
		ShortName:   "BTN",
		Name:        "Bhutanese Ngultrum",
		Symbol:      "Nu.",
		Emoji:       "🇧🇹",
		ImageSource: "../../assets/twemoji/svg/1f1e7-1f1f9.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "cad",
		ShortName:   "CAD",
		Name:        "Canadian Dollar",
		Symbol:      "$",
		Emoji:       "🇨🇦",
		ImageSource: "../../assets/twemoji/svg/1f1e8-1f1e6.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "chf",
		ShortName:   "CHF",
		Name:        "Swiss Franc",
		Symbol:      "CHF",
		Emoji:       "🇨🇭",
		ImageSource: "../../assets/twemoji/svg/1f1e8-1f1ed.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "clp",
		ShortName:   "CLP",
		Name:        "Chilean Peso",
		Symbol:      "$",
		Emoji:       "🇨🇱",
		ImageSource: "../../assets/twemoji/svg/1f1e8-1f1f1.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "cny",
		ShortName:   "CNY",
		Name:        "Chinese Yuan",
		Symbol:      "¥",
		Emoji:       "🇨🇳",
		ImageSource: "../../assets/twemoji/svg/1f1e8-1f1f3.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "cop",
		ShortName:   "COP",
		Name:        "Colombian Peso",
		Symbol:      "$",
		Emoji:       "🇨🇴",
		ImageSource: "../../assets/twemoji/svg/1f1e8-1f1f4.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "crc",
		ShortName:   "CRC",
		Name:        "Costa Rican Colón",
		Symbol:      "₡",
		Emoji:       "🇨🇷",
		ImageSource: "../../assets/twemoji/svg/1f1e8-1f1f7.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "czk",
		ShortName:   "CZK",
		Name:        "Czech Koruna",
		Symbol:      "Kč",
		Emoji:       "🇨🇿",
		ImageSource: "../../assets/twemoji/svg/1f1e8-1f1ff.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "dkk",
		ShortName:   "DKK",
		Name:        "Danish Krone",
		Symbol:      "kr",
		Emoji:       "🇩🇰",
		ImageSource: "../../assets/twemoji/svg/1f1e9-1f1f0.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "dop",
		ShortName:   "DOP",
		Name:        "Dominican Peso",
		Symbol:      "RD$",
		Emoji:       "🇩🇴",
		ImageSource: "../../assets/twemoji/svg/1f1e9-1f1f4.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "egp",
		ShortName:   "EGP",
		Name:        "Egyptian Pound",
		Symbol:      "£",
		Emoji:       "🇪🇬",
		ImageSource: "../../assets/twemoji/svg/1f1ea-1f1ec.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "etb",
		ShortName:   "ETB",
		Name:        "Ethiopian Birr",
		Symbol:      "Br",
		Emoji:       "🇪🇹",
		ImageSource: "../../assets/twemoji/svg/1f1ea-1f1f9.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "gel",
		ShortName:   "GEL",
		Name:        "Georgian Lari",
		Symbol:      "₾",
		Emoji:       "🇬🇪",
		ImageSource: "../../assets/twemoji/svg/1f1ec-1f1ea.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "ghs",
		ShortName:   "GHS",
		Name:        "Ghanaian Cedi",
		Symbol:      "¢",
		Emoji:       "🇬🇭",
		ImageSource: "../../assets/twemoji/svg/1f1ec-1f1ed.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "hkd",
		ShortName:   "HKD",
		Name:        "Hong Kong Dollar",
		Symbol:      "$",
		Emoji:       "🇭🇰",
		ImageSource: "../../assets/twemoji/svg/1f1ed-1f1f0.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "hrk",
		ShortName:   "HRK",
		Name:        "Croatian Kuna",
		Symbol:      "kn",
		Emoji:       "🇭🇷",
		ImageSource: "../../assets/twemoji/svg/1f1ed-1f1f7.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "huf",
		ShortName:   "HUF",
		Name:        "Hungarian Forint",
		Symbol:      "Ft",
		Emoji:       "🇭🇺",
		ImageSource: "../../assets/twemoji/svg/1f1ed-1f1fa.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "idr",
		ShortName:   "IDR",
		Name:        "Indonesian Rupiah",
		Symbol:      "Rp",
		Emoji:       "🇮🇩",
		ImageSource: "../../assets/twemoji/svg/1f1ee-1f1e9.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "ils",
		ShortName:   "ILS",
		Name:        "Israeli New Shekel",
		Symbol:      "₪",
		Emoji:       "🇮🇱",
		ImageSource: "../../assets/twemoji/svg/1f1ee-1f1f1.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "inr",
		ShortName:   "INR",
		Name:        "Indian Rupee",
		Symbol:      "₹",
		Emoji:       "🇮🇳",
		ImageSource: "../../assets/twemoji/svg/1f1ee-1f1f3.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "isk",
		ShortName:   "ISK",
		Name:        "Icelandic Króna",
		Symbol:      "kr",
		Emoji:       "🇮🇸",
		ImageSource: "../../assets/twemoji/svg/1f1ee-1f1f8.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "jmd",
		ShortName:   "JMD",
		Name:        "Jamaican Dollar",
		Symbol:      "J$",
		Emoji:       "🇯🇲",
		ImageSource: "../../assets/twemoji/svg/1f1ef-1f1f2.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "jpy",
		ShortName:   "JPY",
		Name:        "Japanese Yen",
		Symbol:      "¥",
		Emoji:       "🇯🇵",
		ImageSource: "../../assets/twemoji/svg/1f1ef-1f1f5.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "kes",
		ShortName:   "KES",
		Name:        "Kenyan Shilling",
		Symbol:      "KSh",
		Emoji:       "🇰🇪",
		ImageSource: "../../assets/twemoji/svg/1f1f0-1f1ea.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "kwd",
		ShortName:   "KWD",
		Name:        "Kuwaiti Dinar",
		Symbol:      "د.ك",
		Emoji:       "🇰🇼",
		ImageSource: "../../assets/twemoji/svg/1f1f0-1f1fc.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "kzt",
		ShortName:   "KZT",
		Name:        "Kazakhstani Tenge",
		Symbol:      "лв",
		Emoji:       "🇰🇿",
		ImageSource: "../../assets/twemoji/svg/1f1f0-1f1ff.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "lkr",
		ShortName:   "LKR",
		Name:        "Sri Lankan Rupee",
		Symbol:      "₨",
		Emoji:       "🇱🇰",
		ImageSource: "../../assets/twemoji/svg/1f1f1-1f1f0.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "mad",
		ShortName:   "MAD",
		Name:        "Moroccan Dirham",
		Symbol:      "MAD",
		Emoji:       "🇲🇦",
		ImageSource: "../../assets/twemoji/svg/1f1f2-1f1e6.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "mdl",
		ShortName:   "MDL",
		Name:        "Moldovan Leu",
		Symbol:      "MDL",
		Emoji:       "🇲🇩",
		ImageSource: "../../assets/twemoji/svg/1f1f2-1f1e9.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "mur",
		ShortName:   "MUR",
		Name:        "Mauritian Rupee",
		Symbol:      "₨",
		Emoji:       "🇲🇺",
		ImageSource: "../../assets/twemoji/svg/1f1f2-1f1f7.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "mwk",
		ShortName:   "MWK",
		Name:        "Malawian Kwacha",
		Symbol:      "MK",
		Emoji:       "🇲🇼",
		ImageSource: "../../assets/twemoji/svg/1f1f2-1f1fc.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "mxn",
		ShortName:   "MXN",
		Name:        "Mexican Peso",
		Symbol:      "$",
		Emoji:       "🇲🇽",
		ImageSource: "../../assets/twemoji/svg/1f1f2-1f1fd.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "myr",
		ShortName:   "MYR",
		Name:        "Malaysian Ringgit",
		Symbol:      "RM",
		Emoji:       "🇲🇾",
		ImageSource: "../../assets/twemoji/svg/1f1f2-1f1fe.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "mzn",
		ShortName:   "MZN",
		Name:        "Mozambican metical",
		Symbol:      "MT",
		Emoji:       "🇲🇿",
		ImageSource: "../../assets/twemoji/svg/1f1f2-1f1ff.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "nad",
		ShortName:   "NAD",
		Name:        "Namibian Dollar",
		Symbol:      "$",
		Emoji:       "🇳🇦",
		ImageSource: "../../assets/twemoji/svg/1f1f3-1f1e6.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "ngn",
		ShortName:   "NGN",
		Name:        "Nigerian Naira",
		Symbol:      "₦",
		Emoji:       "🇳🇬",
		ImageSource: "../../assets/twemoji/svg/1f1f3-1f1ec.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "nok",
		ShortName:   "NOK",
		Name:        "Norwegian Krone",
		Symbol:      "kr",
		Emoji:       "🇳🇴",
		ImageSource: "../../assets/twemoji/svg/1f1f3-1f1f4.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "npr",
		ShortName:   "NPR",
		Name:        "Nepalese Rupee",
		Symbol:      "₨",
		Emoji:       "🇳🇵",
		ImageSource: "../../assets/twemoji/svg/1f1f3-1f1f5.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "nzd",
		ShortName:   "NZD",
		Name:        "New Zealand Dollar",
		Symbol:      "$",
		Emoji:       "🇳🇿",
		ImageSource: "../../assets/twemoji/svg/1f1f3-1f1ff.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "omr",
		ShortName:   "OMR",
		Name:        "Omani Rial",
		Symbol:      "﷼",
		Emoji:       "🇴🇲",
		ImageSource: "../../assets/twemoji/svg/1f1f4-1f1f2.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "pen",
		ShortName:   "PEN",
		Name:        "Peruvian Sol",
		Symbol:      "S/.",
		Emoji:       "🇵🇪",
		ImageSource: "../../assets/twemoji/svg/1f1f5-1f1ea.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "pgk",
		ShortName:   "PGK",
		Name:        "Papua New Guinean Kina",
		Symbol:      "K",
		Emoji:       "🇵🇬",
		ImageSource: "../../assets/twemoji/svg/1f1f5-1f1ec.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "php",
		ShortName:   "PHP",
		Name:        "Philippine peso",
		Symbol:      "₱",
		Emoji:       "🇵🇭",
		ImageSource: "../../assets/twemoji/svg/1f1f5-1f1ed.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "pkr",
		ShortName:   "PKR",
		Name:        "Pakistani Rupee",
		Symbol:      "₨",
		Emoji:       "🇵🇰",
		ImageSource: "../../assets/twemoji/svg/1f1f5-1f1f0.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "pln",
		ShortName:   "PLN",
		Name:        "Polish złoty",
		Symbol:      "zł",
		Emoji:       "🇵🇱",
		ImageSource: "../../assets/twemoji/svg/1f1f5-1f1f1.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "pyg",
		ShortName:   "PYG",
		Name:        "Paraguayan Guarani",
		Symbol:      "Gs",
		Emoji:       "🇵🇾",
		ImageSource: "../../assets/twemoji/svg/1f1f5-1f1fe.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "qar",
		ShortName:   "QAR",
		Name:        "Qatari Riyal",
		Symbol:      "﷼",
		Emoji:       "🇶🇦",
		ImageSource: "../../assets/twemoji/svg/1f1f6-1f1e6.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "ron",
		ShortName:   "RON",
		Name:        "Romanian Leu",
		Symbol:      "lei",
		Emoji:       "🇷🇴",
		ImageSource: "../../assets/twemoji/svg/1f1f7-1f1f4.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "rsd",
		ShortName:   "RSD",
		Name:        "Serbian Dinar",
		Symbol:      "Дин.",
		Emoji:       "🇷🇸",
		ImageSource: "../../assets/twemoji/svg/1f1f7-1f1f8.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "sar",
		ShortName:   "SAR",
		Name:        "Saudi Riyal",
		Symbol:      "﷼",
		Emoji:       "🇸🇦",
		ImageSource: "../../assets/twemoji/svg/1f1f8-1f1e6.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "sek",
		ShortName:   "SEK",
		Name:        "Swedish Krona",
		Symbol:      "kr",
		Emoji:       "🇸🇪",
		ImageSource: "../../assets/twemoji/svg/1f1f8-1f1ea.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "sgd",
		ShortName:   "SGD",
		Name:        "Singapore Dollar",
		Symbol:      "$",
		Emoji:       "🇸🇬",
		ImageSource: "../../assets/twemoji/svg/1f1f8-1f1ec.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "thb",
		ShortName:   "THB",
		Name:        "Thai Baht",
		Symbol:      "฿",
		Emoji:       "🇹🇭",
		ImageSource: "../../assets/twemoji/svg/1f1f9-1f1ed.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "ttd",
		ShortName:   "TTD",
		Name:        "Trinidad and Tobago Dollar",
		Symbol:      "TT$",
		Emoji:       "🇹🇹",
		ImageSource: "../../assets/twemoji/svg/1f1f9-1f1f9.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "twd",
		ShortName:   "TWD",
		Name:        "New Taiwan dollar",
		Symbol:      "NT$",
		Emoji:       "🇹🇼",
		ImageSource: "../../assets/twemoji/svg/1f1f9-1f1fc.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "tzs",
		ShortName:   "TZS",
		Name:        "Tanzanian Shilling",
		Symbol:      "TSh",
		Emoji:       "🇹🇿",
		ImageSource: "../../assets/twemoji/svg/1f1f9-1f1ff.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "try",
		ShortName:   "TRY",
		Name:        "Turkish lira",
		Symbol:      "₺",
		Emoji:       "🇹🇷",
		ImageSource: "../../assets/twemoji/svg/1f1f9-1f1f7.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "uah",
		ShortName:   "UAH",
		Name:        "Ukrainian hryvnia",
		Symbol:      "₴",
		Emoji:       "🇺🇦",
		ImageSource: "../../assets/twemoji/svg/1f1fa-1f1e6.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "ugx",
		ShortName:   "UGX",
		Name:        "Ugandan Shilling",
		Symbol:      "USh",
		Emoji:       "🇺🇬",
		ImageSource: "../../assets/twemoji/svg/1f1fa-1f1ec.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "uyu",
		ShortName:   "UYU",
		Name:        "Uruguayan peso",
		Symbol:      "$U",
		Emoji:       "🇺🇾",
		ImageSource: "../../assets/twemoji/svg/1f1fa-1f1fe.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "vef",
		ShortName:   "VEF",
		Name:        "Venezuelan Bolívar",
		Symbol:      "Bs",
		Emoji:       "🇻🇪",
		ImageSource: "../../assets/twemoji/svg/1f1fb-1f1ea.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "vnd",
		ShortName:   "VND",
		Name:        "Vietnamese đồng",
		Symbol:      "₫",
		Emoji:       "🇻🇳",
		ImageSource: "../../assets/twemoji/svg/1f1fb-1f1f3.svg",
		IsPopular:   false,
		IsToken:     false,
	},
	&Currency{
		Id:          "zar",
		ShortName:   "ZAR",
		Name:        "South African Rand",
		Symbol:      "R",
		Emoji:       "🇿🇦",
		ImageSource: "../../assets/twemoji/svg/1f1ff-1f1e6.svg",
		IsPopular:   false,
		IsToken:     false,
	},
}

func GetCurrencies() []*Currency {
	return currencyList
}
