CREATE TABLE IF NOT EXISTS transfers (
hash VARCHAR UNIQUE NOT NULL,
blk_hash VARCHAR NOT NULL,
tx BLOB,
receipt BLOB,
type VARCHAR NOT NULL,
FOREIGN KEY(blk_hash) REFERENCES blocks(hash) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS blocks (
hash VARCHAR PRIMARY KEY,
number BIGINT UNIQUE NOT NULL,
header BLOB,
sync INT
) WITHOUT ROWID;
