version: "3"
services:
  bootnode:
    image: ethereum/client-go:alltools-latest
    entrypoint: bootnode
    command: -addr=:30303 -nodekey /static/keys/bootnode.key
    ports:
      - 30303
    volumes:
      - ./../../../static/keys:/static/keys:ro
    networks:
      cluster:
        ipv4_address: 172.16.238.10

  wnode:
    image: statusteam/status-go:latest
    command:
      - "-c"
      - "/config/wnode-config.json"
    ports:
      - 8080
      - 8545
      - 30303
    networks:
      cluster:
    volumes:
      - ./wnode-config.json:/config/wnode-config.json:ro
      - ./.ethereumtest:/data/ethereumtest/:rw
    depends_on:
      - bootnode

networks:
  cluster:
    driver: overlay
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
