package networkdefaults

import (
	"github.com/status-im/status-go/pkg/security"
	"github.com/status-im/status-go/services/wallet/common"
)

var defaultNetworkSpecs = []networkSpec{
	{
		chainID:          common.EthereumMainnet,
		proxyChainName:   "ethereum",
		proxyNetworkName: "mainnet",
		chainName:        "Ethereum",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://mainnet.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectGrove, directURL: security.NewSensitiveString("https://eth.rpc.grove.city/v1/")},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://etherscan.io/",
		chainColor:             "#627EEA",
		shortName:              "eth",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 false,
		layer:                  1,
		enabled:                true,
		relatedChainID:         common.EthereumHoodi,
		isActive:               true,
		isDeactivatable:        false,
	},
	{
		chainID:          common.EthereumHoodi,
		proxyChainName:   "ethereum",
		proxyNetworkName: "hoodi",
		chainName:        "Hoodi",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://hoodi.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://hoodi.etherscan.io/",
		chainColor:             "#627EEA",
		shortName:              "eth",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 true,
		layer:                  1,
		enabled:                true,
		relatedChainID:         common.EthereumMainnet,
		isActive:               true,
		isDeactivatable:        false,
	},
	{
		chainID:          common.EthereumSepolia,
		proxyChainName:   "ethereum",
		proxyNetworkName: "sepolia",
		chainName:        "Sepolia",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://sepolia.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectGrove, directURL: security.NewSensitiveString("https://eth-sepolia-testnet.rpc.grove.city/v1/")},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://sepolia.etherscan.io/",
		chainColor:             "#627EEA",
		shortName:              "eth",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 true,
		layer:                  1,
		enabled:                false,
		relatedChainID:         common.EthereumMainnet,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.OptimismMainnet,
		proxyChainName:   "optimism",
		proxyNetworkName: "mainnet",
		chainName:        "Optimism",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://optimism-mainnet.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectGrove, directURL: security.NewSensitiveString("https://optimism.rpc.grove.city/v1/")},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://optimistic.etherscan.io/",
		chainColor:             "#E90101",
		shortName:              "oeth",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 false,
		layer:                  2,
		enabled:                true,
		relatedChainID:         common.OptimismSepolia,
		isActive:               true,
		isDeactivatable:        true,
	},
	{
		chainID:          common.OptimismSepolia,
		proxyChainName:   "optimism",
		proxyNetworkName: "sepolia",
		chainName:        "Optimism Sepolia",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://optimism-sepolia.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectGrove, directURL: security.NewSensitiveString("https://optimism-sepolia-testnet.rpc.grove.city/v1/")},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://sepolia-optimism.etherscan.io/",
		chainColor:             "#E90101",
		shortName:              "oeth",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 true,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.OptimismMainnet,
		isActive:               true,
		isDeactivatable:        true,
	},
	{
		chainID:          common.ArbitrumMainnet,
		proxyChainName:   "arbitrum",
		proxyNetworkName: "mainnet",
		chainName:        "Arbitrum",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://arbitrum-mainnet.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectGrove, directURL: security.NewSensitiveString("https://arbitrum-one.rpc.grove.city/v1/")},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://arbiscan.io/",
		chainColor:             "#51D0F0",
		shortName:              "arb1",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 false,
		layer:                  2,
		enabled:                true,
		relatedChainID:         common.ArbitrumSepolia,
		isActive:               true,
		isDeactivatable:        true,
	},
	{
		chainID:          common.ArbitrumSepolia,
		proxyChainName:   "arbitrum",
		proxyNetworkName: "sepolia",
		chainName:        "Arbitrum Sepolia",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://arbitrum-sepolia.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectGrove, directURL: security.NewSensitiveString("https://arbitrum-sepolia-testnet.rpc.grove.city/v1/")},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://sepolia.arbiscan.io/",
		chainColor:             "#51D0F0",
		shortName:              "arb1",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 true,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.ArbitrumMainnet,
		isActive:               true,
		isDeactivatable:        true,
	},
	{
		chainID:          common.BaseMainnet,
		proxyChainName:   "base",
		proxyNetworkName: "mainnet",
		chainName:        "Base",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://base-mainnet.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectGrove, directURL: security.NewSensitiveString("https://base.rpc.grove.city/v1/")},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://basescan.org",
		chainColor:             "#0052FF",
		shortName:              "base",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 false,
		layer:                  2,
		enabled:                true,
		relatedChainID:         common.BaseSepolia,
		isActive:               true,
		isDeactivatable:        true,
	},
	{
		chainID:          common.BaseSepolia,
		proxyChainName:   "base",
		proxyNetworkName: "sepolia",
		chainName:        "Base Sepolia",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://base-sepolia.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectGrove, directURL: security.NewSensitiveString("https://base-testnet.rpc.grove.city/v1/")},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://sepolia.basescan.org/",
		chainColor:             "#0052FF",
		shortName:              "base",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 true,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.BaseMainnet,
		isActive:               true,
		isDeactivatable:        true,
	},
	{
		chainID:          common.LineaMainnet,
		proxyChainName:   "linea",
		proxyNetworkName: "mainnet",
		chainName:        "Linea",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://linea-mainnet.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectGrove, directURL: security.NewSensitiveString("https://linea.rpc.grove.city/v1/")},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://lineascan.build/",
		chainColor:             "#121212",
		shortName:              "linea",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 false,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.LineaSepolia,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.LineaSepolia,
		proxyChainName:   "linea",
		proxyNetworkName: "sepolia",
		chainName:        "Linea Sepolia",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://linea-sepolia.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectGrove, directURL: security.NewSensitiveString("https://linea-sepolia-testnet.rpc.grove.city/v1/")},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://sepolia.lineascan.build/",
		chainColor:             "#121212",
		shortName:              "linea",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 true,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.LineaMainnet,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.PolygonZkEVMMainnet,
		proxyChainName:   "polygon-zkevm",
		proxyNetworkName: "mainnet",
		chainName:        "Polygon zkEVM",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			// no support for polygon zkevm on infura
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://zkevm-rpc.com"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://www.oklink.com/polygon-zkevm/", // this is official, but doesn't work: "https://zkevm.polygonscan.com/",
		chainColor:             "#7B3FE4",
		shortName:              "zkevm",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 false,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.PolygonZkEVMCardona,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.PolygonZkEVMCardona,
		proxyChainName:   "polygon-zkevm",
		proxyNetworkName: "cardona",
		chainName:        "Polygon zkEVM Cardona",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			// no support for polygon zkevm on infura
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://rpc.cardona.zkevm-rpc.com"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://explorer.zkevm-testnet.com/",
		chainColor:             "#7B3FE4",
		shortName:              "zkevm",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 true,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.PolygonZkEVMMainnet,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.UnichainMainnet,
		proxyChainName:   "unichain",
		proxyNetworkName: "mainnet",
		chainName:        "Unichain",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://unichain-mainnet.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://mainnet.unichain.org"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://unichain.blockscout.com/",
		chainColor:             "#F50DB4",
		shortName:              "unichain",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 false,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.UnichainSepolia,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.UnichainSepolia,
		proxyChainName:   "unichain",
		proxyNetworkName: "sepolia",
		chainName:        "Unichain Sepolia",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://unichain-sepolia.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://sepolia.unichain.org"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://unichain-sepolia.blockscout.com/",
		chainColor:             "#F50DB4",
		shortName:              "unichain",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 true,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.UnichainMainnet,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.KatanaMainnet,
		proxyChainName:   "katana",
		proxyNetworkName: "mainnet",
		chainName:        "Katana",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			// no support for katana on infura
			// no support for katana on alchemy
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://rpc.katana.network"), enableRpsLimiter: true},
		},
		blockExplorerURL:       "https://katanascan.com/",
		chainColor:             "#F6FF0D",
		shortName:              "katana",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 false,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.KatanaBokuto,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.KatanaBokuto,
		proxyChainName:   "katana",
		proxyNetworkName: "bokuto",
		chainName:        "Katana Bokuto",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			// no support for katana on infura
			// no support for katana on alchemy
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://rpc-bokuto.katanarpc.com"), enableRpsLimiter: true},
		},
		blockExplorerURL:       "https://bokuto.katanascan.com/",
		chainColor:             "#F6FF0D",
		shortName:              "katana",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 true,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.KatanaMainnet,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.InkMainnet,
		proxyChainName:   "ink",
		proxyNetworkName: "mainnet",
		chainName:        "Ink",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			// no support for ink on infura
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://rpc-gel.inkonchain.com"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://explorer.inkonchain.com/",
		chainColor:             "#7757E2",
		shortName:              "ink",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 false,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.InkSepolia,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.InkSepolia,
		proxyChainName:   "ink",
		proxyNetworkName: "sepolia",
		chainName:        "Ink Sepolia",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			// no support for ink on infura
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://rpc-gel-sepolia.inkonchain.com"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://explorer-sepolia.inkonchain.com/",
		chainColor:             "#7757E2",
		shortName:              "ink",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 true,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.InkMainnet,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.AbstractMainnet,
		proxyChainName:   "abstract",
		proxyNetworkName: "mainnet",
		chainName:        "Abstract",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			// no support for abstract on infura
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://abstract.drpc.org"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://abscan.org/",
		chainColor:             "#054729",
		shortName:              "abstract",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 false,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.AbstractTestnet,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.AbstractTestnet,
		proxyChainName:   "abstract",
		proxyNetworkName: "testnet",
		chainName:        "Abstract Sepolia",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			// no support for abstract on infura
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://abstract-sepolia.drpc.org"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://sepolia.abscan.org/",
		chainColor:             "#054729",
		shortName:              "abstract",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 true,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.AbstractMainnet,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.ZkSyncMainnet,
		proxyChainName:   "zksync",
		proxyNetworkName: "mainnet",
		chainName:        "zkSync",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://zksync-mainnet.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://mainnet.era.zksync.io"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://explorer.zksync.io/",
		chainColor:             "#000000",
		shortName:              "zksync",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 false,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.ZkSyncSepolia,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.ZkSyncSepolia,
		proxyChainName:   "zksync",
		proxyNetworkName: "sepolia",
		chainName:        "zkSync Sepolia",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://zksync-sepolia.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://sepolia.era.zksync.dev"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://sepolia.explorer.zksync.io/",
		chainColor:             "#000000",
		shortName:              "zksync",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 true,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.ZkSyncMainnet,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.SoneiumMainnet,
		proxyChainName:   "soneium",
		proxyNetworkName: "mainnet",
		chainName:        "Soneium",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			// no support for soneium on infura
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://rpc.soneium.org/"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://soneium.blockscout.com/",
		chainColor:             "#000000",
		shortName:              "soneium",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 false,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.SoneiumMinato,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.SoneiumMinato,
		proxyChainName:   "soneium",
		proxyNetworkName: "minato",
		chainName:        "Soneium Minato",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			// no support for soneium on infura
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://rpc.minato.soneium.org/"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://soneium-minato.blockscout.com/",
		chainColor:             "#000000",
		shortName:              "soneium",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 true,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.SoneiumMainnet,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.ScrollMainnet,
		proxyChainName:   "scroll",
		proxyNetworkName: "mainnet",
		chainName:        "Scroll",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://scroll-mainnet.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://rpc.scroll.io"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://scrollscan.com/",
		chainColor:             "#101010",
		shortName:              "scroll",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 false,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.ScrollSepolia,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.ScrollSepolia,
		proxyChainName:   "scroll",
		proxyNetworkName: "sepolia",
		chainName:        "Scroll Sepolia",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://scroll-sepolia.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://sepolia-rpc.scroll.io"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://sepolia.scrollscan.com/",
		chainColor:             "#101010",
		shortName:              "scroll",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 true,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.ScrollMainnet,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.BlastMainnet,
		proxyChainName:   "blast",
		proxyNetworkName: "mainnet",
		chainName:        "Blast",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://blast-mainnet.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://rpc.blast.io"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://blastscan.io/",
		chainColor:             "#FCFC03",
		shortName:              "blast",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 false,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.BlastSepolia,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.BlastSepolia,
		proxyChainName:   "blast",
		proxyNetworkName: "sepolia",
		chainName:        "Blast Sepolia",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeProxy, name: common.ProxyInfura, targetProvider: common.Infura},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://blast-sepolia.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectCustom, directURL: security.NewSensitiveString("https://sepolia.blast.io"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://sepolia.blastscan.io/",
		chainColor:             "#FCFC03",
		shortName:              "blast",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 true,
		layer:                  2,
		enabled:                false,
		relatedChainID:         common.BlastMainnet,
		isActive:               false,
		isDeactivatable:        true,
	},
	{
		chainID:          common.StatusNetworkHoodi,
		proxyChainName:   "status",
		proxyNetworkName: "hoodi",
		chainName:        "Status Network Hoodi",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeDirect, name: common.DirectStatus, directURL: security.NewSensitiveString("https://public.hoodi.rpc.status.network")},
		},
		blockExplorerURL:       "https://hoodiscan.status.network/",
		chainColor:             "#7140FD",
		shortName:              "status",
		nativeCurrencyName:     "Ether",
		nativeCurrencySymbol:   "ETH",
		nativeCurrencyDecimals: 18,
		isTest:                 true,
		layer:                  2,
		enabled:                true,
		relatedChainID:         0, // TODO: update related chain id once decided
		isActive:               true,
		isDeactivatable:        true,
	},
	{
		chainID:          common.BSCMainnet,
		proxyChainName:   "bsc",
		proxyNetworkName: "mainnet",
		chainName:        "Binance",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://bsc-mainnet.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeDirect, name: common.DirectGrove, directURL: security.NewSensitiveString("https://bsc.rpc.grove.city/v1/")},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://bscscan.com/",
		chainColor:             "#f7bb0f",
		shortName:              "bsc",
		nativeCurrencyName:     "BNB",
		nativeCurrencySymbol:   "BNB",
		nativeCurrencyDecimals: 18,
		isTest:                 false,
		layer:                  1,
		enabled:                true,
		relatedChainID:         common.BSCTestnet,
		isActive:               true,
		isDeactivatable:        true,
	},
	{
		chainID:          common.BSCTestnet,
		proxyChainName:   "bsc",
		proxyNetworkName: "testnet",
		chainName:        "Binance Testnet",
		providers: []providerSpec{
			{providerType: providerTypeEthRpcProxy, name: common.StatusSmartProxy},
			{providerType: providerTypeDirect, name: common.DirectInfura, directURL: security.NewSensitiveString("https://bsc-testnet.infura.io/v3/"), enableRpsLimiter: true},
			{providerType: providerTypeEthRpcProxyWithProvider, name: common.SmartProxyAlchemy, targetProvider: common.Alchemy},
		},
		blockExplorerURL:       "https://testnet.bscscan.com/",
		chainColor:             "#f7bb0f",
		shortName:              "bsc",
		nativeCurrencyName:     "BNB",
		nativeCurrencySymbol:   "BNB",
		nativeCurrencyDecimals: 18,
		isTest:                 true,
		layer:                  1,
		enabled:                true,
		relatedChainID:         common.BSCMainnet,
		isActive:               false,
		isDeactivatable:        true,
	},
}
