version: "3"
services:
  mailserver:
    container_name: '${CONTAINER_NAME}'
    image: '${CONTAINER_IMG}:${CONTAINER_TAG}'
    entrypoint: statusd
    restart: always
    command: |
        -log=${LOG_LEVEL}
        -log-without-color
        -metrics
        -metrics-port=${METRICS_PORT}
        -c=/config.json
        -dir=/data
    ports:
      - '127.0.0.1:${RPC_PORT}:${RPC_PORT}'
      - '127.0.0.1:${METRICS_PORT}:${METRICS_PORT}'
      - '0.0.0.0:${LISTEN_PORT}:${LISTEN_PORT}/tcp'
      - '0.0.0.0:${LISTEN_PORT}:${LISTEN_PORT}/udp'
    volumes:
      - '${DATA_PATH}/config.json:/config.json'
      - '${DATA_PATH}:/data'
