// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat_message.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AudioMessage_AudioType int32

const (
	AudioMessage_UNKNOWN_AUDIO_TYPE AudioMessage_AudioType = 0
	AudioMessage_AAC                AudioMessage_AudioType = 1
	AudioMessage_AMR                AudioMessage_AudioType = 2
)

var AudioMessage_AudioType_name = map[int32]string{
	0: "UNKNOWN_AUDIO_TYPE",
	1: "AAC",
	2: "AMR",
}

var AudioMessage_AudioType_value = map[string]int32{
	"UNKNOWN_AUDIO_TYPE": 0,
	"AAC":                1,
	"AMR":                2,
}

func (x AudioMessage_AudioType) String() string {
	return proto.EnumName(AudioMessage_AudioType_name, int32(x))
}

func (AudioMessage_AudioType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_263952f55fd35689, []int{2, 0}
}

type ChatMessage_ContentType int32

const (
	ChatMessage_UNKNOWN_CONTENT_TYPE ChatMessage_ContentType = 0
	ChatMessage_TEXT_PLAIN           ChatMessage_ContentType = 1
	ChatMessage_STICKER              ChatMessage_ContentType = 2
	ChatMessage_STATUS               ChatMessage_ContentType = 3
	ChatMessage_EMOJI                ChatMessage_ContentType = 4
	ChatMessage_TRANSACTION_COMMAND  ChatMessage_ContentType = 5
	// Only local
	ChatMessage_SYSTEM_MESSAGE_CONTENT_PRIVATE_GROUP ChatMessage_ContentType = 6
	ChatMessage_IMAGE                                ChatMessage_ContentType = 7
	ChatMessage_AUDIO                                ChatMessage_ContentType = 8
	ChatMessage_COMMUNITY                            ChatMessage_ContentType = 9
	// Only local
	ChatMessage_SYSTEM_MESSAGE_GAP ChatMessage_ContentType = 10
	ChatMessage_CONTACT_REQUEST    ChatMessage_ContentType = 11
	ChatMessage_DISCORD_MESSAGE    ChatMessage_ContentType = 12
)

var ChatMessage_ContentType_name = map[int32]string{
	0:  "UNKNOWN_CONTENT_TYPE",
	1:  "TEXT_PLAIN",
	2:  "STICKER",
	3:  "STATUS",
	4:  "EMOJI",
	5:  "TRANSACTION_COMMAND",
	6:  "SYSTEM_MESSAGE_CONTENT_PRIVATE_GROUP",
	7:  "IMAGE",
	8:  "AUDIO",
	9:  "COMMUNITY",
	10: "SYSTEM_MESSAGE_GAP",
	11: "CONTACT_REQUEST",
	12: "DISCORD_MESSAGE",
}

var ChatMessage_ContentType_value = map[string]int32{
	"UNKNOWN_CONTENT_TYPE":                 0,
	"TEXT_PLAIN":                           1,
	"STICKER":                              2,
	"STATUS":                               3,
	"EMOJI":                                4,
	"TRANSACTION_COMMAND":                  5,
	"SYSTEM_MESSAGE_CONTENT_PRIVATE_GROUP": 6,
	"IMAGE":                                7,
	"AUDIO":                                8,
	"COMMUNITY":                            9,
	"SYSTEM_MESSAGE_GAP":                   10,
	"CONTACT_REQUEST":                      11,
	"DISCORD_MESSAGE":                      12,
}

func (x ChatMessage_ContentType) String() string {
	return proto.EnumName(ChatMessage_ContentType_name, int32(x))
}

func (ChatMessage_ContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_263952f55fd35689, []int{8, 0}
}

type StickerMessage struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Pack                 int32    `protobuf:"varint,2,opt,name=pack,proto3" json:"pack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StickerMessage) Reset()         { *m = StickerMessage{} }
func (m *StickerMessage) String() string { return proto.CompactTextString(m) }
func (*StickerMessage) ProtoMessage()    {}
func (*StickerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_263952f55fd35689, []int{0}
}

func (m *StickerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StickerMessage.Unmarshal(m, b)
}
func (m *StickerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StickerMessage.Marshal(b, m, deterministic)
}
func (m *StickerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StickerMessage.Merge(m, src)
}
func (m *StickerMessage) XXX_Size() int {
	return xxx_messageInfo_StickerMessage.Size(m)
}
func (m *StickerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StickerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StickerMessage proto.InternalMessageInfo

func (m *StickerMessage) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *StickerMessage) GetPack() int32 {
	if m != nil {
		return m.Pack
	}
	return 0
}

type ImageMessage struct {
	Payload              []byte    `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Type                 ImageType `protobuf:"varint,2,opt,name=type,proto3,enum=protobuf.ImageType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ImageMessage) Reset()         { *m = ImageMessage{} }
func (m *ImageMessage) String() string { return proto.CompactTextString(m) }
func (*ImageMessage) ProtoMessage()    {}
func (*ImageMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_263952f55fd35689, []int{1}
}

func (m *ImageMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageMessage.Unmarshal(m, b)
}
func (m *ImageMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageMessage.Marshal(b, m, deterministic)
}
func (m *ImageMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageMessage.Merge(m, src)
}
func (m *ImageMessage) XXX_Size() int {
	return xxx_messageInfo_ImageMessage.Size(m)
}
func (m *ImageMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ImageMessage proto.InternalMessageInfo

func (m *ImageMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ImageMessage) GetType() ImageType {
	if m != nil {
		return m.Type
	}
	return ImageType_UNKNOWN_IMAGE_TYPE
}

type AudioMessage struct {
	Payload              []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Type                 AudioMessage_AudioType `protobuf:"varint,2,opt,name=type,proto3,enum=protobuf.AudioMessage_AudioType" json:"type,omitempty"`
	DurationMs           uint64                 `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AudioMessage) Reset()         { *m = AudioMessage{} }
func (m *AudioMessage) String() string { return proto.CompactTextString(m) }
func (*AudioMessage) ProtoMessage()    {}
func (*AudioMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_263952f55fd35689, []int{2}
}

func (m *AudioMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioMessage.Unmarshal(m, b)
}
func (m *AudioMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioMessage.Marshal(b, m, deterministic)
}
func (m *AudioMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioMessage.Merge(m, src)
}
func (m *AudioMessage) XXX_Size() int {
	return xxx_messageInfo_AudioMessage.Size(m)
}
func (m *AudioMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AudioMessage proto.InternalMessageInfo

func (m *AudioMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *AudioMessage) GetType() AudioMessage_AudioType {
	if m != nil {
		return m.Type
	}
	return AudioMessage_UNKNOWN_AUDIO_TYPE
}

func (m *AudioMessage) GetDurationMs() uint64 {
	if m != nil {
		return m.DurationMs
	}
	return 0
}

type EditMessage struct {
	Clock uint64 `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	// Text of the message
	Text      string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	ChatId    string `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MessageId string `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Grant for community edit messages
	Grant []byte `protobuf:"bytes,5,opt,name=grant,proto3" json:"grant,omitempty"`
	// The type of message (public/one-to-one/private-group-chat)
	MessageType          MessageType `protobuf:"varint,6,opt,name=message_type,json=messageType,proto3,enum=protobuf.MessageType" json:"message_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EditMessage) Reset()         { *m = EditMessage{} }
func (m *EditMessage) String() string { return proto.CompactTextString(m) }
func (*EditMessage) ProtoMessage()    {}
func (*EditMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_263952f55fd35689, []int{3}
}

func (m *EditMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditMessage.Unmarshal(m, b)
}
func (m *EditMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditMessage.Marshal(b, m, deterministic)
}
func (m *EditMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditMessage.Merge(m, src)
}
func (m *EditMessage) XXX_Size() int {
	return xxx_messageInfo_EditMessage.Size(m)
}
func (m *EditMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EditMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EditMessage proto.InternalMessageInfo

func (m *EditMessage) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *EditMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *EditMessage) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *EditMessage) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *EditMessage) GetGrant() []byte {
	if m != nil {
		return m.Grant
	}
	return nil
}

func (m *EditMessage) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

type DeleteMessage struct {
	Clock     uint64 `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	ChatId    string `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MessageId string `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Grant for community delete messages
	Grant []byte `protobuf:"bytes,4,opt,name=grant,proto3" json:"grant,omitempty"`
	// The type of message (public/one-to-one/private-group-chat)
	MessageType          MessageType `protobuf:"varint,5,opt,name=message_type,json=messageType,proto3,enum=protobuf.MessageType" json:"message_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DeleteMessage) Reset()         { *m = DeleteMessage{} }
func (m *DeleteMessage) String() string { return proto.CompactTextString(m) }
func (*DeleteMessage) ProtoMessage()    {}
func (*DeleteMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_263952f55fd35689, []int{4}
}

func (m *DeleteMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMessage.Unmarshal(m, b)
}
func (m *DeleteMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMessage.Marshal(b, m, deterministic)
}
func (m *DeleteMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMessage.Merge(m, src)
}
func (m *DeleteMessage) XXX_Size() int {
	return xxx_messageInfo_DeleteMessage.Size(m)
}
func (m *DeleteMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMessage proto.InternalMessageInfo

func (m *DeleteMessage) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *DeleteMessage) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *DeleteMessage) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *DeleteMessage) GetGrant() []byte {
	if m != nil {
		return m.Grant
	}
	return nil
}

func (m *DeleteMessage) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

type DiscordMessage struct {
	Id                   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string                   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp            string                   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TimestampEdited      string                   `protobuf:"bytes,4,opt,name=timestampEdited,proto3" json:"timestampEdited,omitempty"`
	Content              string                   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Author               *DiscordMessageAuthor    `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	Reference            *DiscordMessageReference `protobuf:"bytes,7,opt,name=reference,proto3" json:"reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DiscordMessage) Reset()         { *m = DiscordMessage{} }
func (m *DiscordMessage) String() string { return proto.CompactTextString(m) }
func (*DiscordMessage) ProtoMessage()    {}
func (*DiscordMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_263952f55fd35689, []int{5}
}

func (m *DiscordMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscordMessage.Unmarshal(m, b)
}
func (m *DiscordMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscordMessage.Marshal(b, m, deterministic)
}
func (m *DiscordMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscordMessage.Merge(m, src)
}
func (m *DiscordMessage) XXX_Size() int {
	return xxx_messageInfo_DiscordMessage.Size(m)
}
func (m *DiscordMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscordMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DiscordMessage proto.InternalMessageInfo

func (m *DiscordMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DiscordMessage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DiscordMessage) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *DiscordMessage) GetTimestampEdited() string {
	if m != nil {
		return m.TimestampEdited
	}
	return ""
}

func (m *DiscordMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *DiscordMessage) GetAuthor() *DiscordMessageAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *DiscordMessage) GetReference() *DiscordMessageReference {
	if m != nil {
		return m.Reference
	}
	return nil
}

type DiscordMessageAuthor struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Discriminator        string   `protobuf:"bytes,3,opt,name=discriminator,proto3" json:"discriminator,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,5,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscordMessageAuthor) Reset()         { *m = DiscordMessageAuthor{} }
func (m *DiscordMessageAuthor) String() string { return proto.CompactTextString(m) }
func (*DiscordMessageAuthor) ProtoMessage()    {}
func (*DiscordMessageAuthor) Descriptor() ([]byte, []int) {
	return fileDescriptor_263952f55fd35689, []int{6}
}

func (m *DiscordMessageAuthor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscordMessageAuthor.Unmarshal(m, b)
}
func (m *DiscordMessageAuthor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscordMessageAuthor.Marshal(b, m, deterministic)
}
func (m *DiscordMessageAuthor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscordMessageAuthor.Merge(m, src)
}
func (m *DiscordMessageAuthor) XXX_Size() int {
	return xxx_messageInfo_DiscordMessageAuthor.Size(m)
}
func (m *DiscordMessageAuthor) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscordMessageAuthor.DiscardUnknown(m)
}

var xxx_messageInfo_DiscordMessageAuthor proto.InternalMessageInfo

func (m *DiscordMessageAuthor) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DiscordMessageAuthor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DiscordMessageAuthor) GetDiscriminator() string {
	if m != nil {
		return m.Discriminator
	}
	return ""
}

func (m *DiscordMessageAuthor) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *DiscordMessageAuthor) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

type DiscordMessageReference struct {
	MessageId            string   `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	ChannelId            string   `protobuf:"bytes,2,opt,name=channelId,proto3" json:"channelId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscordMessageReference) Reset()         { *m = DiscordMessageReference{} }
func (m *DiscordMessageReference) String() string { return proto.CompactTextString(m) }
func (*DiscordMessageReference) ProtoMessage()    {}
func (*DiscordMessageReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_263952f55fd35689, []int{7}
}

func (m *DiscordMessageReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscordMessageReference.Unmarshal(m, b)
}
func (m *DiscordMessageReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscordMessageReference.Marshal(b, m, deterministic)
}
func (m *DiscordMessageReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscordMessageReference.Merge(m, src)
}
func (m *DiscordMessageReference) XXX_Size() int {
	return xxx_messageInfo_DiscordMessageReference.Size(m)
}
func (m *DiscordMessageReference) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscordMessageReference.DiscardUnknown(m)
}

var xxx_messageInfo_DiscordMessageReference proto.InternalMessageInfo

func (m *DiscordMessageReference) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *DiscordMessageReference) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type ChatMessage struct {
	// Lamport timestamp of the chat message
	Clock uint64 `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	// Unix timestamps in milliseconds, currently not used as we use whisper as more reliable, but here
	// so that we don't rely on it
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Text of the message
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// Id of the message that we are replying to
	ResponseTo string `protobuf:"bytes,4,opt,name=response_to,json=responseTo,proto3" json:"response_to,omitempty"`
	// Ens name of the sender
	EnsName string `protobuf:"bytes,5,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	// Chat id, this field is symmetric for public-chats and private group chats,
	// but asymmetric in case of one-to-ones, as the sender will use the chat-id
	// of the received, while the receiver will use the chat-id of the sender.
	// Probably should be the concatenation of sender-pk & receiver-pk in alphabetical order
	ChatId string `protobuf:"bytes,6,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// The type of message (public/one-to-one/private-group-chat)
	MessageType MessageType `protobuf:"varint,7,opt,name=message_type,json=messageType,proto3,enum=protobuf.MessageType" json:"message_type,omitempty"`
	// The type of the content of the message
	ContentType ChatMessage_ContentType `protobuf:"varint,8,opt,name=content_type,json=contentType,proto3,enum=protobuf.ChatMessage_ContentType" json:"content_type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*ChatMessage_Sticker
	//	*ChatMessage_Image
	//	*ChatMessage_Audio
	//	*ChatMessage_Community
	//	*ChatMessage_DiscordMessage
	Payload isChatMessage_Payload `protobuf_oneof:"payload"`
	// Grant for community chat messages
	Grant []byte `protobuf:"bytes,13,opt,name=grant,proto3" json:"grant,omitempty"`
	// Message author's display name, introduced in version 1
	DisplayName                     string                   `protobuf:"bytes,14,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	SentContactRequestSignature     *ContactRequestSignature `protobuf:"bytes,15,opt,name=sent_contact_request_signature,json=sentContactRequestSignature,proto3" json:"sent_contact_request_signature,omitempty"`
	ReceivedContactRequestSignature *ContactRequestSignature `protobuf:"bytes,16,opt,name=received_contact_request_signature,json=receivedContactRequestSignature,proto3" json:"received_contact_request_signature,omitempty"`
	ContactMessage                  bool                     `protobuf:"varint,17,opt,name=contact_message,json=contactMessage,proto3" json:"contact_message,omitempty"`
	XXX_NoUnkeyedLiteral            struct{}                 `json:"-"`
	XXX_unrecognized                []byte                   `json:"-"`
	XXX_sizecache                   int32                    `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_263952f55fd35689, []int{8}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *ChatMessage) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ChatMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *ChatMessage) GetResponseTo() string {
	if m != nil {
		return m.ResponseTo
	}
	return ""
}

func (m *ChatMessage) GetEnsName() string {
	if m != nil {
		return m.EnsName
	}
	return ""
}

func (m *ChatMessage) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *ChatMessage) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *ChatMessage) GetContentType() ChatMessage_ContentType {
	if m != nil {
		return m.ContentType
	}
	return ChatMessage_UNKNOWN_CONTENT_TYPE
}

type isChatMessage_Payload interface {
	isChatMessage_Payload()
}

type ChatMessage_Sticker struct {
	Sticker *StickerMessage `protobuf:"bytes,9,opt,name=sticker,proto3,oneof"`
}

type ChatMessage_Image struct {
	Image *ImageMessage `protobuf:"bytes,10,opt,name=image,proto3,oneof"`
}

type ChatMessage_Audio struct {
	Audio *AudioMessage `protobuf:"bytes,11,opt,name=audio,proto3,oneof"`
}

type ChatMessage_Community struct {
	Community []byte `protobuf:"bytes,12,opt,name=community,proto3,oneof"`
}

type ChatMessage_DiscordMessage struct {
	DiscordMessage *DiscordMessage `protobuf:"bytes,99,opt,name=discord_message,json=discordMessage,proto3,oneof"`
}

func (*ChatMessage_Sticker) isChatMessage_Payload() {}

func (*ChatMessage_Image) isChatMessage_Payload() {}

func (*ChatMessage_Audio) isChatMessage_Payload() {}

func (*ChatMessage_Community) isChatMessage_Payload() {}

func (*ChatMessage_DiscordMessage) isChatMessage_Payload() {}

func (m *ChatMessage) GetPayload() isChatMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ChatMessage) GetSticker() *StickerMessage {
	if x, ok := m.GetPayload().(*ChatMessage_Sticker); ok {
		return x.Sticker
	}
	return nil
}

func (m *ChatMessage) GetImage() *ImageMessage {
	if x, ok := m.GetPayload().(*ChatMessage_Image); ok {
		return x.Image
	}
	return nil
}

func (m *ChatMessage) GetAudio() *AudioMessage {
	if x, ok := m.GetPayload().(*ChatMessage_Audio); ok {
		return x.Audio
	}
	return nil
}

func (m *ChatMessage) GetCommunity() []byte {
	if x, ok := m.GetPayload().(*ChatMessage_Community); ok {
		return x.Community
	}
	return nil
}

func (m *ChatMessage) GetDiscordMessage() *DiscordMessage {
	if x, ok := m.GetPayload().(*ChatMessage_DiscordMessage); ok {
		return x.DiscordMessage
	}
	return nil
}

func (m *ChatMessage) GetGrant() []byte {
	if m != nil {
		return m.Grant
	}
	return nil
}

func (m *ChatMessage) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ChatMessage) GetSentContactRequestSignature() *ContactRequestSignature {
	if m != nil {
		return m.SentContactRequestSignature
	}
	return nil
}

func (m *ChatMessage) GetReceivedContactRequestSignature() *ContactRequestSignature {
	if m != nil {
		return m.ReceivedContactRequestSignature
	}
	return nil
}

func (m *ChatMessage) GetContactMessage() bool {
	if m != nil {
		return m.ContactMessage
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ChatMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ChatMessage_Sticker)(nil),
		(*ChatMessage_Image)(nil),
		(*ChatMessage_Audio)(nil),
		(*ChatMessage_Community)(nil),
		(*ChatMessage_DiscordMessage)(nil),
	}
}

type ContactRequestSignature struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp            uint64   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactRequestSignature) Reset()         { *m = ContactRequestSignature{} }
func (m *ContactRequestSignature) String() string { return proto.CompactTextString(m) }
func (*ContactRequestSignature) ProtoMessage()    {}
func (*ContactRequestSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_263952f55fd35689, []int{9}
}

func (m *ContactRequestSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactRequestSignature.Unmarshal(m, b)
}
func (m *ContactRequestSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactRequestSignature.Marshal(b, m, deterministic)
}
func (m *ContactRequestSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactRequestSignature.Merge(m, src)
}
func (m *ContactRequestSignature) XXX_Size() int {
	return xxx_messageInfo_ContactRequestSignature.Size(m)
}
func (m *ContactRequestSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactRequestSignature.DiscardUnknown(m)
}

var xxx_messageInfo_ContactRequestSignature proto.InternalMessageInfo

func (m *ContactRequestSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ContactRequestSignature) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("protobuf.AudioMessage_AudioType", AudioMessage_AudioType_name, AudioMessage_AudioType_value)
	proto.RegisterEnum("protobuf.ChatMessage_ContentType", ChatMessage_ContentType_name, ChatMessage_ContentType_value)
	proto.RegisterType((*StickerMessage)(nil), "protobuf.StickerMessage")
	proto.RegisterType((*ImageMessage)(nil), "protobuf.ImageMessage")
	proto.RegisterType((*AudioMessage)(nil), "protobuf.AudioMessage")
	proto.RegisterType((*EditMessage)(nil), "protobuf.EditMessage")
	proto.RegisterType((*DeleteMessage)(nil), "protobuf.DeleteMessage")
	proto.RegisterType((*DiscordMessage)(nil), "protobuf.DiscordMessage")
	proto.RegisterType((*DiscordMessageAuthor)(nil), "protobuf.DiscordMessageAuthor")
	proto.RegisterType((*DiscordMessageReference)(nil), "protobuf.DiscordMessageReference")
	proto.RegisterType((*ChatMessage)(nil), "protobuf.ChatMessage")
	proto.RegisterType((*ContactRequestSignature)(nil), "protobuf.ContactRequestSignature")
}

func init() { proto.RegisterFile("chat_message.proto", fileDescriptor_263952f55fd35689) }

var fileDescriptor_263952f55fd35689 = []byte{
	// 1064 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xcf, 0x6e, 0xdb, 0xc6,
	0x13, 0x36, 0x65, 0xfd, 0xe3, 0x50, 0x96, 0xf9, 0x5b, 0xfb, 0x17, 0xb3, 0xa9, 0x6b, 0x3b, 0x44,
	0x80, 0xe8, 0xa4, 0x02, 0x69, 0x5a, 0x04, 0xe8, 0xa1, 0x60, 0x24, 0xc2, 0x66, 0x53, 0x49, 0xce,
	0x92, 0x6a, 0xeb, 0x5e, 0x88, 0x0d, 0xb9, 0xb6, 0x08, 0x8b, 0xa4, 0x4a, 0x52, 0x41, 0xfd, 0x00,
	0x3d, 0xf7, 0xde, 0x77, 0xe8, 0xb5, 0xd7, 0xbe, 0x53, 0x9f, 0xa0, 0xd8, 0x25, 0x57, 0xa4, 0x84,
	0x48, 0xf1, 0x49, 0x3b, 0xc3, 0x99, 0xd9, 0x6f, 0xbf, 0xf9, 0x76, 0x56, 0x80, 0xbc, 0x19, 0xc9,
	0xdc, 0x90, 0xa6, 0x29, 0xb9, 0xa3, 0xfd, 0x45, 0x12, 0x67, 0x31, 0x6a, 0xf3, 0x9f, 0xf7, 0xcb,
	0xdb, 0xa7, 0x0a, 0x8d, 0x96, 0x61, 0x9a, 0xbb, 0xf5, 0xd7, 0xd0, 0xb5, 0xb3, 0xc0, 0xbb, 0xa7,
	0xc9, 0x28, 0x0f, 0x47, 0x08, 0xea, 0x33, 0x92, 0xce, 0x34, 0xe9, 0x42, 0xea, 0xc9, 0x98, 0xaf,
	0x99, 0x6f, 0x41, 0xbc, 0x7b, 0xad, 0x76, 0x21, 0xf5, 0x1a, 0x98, 0xaf, 0xf5, 0x77, 0xd0, 0xb1,
	0x42, 0x72, 0x47, 0x45, 0x9e, 0x06, 0xad, 0x05, 0x79, 0x98, 0xc7, 0xc4, 0xe7, 0xa9, 0x1d, 0x2c,
	0x4c, 0xf4, 0x02, 0xea, 0xd9, 0xc3, 0x82, 0xf2, 0xec, 0xee, 0xcb, 0xa3, 0xbe, 0x40, 0xd2, 0xe7,
	0xf9, 0xce, 0xc3, 0x82, 0x62, 0x1e, 0xa0, 0xff, 0x2d, 0x41, 0xc7, 0x58, 0xfa, 0x41, 0xfc, 0xe9,
	0x9a, 0xaf, 0xd6, 0x6a, 0x5e, 0x94, 0x35, 0xab, 0xf9, 0xb9, 0x51, 0x6e, 0x80, 0xce, 0x41, 0xf1,
	0x97, 0x09, 0xc9, 0x82, 0x38, 0x72, 0xc3, 0x54, 0xdb, 0xbf, 0x90, 0x7a, 0x75, 0x0c, 0xc2, 0x35,
	0x4a, 0xf5, 0xaf, 0x41, 0x5e, 0xe5, 0xa0, 0x27, 0x80, 0xa6, 0xe3, 0xb7, 0xe3, 0xc9, 0x4f, 0x63,
	0xd7, 0x98, 0x0e, 0xad, 0x89, 0xeb, 0xdc, 0x5c, 0x9b, 0xea, 0x1e, 0x6a, 0xc1, 0xbe, 0x61, 0x0c,
	0x54, 0x89, 0x2f, 0x46, 0x58, 0xad, 0xe9, 0xff, 0x48, 0xa0, 0x98, 0x7e, 0x90, 0x09, 0xdc, 0xc7,
	0xd0, 0xf0, 0xe6, 0xb1, 0x77, 0xcf, 0x51, 0xd7, 0x71, 0x6e, 0x30, 0x16, 0x33, 0xfa, 0x5b, 0xc6,
	0x31, 0xcb, 0x98, 0xaf, 0xd1, 0x09, 0xb4, 0x78, 0xb3, 0x02, 0x9f, 0xa3, 0x91, 0x71, 0x93, 0x99,
	0x96, 0x8f, 0xbe, 0x00, 0x28, 0x1a, 0xc8, 0xbe, 0xd5, 0xf9, 0x37, 0xb9, 0xf0, 0x58, 0x3e, 0xdb,
	0xe1, 0x2e, 0x21, 0x51, 0xa6, 0x35, 0x38, 0x2f, 0xb9, 0x81, 0x5e, 0x43, 0x47, 0x24, 0x71, 0x76,
	0x9a, 0x9c, 0x9d, 0xff, 0x97, 0xec, 0x14, 0x00, 0x39, 0x25, 0x4a, 0x58, 0x1a, 0xfa, 0x5f, 0x12,
	0x1c, 0x0c, 0xe9, 0x9c, 0x66, 0x74, 0xf7, 0x19, 0x2a, 0x78, 0x6b, 0x3b, 0xf0, 0xee, 0x6f, 0xc5,
	0x5b, 0xdf, 0x85, 0xb7, 0xf1, 0x68, 0xbc, 0x7f, 0xd4, 0xa0, 0x3b, 0x0c, 0x52, 0x2f, 0x4e, 0x7c,
	0x01, 0xb8, 0x0b, 0xb5, 0xc0, 0x2f, 0x64, 0x5b, 0x0b, 0x7c, 0x4e, 0xb7, 0x90, 0x88, 0x5c, 0x08,
	0xe0, 0x14, 0xe4, 0x2c, 0x08, 0x69, 0x9a, 0x91, 0x70, 0x21, 0x40, 0xae, 0x1c, 0xa8, 0x07, 0x87,
	0x2b, 0x83, 0xb5, 0x93, 0x0a, 0xe2, 0x37, 0xdd, 0x4c, 0x98, 0x5e, 0x1c, 0x65, 0xb4, 0x68, 0x80,
	0x8c, 0x85, 0x89, 0xbe, 0x81, 0x26, 0x59, 0x66, 0xb3, 0x38, 0xe1, 0xe4, 0x2b, 0x2f, 0xcf, 0xca,
	0xc3, 0xac, 0xe3, 0x35, 0x78, 0x14, 0x2e, 0xa2, 0xd1, 0x77, 0x20, 0x27, 0xf4, 0x96, 0x26, 0x34,
	0xf2, 0xa8, 0xd6, 0xe2, 0xa9, 0xcf, 0xb6, 0xa5, 0x62, 0x11, 0x88, 0xcb, 0x1c, 0xfd, 0x4f, 0x09,
	0x8e, 0x3f, 0xb6, 0xc3, 0xc7, 0x78, 0x89, 0x48, 0xb8, 0xe2, 0x85, 0xad, 0xd1, 0x73, 0x38, 0xf0,
	0x83, 0xd4, 0x4b, 0x82, 0x30, 0x88, 0x48, 0x16, 0x27, 0x05, 0x37, 0xeb, 0x4e, 0xf4, 0x14, 0xda,
	0x51, 0xe0, 0xdd, 0xf3, 0xec, 0x9c, 0x98, 0x95, 0xcd, 0x98, 0x25, 0x1f, 0x48, 0x46, 0x92, 0x69,
	0x32, 0x2f, 0x38, 0x29, 0x1d, 0xfa, 0x14, 0x4e, 0xb6, 0x1c, 0x81, 0x25, 0xae, 0x64, 0x52, 0xa0,
	0xac, 0xe8, 0xe6, 0x14, 0x64, 0x6f, 0x46, 0xa2, 0x88, 0xce, 0x2d, 0xa1, 0xb8, 0xd2, 0xa1, 0xff,
	0xdb, 0x06, 0x65, 0x30, 0x23, 0x9f, 0xb8, 0x77, 0x6b, 0x4d, 0xaf, 0xf1, 0x2f, 0x95, 0xa6, 0x8b,
	0x5b, 0xb9, 0x5f, 0xb9, 0x95, 0xe7, 0xa0, 0x24, 0x34, 0x5d, 0xc4, 0x51, 0x4a, 0xdd, 0x2c, 0x2e,
	0xce, 0x0a, 0xc2, 0xe5, 0xc4, 0xe8, 0x33, 0x68, 0xd3, 0x28, 0x75, 0x39, 0x13, 0x85, 0x00, 0x68,
	0x94, 0x8e, 0x19, 0x11, 0x95, 0x1b, 0xd2, 0x5c, 0xbb, 0x21, 0x9b, 0x62, 0x6f, 0x3d, 0x56, 0xec,
	0x68, 0x08, 0x9d, 0x42, 0x5e, 0x79, 0x66, 0x9b, 0x67, 0x56, 0xe4, 0x51, 0xe1, 0xa0, 0x3f, 0xc8,
	0x23, 0xf3, 0x2a, 0x5e, 0x69, 0xa0, 0x57, 0xd0, 0x4a, 0xf3, 0x51, 0xaf, 0xc9, 0x5c, 0x5f, 0x5a,
	0x59, 0x60, 0xfd, 0x0d, 0xb8, 0xda, 0xc3, 0x22, 0x14, 0xf5, 0xa1, 0x11, 0xb0, 0x31, 0xad, 0x01,
	0xcf, 0x79, 0xb2, 0x31, 0xbd, 0xcb, 0x8c, 0x3c, 0x8c, 0xc5, 0x13, 0x36, 0x41, 0x35, 0x65, 0x33,
	0xbe, 0x3a, 0x99, 0x59, 0x3c, 0x0f, 0x43, 0x67, 0x20, 0x7b, 0x71, 0x18, 0x2e, 0xa3, 0x20, 0x7b,
	0xd0, 0x3a, 0x6c, 0x38, 0x5c, 0xed, 0xe1, 0xd2, 0x85, 0x06, 0x70, 0xe8, 0xe7, 0xca, 0x11, 0x0f,
	0x9a, 0xe6, 0x6d, 0xa2, 0x5f, 0x97, 0xd6, 0xd5, 0x1e, 0xee, 0xfa, 0xeb, 0xa3, 0x61, 0x35, 0x7d,
	0x0e, 0xaa, 0xd3, 0xe7, 0x19, 0x74, 0xfc, 0x20, 0x5d, 0xcc, 0xc9, 0x43, 0xde, 0xc8, 0x2e, 0x6f,
	0x97, 0x52, 0xf8, 0x78, 0x33, 0x6f, 0xe1, 0x2c, 0x65, 0xb4, 0x33, 0x1e, 0x89, 0x97, 0xb9, 0x09,
	0xfd, 0x75, 0x49, 0xd3, 0xcc, 0x4d, 0x83, 0xbb, 0x88, 0x64, 0xcb, 0x84, 0x6a, 0x87, 0x9b, 0x57,
	0x75, 0x90, 0x87, 0xe2, 0x3c, 0xd2, 0x16, 0x81, 0xf8, 0x73, 0x56, 0x68, 0xcb, 0x47, 0x14, 0x81,
	0x9e, 0x50, 0x8f, 0x06, 0x1f, 0xa8, 0xbf, 0x63, 0x2f, 0xf5, 0xb1, 0x7b, 0x9d, 0x8b, 0x62, 0xdb,
	0xf6, 0x7b, 0x01, 0x87, 0x62, 0x1b, 0xc1, 0xea, 0xff, 0x2e, 0xa4, 0x5e, 0x1b, 0x77, 0x0b, 0x77,
	0xc1, 0x9c, 0xfe, 0x7b, 0x0d, 0x94, 0x8a, 0xa2, 0x90, 0x06, 0xc7, 0xe2, 0x4d, 0x1c, 0x4c, 0xc6,
	0x8e, 0x39, 0x76, 0xc4, 0xab, 0xd8, 0x05, 0x70, 0xcc, 0x9f, 0x1d, 0xf7, 0xfa, 0x07, 0xc3, 0x1a,
	0xab, 0x12, 0x52, 0xa0, 0x65, 0x3b, 0xd6, 0xe0, 0xad, 0x89, 0xd5, 0x1a, 0x02, 0x68, 0xda, 0x8e,
	0xe1, 0x4c, 0x6d, 0x75, 0x1f, 0xc9, 0xd0, 0x30, 0x47, 0x93, 0xef, 0x2d, 0xb5, 0x8e, 0x4e, 0xe0,
	0xc8, 0xc1, 0xc6, 0xd8, 0x36, 0x06, 0x8e, 0x35, 0x61, 0x15, 0x47, 0x23, 0x63, 0x3c, 0x54, 0x1b,
	0xa8, 0x07, 0xcf, 0xed, 0x1b, 0xdb, 0x31, 0x47, 0xee, 0xc8, 0xb4, 0x6d, 0xe3, 0xd2, 0x5c, 0xed,
	0x76, 0x8d, 0xad, 0x1f, 0x0d, 0xc7, 0x74, 0x2f, 0xf1, 0x64, 0x7a, 0xad, 0x36, 0x59, 0x35, 0x6b,
	0x64, 0x5c, 0x9a, 0x6a, 0x8b, 0x2d, 0xf9, 0x3b, 0xad, 0xb6, 0xd1, 0x01, 0xc8, 0xac, 0xd8, 0x74,
	0x6c, 0x39, 0x37, 0xaa, 0xcc, 0x5e, 0xf2, 0x8d, 0x72, 0x97, 0xc6, 0xb5, 0x0a, 0xe8, 0x08, 0x0e,
	0x59, 0x5d, 0x63, 0xe0, 0xb8, 0xd8, 0x7c, 0x37, 0x35, 0x6d, 0x47, 0x55, 0x98, 0x73, 0x68, 0xd9,
	0x83, 0x09, 0x1e, 0x8a, 0x68, 0xb5, 0xf3, 0x46, 0x5e, 0xfd, 0x13, 0x61, 0xb3, 0x6c, 0x1b, 0xad,
	0xa7, 0x20, 0x97, 0xdd, 0xca, 0xff, 0xb1, 0x94, 0x8e, 0xdd, 0x73, 0xe8, 0xcd, 0xc1, 0x2f, 0x4a,
	0xff, 0xcb, 0x6f, 0x45, 0x6b, 0xdf, 0x37, 0xf9, 0xea, 0xab, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x65, 0xce, 0x10, 0x41, 0xcc, 0x09, 0x00, 0x00,
}
