// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node_status_update.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeStatusUpdate struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	CommunityId          string   `protobuf:"bytes,2,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeStatusUpdate) Reset()         { *m = NodeStatusUpdate{} }
func (m *NodeStatusUpdate) String() string { return proto.CompactTextString(m) }
func (*NodeStatusUpdate) ProtoMessage()    {}
func (*NodeStatusUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a55205803df77bf, []int{0}
}

func (m *NodeStatusUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStatusUpdate.Unmarshal(m, b)
}
func (m *NodeStatusUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStatusUpdate.Marshal(b, m, deterministic)
}
func (m *NodeStatusUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStatusUpdate.Merge(m, src)
}
func (m *NodeStatusUpdate) XXX_Size() int {
	return xxx_messageInfo_NodeStatusUpdate.Size(m)
}
func (m *NodeStatusUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStatusUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStatusUpdate proto.InternalMessageInfo

func (m *NodeStatusUpdate) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *NodeStatusUpdate) GetCommunityId() string {
	if m != nil {
		return m.CommunityId
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeStatusUpdate)(nil), "protobuf.NodeStatusUpdate")
}

func init() {
	proto.RegisterFile("node_status_update.proto", fileDescriptor_2a55205803df77bf)
}

var fileDescriptor_2a55205803df77bf = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xc8, 0xcb, 0x4f, 0x49,
	0x8d, 0x2f, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x8e, 0x2f, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0xde, 0x5c, 0x02, 0x7e,
	0xf9, 0x29, 0xa9, 0xc1, 0x60, 0x45, 0xa1, 0x60, 0x35, 0x42, 0x22, 0x5c, 0xac, 0xc9, 0x39, 0xf9,
	0xc9, 0xd9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x10, 0x8e, 0x90, 0x22, 0x17, 0x4f, 0x72,
	0x7e, 0x6e, 0x6e, 0x69, 0x5e, 0x66, 0x49, 0x65, 0x7c, 0x66, 0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06,
	0x67, 0x10, 0x37, 0x5c, 0xcc, 0x33, 0xc5, 0x89, 0x37, 0x8a, 0x5b, 0x4f, 0xdf, 0x1a, 0x66, 0x76,
	0x12, 0x1b, 0x98, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x87, 0x92, 0xb1, 0xbb, 0x88, 0x00,
	0x00, 0x00,
}
