// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pairing.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SyncTrustedUser_TrustStatus int32

const (
	SyncTrustedUser_UNKNOWN       SyncTrustedUser_TrustStatus = 0
	SyncTrustedUser_TRUSTED       SyncTrustedUser_TrustStatus = 1
	SyncTrustedUser_UNTRUSTWORTHY SyncTrustedUser_TrustStatus = 2
)

var SyncTrustedUser_TrustStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "TRUSTED",
	2: "UNTRUSTWORTHY",
}

var SyncTrustedUser_TrustStatus_value = map[string]int32{
	"UNKNOWN":       0,
	"TRUSTED":       1,
	"UNTRUSTWORTHY": 2,
}

func (x SyncTrustedUser_TrustStatus) String() string {
	return proto.EnumName(SyncTrustedUser_TrustStatus_name, int32(x))
}

func (SyncTrustedUser_TrustStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{21, 0}
}

type SyncVerificationRequest_VerificationStatus int32

const (
	SyncVerificationRequest_UNKNOWN  SyncVerificationRequest_VerificationStatus = 0
	SyncVerificationRequest_PENDING  SyncVerificationRequest_VerificationStatus = 1
	SyncVerificationRequest_ACCEPTED SyncVerificationRequest_VerificationStatus = 2
	SyncVerificationRequest_DECLINED SyncVerificationRequest_VerificationStatus = 3
	SyncVerificationRequest_CANCELED SyncVerificationRequest_VerificationStatus = 4
)

var SyncVerificationRequest_VerificationStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "PENDING",
	2: "ACCEPTED",
	3: "DECLINED",
	4: "CANCELED",
}

var SyncVerificationRequest_VerificationStatus_value = map[string]int32{
	"UNKNOWN":  0,
	"PENDING":  1,
	"ACCEPTED": 2,
	"DECLINED": 3,
	"CANCELED": 4,
}

func (x SyncVerificationRequest_VerificationStatus) String() string {
	return proto.EnumName(SyncVerificationRequest_VerificationStatus_name, int32(x))
}

func (SyncVerificationRequest_VerificationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{22, 0}
}

type Backup struct {
	Clock                uint64                       `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Id                   string                       `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Contacts             []*SyncInstallationContactV2 `protobuf:"bytes,3,rep,name=contacts,proto3" json:"contacts,omitempty"`
	Communities          []*SyncCommunity             `protobuf:"bytes,4,rep,name=communities,proto3" json:"communities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *Backup) Reset()         { *m = Backup{} }
func (m *Backup) String() string { return proto.CompactTextString(m) }
func (*Backup) ProtoMessage()    {}
func (*Backup) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{0}
}

func (m *Backup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Backup.Unmarshal(m, b)
}
func (m *Backup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Backup.Marshal(b, m, deterministic)
}
func (m *Backup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Backup.Merge(m, src)
}
func (m *Backup) XXX_Size() int {
	return xxx_messageInfo_Backup.Size(m)
}
func (m *Backup) XXX_DiscardUnknown() {
	xxx_messageInfo_Backup.DiscardUnknown(m)
}

var xxx_messageInfo_Backup proto.InternalMessageInfo

func (m *Backup) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *Backup) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Backup) GetContacts() []*SyncInstallationContactV2 {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *Backup) GetCommunities() []*SyncCommunity {
	if m != nil {
		return m.Communities
	}
	return nil
}

type PairInstallation struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	InstallationId       string   `protobuf:"bytes,2,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	DeviceType           string   `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PairInstallation) Reset()         { *m = PairInstallation{} }
func (m *PairInstallation) String() string { return proto.CompactTextString(m) }
func (*PairInstallation) ProtoMessage()    {}
func (*PairInstallation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{1}
}

func (m *PairInstallation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairInstallation.Unmarshal(m, b)
}
func (m *PairInstallation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairInstallation.Marshal(b, m, deterministic)
}
func (m *PairInstallation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairInstallation.Merge(m, src)
}
func (m *PairInstallation) XXX_Size() int {
	return xxx_messageInfo_PairInstallation.Size(m)
}
func (m *PairInstallation) XXX_DiscardUnknown() {
	xxx_messageInfo_PairInstallation.DiscardUnknown(m)
}

var xxx_messageInfo_PairInstallation proto.InternalMessageInfo

func (m *PairInstallation) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *PairInstallation) GetInstallationId() string {
	if m != nil {
		return m.InstallationId
	}
	return ""
}

func (m *PairInstallation) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *PairInstallation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SyncInstallationContact struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ProfileImage         string   `protobuf:"bytes,3,opt,name=profile_image,json=profileImage,proto3" json:"profile_image,omitempty"`
	EnsName              string   `protobuf:"bytes,4,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	LastUpdated          uint64   `protobuf:"varint,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	SystemTags           []string `protobuf:"bytes,6,rep,name=system_tags,json=systemTags,proto3" json:"system_tags,omitempty"`
	LocalNickname        string   `protobuf:"bytes,7,opt,name=local_nickname,json=localNickname,proto3" json:"local_nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncInstallationContact) Reset()         { *m = SyncInstallationContact{} }
func (m *SyncInstallationContact) String() string { return proto.CompactTextString(m) }
func (*SyncInstallationContact) ProtoMessage()    {}
func (*SyncInstallationContact) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{2}
}

func (m *SyncInstallationContact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncInstallationContact.Unmarshal(m, b)
}
func (m *SyncInstallationContact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncInstallationContact.Marshal(b, m, deterministic)
}
func (m *SyncInstallationContact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInstallationContact.Merge(m, src)
}
func (m *SyncInstallationContact) XXX_Size() int {
	return xxx_messageInfo_SyncInstallationContact.Size(m)
}
func (m *SyncInstallationContact) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInstallationContact.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInstallationContact proto.InternalMessageInfo

func (m *SyncInstallationContact) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncInstallationContact) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SyncInstallationContact) GetProfileImage() string {
	if m != nil {
		return m.ProfileImage
	}
	return ""
}

func (m *SyncInstallationContact) GetEnsName() string {
	if m != nil {
		return m.EnsName
	}
	return ""
}

func (m *SyncInstallationContact) GetLastUpdated() uint64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func (m *SyncInstallationContact) GetSystemTags() []string {
	if m != nil {
		return m.SystemTags
	}
	return nil
}

func (m *SyncInstallationContact) GetLocalNickname() string {
	if m != nil {
		return m.LocalNickname
	}
	return ""
}

type SyncInstallationContactV2 struct {
	LastUpdatedLocally   uint64   `protobuf:"varint,1,opt,name=last_updated_locally,json=lastUpdatedLocally,proto3" json:"last_updated_locally,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ProfileImage         string   `protobuf:"bytes,3,opt,name=profile_image,json=profileImage,proto3" json:"profile_image,omitempty"`
	EnsName              string   `protobuf:"bytes,4,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	LastUpdated          uint64   `protobuf:"varint,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	SystemTags           []string `protobuf:"bytes,6,rep,name=system_tags,json=systemTags,proto3" json:"system_tags,omitempty"`
	LocalNickname        string   `protobuf:"bytes,7,opt,name=local_nickname,json=localNickname,proto3" json:"local_nickname,omitempty"`
	Added                bool     `protobuf:"varint,9,opt,name=added,proto3" json:"added,omitempty"`
	Blocked              bool     `protobuf:"varint,10,opt,name=blocked,proto3" json:"blocked,omitempty"`
	Muted                bool     `protobuf:"varint,11,opt,name=muted,proto3" json:"muted,omitempty"`
	Removed              bool     `protobuf:"varint,12,opt,name=removed,proto3" json:"removed,omitempty"`
	HasAddedUs           bool     `protobuf:"varint,13,opt,name=has_added_us,json=hasAddedUs,proto3" json:"has_added_us,omitempty"`
	VerificationStatus   int64    `protobuf:"varint,14,opt,name=verification_status,json=verificationStatus,proto3" json:"verification_status,omitempty"`
	TrustStatus          int64    `protobuf:"varint,15,opt,name=trust_status,json=trustStatus,proto3" json:"trust_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncInstallationContactV2) Reset()         { *m = SyncInstallationContactV2{} }
func (m *SyncInstallationContactV2) String() string { return proto.CompactTextString(m) }
func (*SyncInstallationContactV2) ProtoMessage()    {}
func (*SyncInstallationContactV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{3}
}

func (m *SyncInstallationContactV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncInstallationContactV2.Unmarshal(m, b)
}
func (m *SyncInstallationContactV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncInstallationContactV2.Marshal(b, m, deterministic)
}
func (m *SyncInstallationContactV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInstallationContactV2.Merge(m, src)
}
func (m *SyncInstallationContactV2) XXX_Size() int {
	return xxx_messageInfo_SyncInstallationContactV2.Size(m)
}
func (m *SyncInstallationContactV2) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInstallationContactV2.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInstallationContactV2 proto.InternalMessageInfo

func (m *SyncInstallationContactV2) GetLastUpdatedLocally() uint64 {
	if m != nil {
		return m.LastUpdatedLocally
	}
	return 0
}

func (m *SyncInstallationContactV2) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SyncInstallationContactV2) GetProfileImage() string {
	if m != nil {
		return m.ProfileImage
	}
	return ""
}

func (m *SyncInstallationContactV2) GetEnsName() string {
	if m != nil {
		return m.EnsName
	}
	return ""
}

func (m *SyncInstallationContactV2) GetLastUpdated() uint64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func (m *SyncInstallationContactV2) GetSystemTags() []string {
	if m != nil {
		return m.SystemTags
	}
	return nil
}

func (m *SyncInstallationContactV2) GetLocalNickname() string {
	if m != nil {
		return m.LocalNickname
	}
	return ""
}

func (m *SyncInstallationContactV2) GetAdded() bool {
	if m != nil {
		return m.Added
	}
	return false
}

func (m *SyncInstallationContactV2) GetBlocked() bool {
	if m != nil {
		return m.Blocked
	}
	return false
}

func (m *SyncInstallationContactV2) GetMuted() bool {
	if m != nil {
		return m.Muted
	}
	return false
}

func (m *SyncInstallationContactV2) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

func (m *SyncInstallationContactV2) GetHasAddedUs() bool {
	if m != nil {
		return m.HasAddedUs
	}
	return false
}

func (m *SyncInstallationContactV2) GetVerificationStatus() int64 {
	if m != nil {
		return m.VerificationStatus
	}
	return 0
}

func (m *SyncInstallationContactV2) GetTrustStatus() int64 {
	if m != nil {
		return m.TrustStatus
	}
	return 0
}

type SyncInstallationAccount struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	ProfileImage         string   `protobuf:"bytes,2,opt,name=profile_image,json=profileImage,proto3" json:"profile_image,omitempty"`
	LastUpdated          uint64   `protobuf:"varint,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncInstallationAccount) Reset()         { *m = SyncInstallationAccount{} }
func (m *SyncInstallationAccount) String() string { return proto.CompactTextString(m) }
func (*SyncInstallationAccount) ProtoMessage()    {}
func (*SyncInstallationAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{4}
}

func (m *SyncInstallationAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncInstallationAccount.Unmarshal(m, b)
}
func (m *SyncInstallationAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncInstallationAccount.Marshal(b, m, deterministic)
}
func (m *SyncInstallationAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInstallationAccount.Merge(m, src)
}
func (m *SyncInstallationAccount) XXX_Size() int {
	return xxx_messageInfo_SyncInstallationAccount.Size(m)
}
func (m *SyncInstallationAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInstallationAccount.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInstallationAccount proto.InternalMessageInfo

func (m *SyncInstallationAccount) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncInstallationAccount) GetProfileImage() string {
	if m != nil {
		return m.ProfileImage
	}
	return ""
}

func (m *SyncInstallationAccount) GetLastUpdated() uint64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

type SyncInstallationPublicChat struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncInstallationPublicChat) Reset()         { *m = SyncInstallationPublicChat{} }
func (m *SyncInstallationPublicChat) String() string { return proto.CompactTextString(m) }
func (*SyncInstallationPublicChat) ProtoMessage()    {}
func (*SyncInstallationPublicChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{5}
}

func (m *SyncInstallationPublicChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncInstallationPublicChat.Unmarshal(m, b)
}
func (m *SyncInstallationPublicChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncInstallationPublicChat.Marshal(b, m, deterministic)
}
func (m *SyncInstallationPublicChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInstallationPublicChat.Merge(m, src)
}
func (m *SyncInstallationPublicChat) XXX_Size() int {
	return xxx_messageInfo_SyncInstallationPublicChat.Size(m)
}
func (m *SyncInstallationPublicChat) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInstallationPublicChat.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInstallationPublicChat proto.InternalMessageInfo

func (m *SyncInstallationPublicChat) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncInstallationPublicChat) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SyncCommunity struct {
	Clock                uint64                         `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Id                   []byte                         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	PrivateKey           []byte                         `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Description          []byte                         `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Joined               bool                           `protobuf:"varint,5,opt,name=joined,proto3" json:"joined,omitempty"`
	Verified             bool                           `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"`
	Muted                bool                           `protobuf:"varint,7,opt,name=muted,proto3" json:"muted,omitempty"`
	RequestsToJoin       []*SyncCommunityRequestsToJoin `protobuf:"bytes,8,rep,name=requests_to_join,json=requestsToJoin,proto3" json:"requests_to_join,omitempty"`
	Settings             *SyncCommunitySettings         `protobuf:"bytes,9,opt,name=settings,proto3" json:"settings,omitempty"`
	Encrypted            bool                           `protobuf:"varint,10,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SyncCommunity) Reset()         { *m = SyncCommunity{} }
func (m *SyncCommunity) String() string { return proto.CompactTextString(m) }
func (*SyncCommunity) ProtoMessage()    {}
func (*SyncCommunity) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{6}
}

func (m *SyncCommunity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncCommunity.Unmarshal(m, b)
}
func (m *SyncCommunity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncCommunity.Marshal(b, m, deterministic)
}
func (m *SyncCommunity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncCommunity.Merge(m, src)
}
func (m *SyncCommunity) XXX_Size() int {
	return xxx_messageInfo_SyncCommunity.Size(m)
}
func (m *SyncCommunity) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncCommunity.DiscardUnknown(m)
}

var xxx_messageInfo_SyncCommunity proto.InternalMessageInfo

func (m *SyncCommunity) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncCommunity) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SyncCommunity) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *SyncCommunity) GetDescription() []byte {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *SyncCommunity) GetJoined() bool {
	if m != nil {
		return m.Joined
	}
	return false
}

func (m *SyncCommunity) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *SyncCommunity) GetMuted() bool {
	if m != nil {
		return m.Muted
	}
	return false
}

func (m *SyncCommunity) GetRequestsToJoin() []*SyncCommunityRequestsToJoin {
	if m != nil {
		return m.RequestsToJoin
	}
	return nil
}

func (m *SyncCommunity) GetSettings() *SyncCommunitySettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *SyncCommunity) GetEncrypted() bool {
	if m != nil {
		return m.Encrypted
	}
	return false
}

type SyncCommunityRequestsToJoin struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Clock                uint64   `protobuf:"varint,3,opt,name=clock,proto3" json:"clock,omitempty"`
	EnsName              string   `protobuf:"bytes,4,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	ChatId               string   `protobuf:"bytes,5,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	CommunityId          []byte   `protobuf:"bytes,6,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	State                uint64   `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncCommunityRequestsToJoin) Reset()         { *m = SyncCommunityRequestsToJoin{} }
func (m *SyncCommunityRequestsToJoin) String() string { return proto.CompactTextString(m) }
func (*SyncCommunityRequestsToJoin) ProtoMessage()    {}
func (*SyncCommunityRequestsToJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{7}
}

func (m *SyncCommunityRequestsToJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncCommunityRequestsToJoin.Unmarshal(m, b)
}
func (m *SyncCommunityRequestsToJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncCommunityRequestsToJoin.Marshal(b, m, deterministic)
}
func (m *SyncCommunityRequestsToJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncCommunityRequestsToJoin.Merge(m, src)
}
func (m *SyncCommunityRequestsToJoin) XXX_Size() int {
	return xxx_messageInfo_SyncCommunityRequestsToJoin.Size(m)
}
func (m *SyncCommunityRequestsToJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncCommunityRequestsToJoin.DiscardUnknown(m)
}

var xxx_messageInfo_SyncCommunityRequestsToJoin proto.InternalMessageInfo

func (m *SyncCommunityRequestsToJoin) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SyncCommunityRequestsToJoin) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *SyncCommunityRequestsToJoin) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncCommunityRequestsToJoin) GetEnsName() string {
	if m != nil {
		return m.EnsName
	}
	return ""
}

func (m *SyncCommunityRequestsToJoin) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *SyncCommunityRequestsToJoin) GetCommunityId() []byte {
	if m != nil {
		return m.CommunityId
	}
	return nil
}

func (m *SyncCommunityRequestsToJoin) GetState() uint64 {
	if m != nil {
		return m.State
	}
	return 0
}

type SyncInstallation struct {
	Contacts             []*SyncInstallationContact    `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	PublicChats          []*SyncInstallationPublicChat `protobuf:"bytes,2,rep,name=public_chats,json=publicChats,proto3" json:"public_chats,omitempty"`
	Account              *SyncInstallationAccount      `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Communities          []*SyncCommunity              `protobuf:"bytes,4,rep,name=communities,proto3" json:"communities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SyncInstallation) Reset()         { *m = SyncInstallation{} }
func (m *SyncInstallation) String() string { return proto.CompactTextString(m) }
func (*SyncInstallation) ProtoMessage()    {}
func (*SyncInstallation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{8}
}

func (m *SyncInstallation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncInstallation.Unmarshal(m, b)
}
func (m *SyncInstallation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncInstallation.Marshal(b, m, deterministic)
}
func (m *SyncInstallation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInstallation.Merge(m, src)
}
func (m *SyncInstallation) XXX_Size() int {
	return xxx_messageInfo_SyncInstallation.Size(m)
}
func (m *SyncInstallation) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInstallation.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInstallation proto.InternalMessageInfo

func (m *SyncInstallation) GetContacts() []*SyncInstallationContact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *SyncInstallation) GetPublicChats() []*SyncInstallationPublicChat {
	if m != nil {
		return m.PublicChats
	}
	return nil
}

func (m *SyncInstallation) GetAccount() *SyncInstallationAccount {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *SyncInstallation) GetCommunities() []*SyncCommunity {
	if m != nil {
		return m.Communities
	}
	return nil
}

type SyncChatRemoved struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncChatRemoved) Reset()         { *m = SyncChatRemoved{} }
func (m *SyncChatRemoved) String() string { return proto.CompactTextString(m) }
func (*SyncChatRemoved) ProtoMessage()    {}
func (*SyncChatRemoved) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{9}
}

func (m *SyncChatRemoved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncChatRemoved.Unmarshal(m, b)
}
func (m *SyncChatRemoved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncChatRemoved.Marshal(b, m, deterministic)
}
func (m *SyncChatRemoved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncChatRemoved.Merge(m, src)
}
func (m *SyncChatRemoved) XXX_Size() int {
	return xxx_messageInfo_SyncChatRemoved.Size(m)
}
func (m *SyncChatRemoved) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncChatRemoved.DiscardUnknown(m)
}

var xxx_messageInfo_SyncChatRemoved proto.InternalMessageInfo

func (m *SyncChatRemoved) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncChatRemoved) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SyncChatMessagesRead struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncChatMessagesRead) Reset()         { *m = SyncChatMessagesRead{} }
func (m *SyncChatMessagesRead) String() string { return proto.CompactTextString(m) }
func (*SyncChatMessagesRead) ProtoMessage()    {}
func (*SyncChatMessagesRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{10}
}

func (m *SyncChatMessagesRead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncChatMessagesRead.Unmarshal(m, b)
}
func (m *SyncChatMessagesRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncChatMessagesRead.Marshal(b, m, deterministic)
}
func (m *SyncChatMessagesRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncChatMessagesRead.Merge(m, src)
}
func (m *SyncChatMessagesRead) XXX_Size() int {
	return xxx_messageInfo_SyncChatMessagesRead.Size(m)
}
func (m *SyncChatMessagesRead) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncChatMessagesRead.DiscardUnknown(m)
}

var xxx_messageInfo_SyncChatMessagesRead proto.InternalMessageInfo

func (m *SyncChatMessagesRead) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncChatMessagesRead) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SyncActivityCenterRead struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Ids                  [][]byte `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncActivityCenterRead) Reset()         { *m = SyncActivityCenterRead{} }
func (m *SyncActivityCenterRead) String() string { return proto.CompactTextString(m) }
func (*SyncActivityCenterRead) ProtoMessage()    {}
func (*SyncActivityCenterRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{11}
}

func (m *SyncActivityCenterRead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncActivityCenterRead.Unmarshal(m, b)
}
func (m *SyncActivityCenterRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncActivityCenterRead.Marshal(b, m, deterministic)
}
func (m *SyncActivityCenterRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncActivityCenterRead.Merge(m, src)
}
func (m *SyncActivityCenterRead) XXX_Size() int {
	return xxx_messageInfo_SyncActivityCenterRead.Size(m)
}
func (m *SyncActivityCenterRead) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncActivityCenterRead.DiscardUnknown(m)
}

var xxx_messageInfo_SyncActivityCenterRead proto.InternalMessageInfo

func (m *SyncActivityCenterRead) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncActivityCenterRead) GetIds() [][]byte {
	if m != nil {
		return m.Ids
	}
	return nil
}

type SyncActivityCenterAccepted struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Ids                  [][]byte `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncActivityCenterAccepted) Reset()         { *m = SyncActivityCenterAccepted{} }
func (m *SyncActivityCenterAccepted) String() string { return proto.CompactTextString(m) }
func (*SyncActivityCenterAccepted) ProtoMessage()    {}
func (*SyncActivityCenterAccepted) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{12}
}

func (m *SyncActivityCenterAccepted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncActivityCenterAccepted.Unmarshal(m, b)
}
func (m *SyncActivityCenterAccepted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncActivityCenterAccepted.Marshal(b, m, deterministic)
}
func (m *SyncActivityCenterAccepted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncActivityCenterAccepted.Merge(m, src)
}
func (m *SyncActivityCenterAccepted) XXX_Size() int {
	return xxx_messageInfo_SyncActivityCenterAccepted.Size(m)
}
func (m *SyncActivityCenterAccepted) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncActivityCenterAccepted.DiscardUnknown(m)
}

var xxx_messageInfo_SyncActivityCenterAccepted proto.InternalMessageInfo

func (m *SyncActivityCenterAccepted) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncActivityCenterAccepted) GetIds() [][]byte {
	if m != nil {
		return m.Ids
	}
	return nil
}

type SyncActivityCenterDismissed struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Ids                  [][]byte `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncActivityCenterDismissed) Reset()         { *m = SyncActivityCenterDismissed{} }
func (m *SyncActivityCenterDismissed) String() string { return proto.CompactTextString(m) }
func (*SyncActivityCenterDismissed) ProtoMessage()    {}
func (*SyncActivityCenterDismissed) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{13}
}

func (m *SyncActivityCenterDismissed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncActivityCenterDismissed.Unmarshal(m, b)
}
func (m *SyncActivityCenterDismissed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncActivityCenterDismissed.Marshal(b, m, deterministic)
}
func (m *SyncActivityCenterDismissed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncActivityCenterDismissed.Merge(m, src)
}
func (m *SyncActivityCenterDismissed) XXX_Size() int {
	return xxx_messageInfo_SyncActivityCenterDismissed.Size(m)
}
func (m *SyncActivityCenterDismissed) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncActivityCenterDismissed.DiscardUnknown(m)
}

var xxx_messageInfo_SyncActivityCenterDismissed proto.InternalMessageInfo

func (m *SyncActivityCenterDismissed) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncActivityCenterDismissed) GetIds() [][]byte {
	if m != nil {
		return m.Ids
	}
	return nil
}

type SyncBookmark struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl             string   `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Removed              bool     `protobuf:"varint,5,opt,name=removed,proto3" json:"removed,omitempty"`
	DeletedAt            uint64   `protobuf:"varint,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncBookmark) Reset()         { *m = SyncBookmark{} }
func (m *SyncBookmark) String() string { return proto.CompactTextString(m) }
func (*SyncBookmark) ProtoMessage()    {}
func (*SyncBookmark) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{14}
}

func (m *SyncBookmark) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncBookmark.Unmarshal(m, b)
}
func (m *SyncBookmark) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncBookmark.Marshal(b, m, deterministic)
}
func (m *SyncBookmark) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncBookmark.Merge(m, src)
}
func (m *SyncBookmark) XXX_Size() int {
	return xxx_messageInfo_SyncBookmark.Size(m)
}
func (m *SyncBookmark) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncBookmark.DiscardUnknown(m)
}

var xxx_messageInfo_SyncBookmark proto.InternalMessageInfo

func (m *SyncBookmark) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncBookmark) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SyncBookmark) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SyncBookmark) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *SyncBookmark) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

func (m *SyncBookmark) GetDeletedAt() uint64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

type SyncClearHistory struct {
	ChatId               string   `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ClearedAt            uint64   `protobuf:"varint,2,opt,name=cleared_at,json=clearedAt,proto3" json:"cleared_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncClearHistory) Reset()         { *m = SyncClearHistory{} }
func (m *SyncClearHistory) String() string { return proto.CompactTextString(m) }
func (*SyncClearHistory) ProtoMessage()    {}
func (*SyncClearHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{15}
}

func (m *SyncClearHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncClearHistory.Unmarshal(m, b)
}
func (m *SyncClearHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncClearHistory.Marshal(b, m, deterministic)
}
func (m *SyncClearHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncClearHistory.Merge(m, src)
}
func (m *SyncClearHistory) XXX_Size() int {
	return xxx_messageInfo_SyncClearHistory.Size(m)
}
func (m *SyncClearHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncClearHistory.DiscardUnknown(m)
}

var xxx_messageInfo_SyncClearHistory proto.InternalMessageInfo

func (m *SyncClearHistory) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *SyncClearHistory) GetClearedAt() uint64 {
	if m != nil {
		return m.ClearedAt
	}
	return 0
}

type SyncProfilePicture struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Width                uint32   `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	FileSize             uint32   `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ResizeTarget         uint32   `protobuf:"varint,6,opt,name=resize_target,json=resizeTarget,proto3" json:"resize_target,omitempty"`
	Clock                uint64   `protobuf:"varint,7,opt,name=clock,proto3" json:"clock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncProfilePicture) Reset()         { *m = SyncProfilePicture{} }
func (m *SyncProfilePicture) String() string { return proto.CompactTextString(m) }
func (*SyncProfilePicture) ProtoMessage()    {}
func (*SyncProfilePicture) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{16}
}

func (m *SyncProfilePicture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncProfilePicture.Unmarshal(m, b)
}
func (m *SyncProfilePicture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncProfilePicture.Marshal(b, m, deterministic)
}
func (m *SyncProfilePicture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncProfilePicture.Merge(m, src)
}
func (m *SyncProfilePicture) XXX_Size() int {
	return xxx_messageInfo_SyncProfilePicture.Size(m)
}
func (m *SyncProfilePicture) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncProfilePicture.DiscardUnknown(m)
}

var xxx_messageInfo_SyncProfilePicture proto.InternalMessageInfo

func (m *SyncProfilePicture) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SyncProfilePicture) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *SyncProfilePicture) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *SyncProfilePicture) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *SyncProfilePicture) GetFileSize() uint32 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *SyncProfilePicture) GetResizeTarget() uint32 {
	if m != nil {
		return m.ResizeTarget
	}
	return 0
}

func (m *SyncProfilePicture) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

type SyncProfilePictures struct {
	KeyUid               string                `protobuf:"bytes,1,opt,name=key_uid,json=keyUid,proto3" json:"key_uid,omitempty"`
	Pictures             []*SyncProfilePicture `protobuf:"bytes,2,rep,name=pictures,proto3" json:"pictures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SyncProfilePictures) Reset()         { *m = SyncProfilePictures{} }
func (m *SyncProfilePictures) String() string { return proto.CompactTextString(m) }
func (*SyncProfilePictures) ProtoMessage()    {}
func (*SyncProfilePictures) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{17}
}

func (m *SyncProfilePictures) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncProfilePictures.Unmarshal(m, b)
}
func (m *SyncProfilePictures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncProfilePictures.Marshal(b, m, deterministic)
}
func (m *SyncProfilePictures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncProfilePictures.Merge(m, src)
}
func (m *SyncProfilePictures) XXX_Size() int {
	return xxx_messageInfo_SyncProfilePictures.Size(m)
}
func (m *SyncProfilePictures) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncProfilePictures.DiscardUnknown(m)
}

var xxx_messageInfo_SyncProfilePictures proto.InternalMessageInfo

func (m *SyncProfilePictures) GetKeyUid() string {
	if m != nil {
		return m.KeyUid
	}
	return ""
}

func (m *SyncProfilePictures) GetPictures() []*SyncProfilePicture {
	if m != nil {
		return m.Pictures
	}
	return nil
}

type SyncWalletAccount struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Wallet               bool     `protobuf:"varint,3,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Chat                 bool     `protobuf:"varint,4,opt,name=chat,proto3" json:"chat,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Storage              string   `protobuf:"bytes,6,opt,name=storage,proto3" json:"storage,omitempty"`
	Path                 string   `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,8,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Name                 string   `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Color                string   `protobuf:"bytes,10,opt,name=color,proto3" json:"color,omitempty"`
	Hidden               bool     `protobuf:"varint,11,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Removed              bool     `protobuf:"varint,12,opt,name=removed,proto3" json:"removed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncWalletAccount) Reset()         { *m = SyncWalletAccount{} }
func (m *SyncWalletAccount) String() string { return proto.CompactTextString(m) }
func (*SyncWalletAccount) ProtoMessage()    {}
func (*SyncWalletAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{18}
}

func (m *SyncWalletAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncWalletAccount.Unmarshal(m, b)
}
func (m *SyncWalletAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncWalletAccount.Marshal(b, m, deterministic)
}
func (m *SyncWalletAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncWalletAccount.Merge(m, src)
}
func (m *SyncWalletAccount) XXX_Size() int {
	return xxx_messageInfo_SyncWalletAccount.Size(m)
}
func (m *SyncWalletAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncWalletAccount.DiscardUnknown(m)
}

var xxx_messageInfo_SyncWalletAccount proto.InternalMessageInfo

func (m *SyncWalletAccount) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncWalletAccount) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *SyncWalletAccount) GetWallet() bool {
	if m != nil {
		return m.Wallet
	}
	return false
}

func (m *SyncWalletAccount) GetChat() bool {
	if m != nil {
		return m.Chat
	}
	return false
}

func (m *SyncWalletAccount) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SyncWalletAccount) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

func (m *SyncWalletAccount) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SyncWalletAccount) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *SyncWalletAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SyncWalletAccount) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *SyncWalletAccount) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

func (m *SyncWalletAccount) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

type SyncWalletAccounts struct {
	Accounts             []*SyncWalletAccount `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SyncWalletAccounts) Reset()         { *m = SyncWalletAccounts{} }
func (m *SyncWalletAccounts) String() string { return proto.CompactTextString(m) }
func (*SyncWalletAccounts) ProtoMessage()    {}
func (*SyncWalletAccounts) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{19}
}

func (m *SyncWalletAccounts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncWalletAccounts.Unmarshal(m, b)
}
func (m *SyncWalletAccounts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncWalletAccounts.Marshal(b, m, deterministic)
}
func (m *SyncWalletAccounts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncWalletAccounts.Merge(m, src)
}
func (m *SyncWalletAccounts) XXX_Size() int {
	return xxx_messageInfo_SyncWalletAccounts.Size(m)
}
func (m *SyncWalletAccounts) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncWalletAccounts.DiscardUnknown(m)
}

var xxx_messageInfo_SyncWalletAccounts proto.InternalMessageInfo

func (m *SyncWalletAccounts) GetAccounts() []*SyncWalletAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type SyncCommunitySettings struct {
	Clock                        uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	CommunityId                  string   `protobuf:"bytes,2,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	HistoryArchiveSupportEnabled bool     `protobuf:"varint,3,opt,name=history_archive_support_enabled,json=historyArchiveSupportEnabled,proto3" json:"history_archive_support_enabled,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *SyncCommunitySettings) Reset()         { *m = SyncCommunitySettings{} }
func (m *SyncCommunitySettings) String() string { return proto.CompactTextString(m) }
func (*SyncCommunitySettings) ProtoMessage()    {}
func (*SyncCommunitySettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{20}
}

func (m *SyncCommunitySettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncCommunitySettings.Unmarshal(m, b)
}
func (m *SyncCommunitySettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncCommunitySettings.Marshal(b, m, deterministic)
}
func (m *SyncCommunitySettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncCommunitySettings.Merge(m, src)
}
func (m *SyncCommunitySettings) XXX_Size() int {
	return xxx_messageInfo_SyncCommunitySettings.Size(m)
}
func (m *SyncCommunitySettings) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncCommunitySettings.DiscardUnknown(m)
}

var xxx_messageInfo_SyncCommunitySettings proto.InternalMessageInfo

func (m *SyncCommunitySettings) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncCommunitySettings) GetCommunityId() string {
	if m != nil {
		return m.CommunityId
	}
	return ""
}

func (m *SyncCommunitySettings) GetHistoryArchiveSupportEnabled() bool {
	if m != nil {
		return m.HistoryArchiveSupportEnabled
	}
	return false
}

type SyncTrustedUser struct {
	Clock                uint64                      `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Id                   string                      `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Status               SyncTrustedUser_TrustStatus `protobuf:"varint,3,opt,name=status,proto3,enum=protobuf.SyncTrustedUser_TrustStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *SyncTrustedUser) Reset()         { *m = SyncTrustedUser{} }
func (m *SyncTrustedUser) String() string { return proto.CompactTextString(m) }
func (*SyncTrustedUser) ProtoMessage()    {}
func (*SyncTrustedUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{21}
}

func (m *SyncTrustedUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncTrustedUser.Unmarshal(m, b)
}
func (m *SyncTrustedUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncTrustedUser.Marshal(b, m, deterministic)
}
func (m *SyncTrustedUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncTrustedUser.Merge(m, src)
}
func (m *SyncTrustedUser) XXX_Size() int {
	return xxx_messageInfo_SyncTrustedUser.Size(m)
}
func (m *SyncTrustedUser) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncTrustedUser.DiscardUnknown(m)
}

var xxx_messageInfo_SyncTrustedUser proto.InternalMessageInfo

func (m *SyncTrustedUser) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncTrustedUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SyncTrustedUser) GetStatus() SyncTrustedUser_TrustStatus {
	if m != nil {
		return m.Status
	}
	return SyncTrustedUser_UNKNOWN
}

type SyncVerificationRequest struct {
	Clock                uint64                                     `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	From                 string                                     `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string                                     `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Challenge            string                                     `protobuf:"bytes,4,opt,name=challenge,proto3" json:"challenge,omitempty"`
	RequestedAt          uint64                                     `protobuf:"varint,5,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	Response             string                                     `protobuf:"bytes,6,opt,name=response,proto3" json:"response,omitempty"`
	RepliedAt            uint64                                     `protobuf:"varint,7,opt,name=replied_at,json=repliedAt,proto3" json:"replied_at,omitempty"`
	VerificationStatus   SyncVerificationRequest_VerificationStatus `protobuf:"varint,8,opt,name=verification_status,json=verificationStatus,proto3,enum=protobuf.SyncVerificationRequest_VerificationStatus" json:"verification_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *SyncVerificationRequest) Reset()         { *m = SyncVerificationRequest{} }
func (m *SyncVerificationRequest) String() string { return proto.CompactTextString(m) }
func (*SyncVerificationRequest) ProtoMessage()    {}
func (*SyncVerificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{22}
}

func (m *SyncVerificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncVerificationRequest.Unmarshal(m, b)
}
func (m *SyncVerificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncVerificationRequest.Marshal(b, m, deterministic)
}
func (m *SyncVerificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncVerificationRequest.Merge(m, src)
}
func (m *SyncVerificationRequest) XXX_Size() int {
	return xxx_messageInfo_SyncVerificationRequest.Size(m)
}
func (m *SyncVerificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncVerificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncVerificationRequest proto.InternalMessageInfo

func (m *SyncVerificationRequest) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncVerificationRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SyncVerificationRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SyncVerificationRequest) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

func (m *SyncVerificationRequest) GetRequestedAt() uint64 {
	if m != nil {
		return m.RequestedAt
	}
	return 0
}

func (m *SyncVerificationRequest) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *SyncVerificationRequest) GetRepliedAt() uint64 {
	if m != nil {
		return m.RepliedAt
	}
	return 0
}

func (m *SyncVerificationRequest) GetVerificationStatus() SyncVerificationRequest_VerificationStatus {
	if m != nil {
		return m.VerificationStatus
	}
	return SyncVerificationRequest_UNKNOWN
}

func init() {
	proto.RegisterEnum("protobuf.SyncTrustedUser_TrustStatus", SyncTrustedUser_TrustStatus_name, SyncTrustedUser_TrustStatus_value)
	proto.RegisterEnum("protobuf.SyncVerificationRequest_VerificationStatus", SyncVerificationRequest_VerificationStatus_name, SyncVerificationRequest_VerificationStatus_value)
	proto.RegisterType((*Backup)(nil), "protobuf.Backup")
	proto.RegisterType((*PairInstallation)(nil), "protobuf.PairInstallation")
	proto.RegisterType((*SyncInstallationContact)(nil), "protobuf.SyncInstallationContact")
	proto.RegisterType((*SyncInstallationContactV2)(nil), "protobuf.SyncInstallationContactV2")
	proto.RegisterType((*SyncInstallationAccount)(nil), "protobuf.SyncInstallationAccount")
	proto.RegisterType((*SyncInstallationPublicChat)(nil), "protobuf.SyncInstallationPublicChat")
	proto.RegisterType((*SyncCommunity)(nil), "protobuf.SyncCommunity")
	proto.RegisterType((*SyncCommunityRequestsToJoin)(nil), "protobuf.SyncCommunityRequestsToJoin")
	proto.RegisterType((*SyncInstallation)(nil), "protobuf.SyncInstallation")
	proto.RegisterType((*SyncChatRemoved)(nil), "protobuf.SyncChatRemoved")
	proto.RegisterType((*SyncChatMessagesRead)(nil), "protobuf.SyncChatMessagesRead")
	proto.RegisterType((*SyncActivityCenterRead)(nil), "protobuf.SyncActivityCenterRead")
	proto.RegisterType((*SyncActivityCenterAccepted)(nil), "protobuf.SyncActivityCenterAccepted")
	proto.RegisterType((*SyncActivityCenterDismissed)(nil), "protobuf.SyncActivityCenterDismissed")
	proto.RegisterType((*SyncBookmark)(nil), "protobuf.SyncBookmark")
	proto.RegisterType((*SyncClearHistory)(nil), "protobuf.SyncClearHistory")
	proto.RegisterType((*SyncProfilePicture)(nil), "protobuf.SyncProfilePicture")
	proto.RegisterType((*SyncProfilePictures)(nil), "protobuf.SyncProfilePictures")
	proto.RegisterType((*SyncWalletAccount)(nil), "protobuf.SyncWalletAccount")
	proto.RegisterType((*SyncWalletAccounts)(nil), "protobuf.SyncWalletAccounts")
	proto.RegisterType((*SyncCommunitySettings)(nil), "protobuf.SyncCommunitySettings")
	proto.RegisterType((*SyncTrustedUser)(nil), "protobuf.SyncTrustedUser")
	proto.RegisterType((*SyncVerificationRequest)(nil), "protobuf.SyncVerificationRequest")
}

func init() {
	proto.RegisterFile("pairing.proto", fileDescriptor_d61ab7221f0b5518)
}

var fileDescriptor_d61ab7221f0b5518 = []byte{
	// 1539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0xcd, 0x72, 0xdb, 0x46,
	0x12, 0x5e, 0x90, 0x14, 0x09, 0x36, 0x49, 0x99, 0x1e, 0x7b, 0x6d, 0xf8, 0xaf, 0x44, 0xc3, 0xeb,
	0x5a, 0x9d, 0xe4, 0x2d, 0xef, 0x56, 0x79, 0x77, 0x1d, 0x57, 0x42, 0x51, 0x2c, 0x5b, 0xfe, 0xa1,
	0x55, 0x10, 0x65, 0x27, 0xb9, 0xa0, 0x46, 0xc0, 0x88, 0x9c, 0x10, 0x04, 0x10, 0xcc, 0x50, 0x2e,
	0xfa, 0x01, 0x72, 0x4e, 0xe5, 0x92, 0x6b, 0xce, 0xc9, 0x2d, 0x4f, 0x91, 0x5b, 0xde, 0x20, 0x0f,
	0x90, 0x43, 0x9e, 0x21, 0xd5, 0x33, 0x43, 0x12, 0x94, 0x44, 0x59, 0xa9, 0x9c, 0x72, 0xe2, 0xf4,
	0x37, 0x3d, 0x8d, 0xfe, 0xef, 0x26, 0x34, 0x52, 0xca, 0x33, 0x1e, 0x0f, 0xb6, 0xd2, 0x2c, 0x91,
	0x09, 0xb1, 0xd5, 0xcf, 0xe1, 0xe4, 0xc8, 0xfd, 0xde, 0x82, 0xf2, 0x36, 0x0d, 0x46, 0x93, 0x94,
	0x5c, 0x85, 0xb5, 0x20, 0x4a, 0x82, 0x91, 0x63, 0xb5, 0xac, 0xcd, 0x92, 0xa7, 0x09, 0xb2, 0x0e,
	0x05, 0x1e, 0x3a, 0x85, 0x96, 0xb5, 0x59, 0xf5, 0x0a, 0x3c, 0x24, 0x1f, 0x83, 0x1d, 0x24, 0xb1,
	0xa4, 0x81, 0x14, 0x4e, 0xb1, 0x55, 0xdc, 0xac, 0x3d, 0xbc, 0xb7, 0x35, 0x93, 0xb6, 0xb5, 0x3f,
	0x8d, 0x83, 0xdd, 0x58, 0x48, 0x1a, 0x45, 0x54, 0xf2, 0x24, 0xee, 0x68, 0xce, 0x37, 0x0f, 0xbd,
	0xf9, 0x23, 0xf2, 0x3f, 0xa8, 0x05, 0xc9, 0x78, 0x3c, 0x89, 0xb9, 0xe4, 0x4c, 0x38, 0x25, 0x25,
	0xe3, 0xfa, 0xb2, 0x8c, 0x8e, 0x61, 0x98, 0x7a, 0x79, 0x5e, 0xf7, 0x2b, 0x0b, 0x9a, 0x7b, 0x94,
	0x67, 0xf9, 0x4f, 0xac, 0x50, 0xfb, 0x9f, 0x70, 0x89, 0xe7, 0xb8, 0xfc, 0xb9, 0x0d, 0xeb, 0x79,
	0x78, 0x37, 0x24, 0x1b, 0x50, 0x0b, 0xd9, 0x31, 0x0f, 0x98, 0x2f, 0xa7, 0x29, 0x73, 0x8a, 0x8a,
	0x09, 0x34, 0xd4, 0x9f, 0xa6, 0x8c, 0x10, 0x28, 0xc5, 0x74, 0xcc, 0x9c, 0x92, 0xba, 0x51, 0x67,
	0xf7, 0x57, 0x0b, 0xae, 0xaf, 0xb0, 0xf5, 0x82, 0x6e, 0xbc, 0x07, 0x8d, 0x34, 0x4b, 0x8e, 0x78,
	0xc4, 0x7c, 0x3e, 0xa6, 0x83, 0xd9, 0x87, 0xeb, 0x06, 0xdc, 0x45, 0x8c, 0xdc, 0x00, 0x9b, 0xc5,
	0xc2, 0xcf, 0x7d, 0xbe, 0xc2, 0x62, 0xd1, 0xa3, 0x63, 0x46, 0xee, 0x42, 0x3d, 0xa2, 0x42, 0xfa,
	0x93, 0x34, 0xa4, 0x92, 0x85, 0xce, 0x9a, 0xfa, 0x58, 0x0d, 0xb1, 0x03, 0x0d, 0xa1, 0x65, 0x62,
	0x2a, 0x24, 0x1b, 0xfb, 0x92, 0x0e, 0x84, 0x53, 0x6e, 0x15, 0xd1, 0x32, 0x0d, 0xf5, 0xe9, 0x40,
	0x90, 0xfb, 0xb0, 0x1e, 0x25, 0x01, 0x8d, 0xfc, 0x98, 0x07, 0x23, 0xf5, 0x91, 0x8a, 0xfa, 0x48,
	0x43, 0xa1, 0x3d, 0x03, 0xba, 0xbf, 0x14, 0xe1, 0xc6, 0xca, 0xc0, 0x92, 0x7f, 0xc1, 0xd5, 0xbc,
	0x22, 0xbe, 0x7a, 0x1b, 0x4d, 0x8d, 0xf5, 0x24, 0xa7, 0xd0, 0x4b, 0x7d, 0xf3, 0x17, 0x76, 0x05,
	0xc6, 0x96, 0x86, 0x21, 0x0b, 0x9d, 0x6a, 0xcb, 0xda, 0xb4, 0x3d, 0x4d, 0x10, 0x07, 0x2a, 0x87,
	0x18, 0x64, 0x16, 0x3a, 0xa0, 0xf0, 0x19, 0x89, 0xfc, 0xe3, 0x09, 0xea, 0x54, 0xd3, 0xfc, 0x8a,
	0x40, 0xfe, 0x8c, 0x8d, 0x93, 0x63, 0x16, 0x3a, 0x75, 0xcd, 0x6f, 0x48, 0xd2, 0x82, 0xfa, 0x90,
	0x0a, 0x5f, 0x89, 0xf5, 0x27, 0xc2, 0x69, 0xa8, 0x6b, 0x18, 0x52, 0xd1, 0x46, 0xe8, 0x40, 0x90,
	0x07, 0x70, 0xe5, 0x98, 0x65, 0xfc, 0x88, 0x07, 0x3a, 0xaf, 0x85, 0xa4, 0x72, 0x22, 0x9c, 0xf5,
	0x96, 0xb5, 0x59, 0xf4, 0x48, 0xfe, 0x6a, 0x5f, 0xdd, 0xa0, 0x77, 0x64, 0x36, 0x11, 0x72, 0xc6,
	0x79, 0x49, 0x71, 0xd6, 0x14, 0xa6, 0x59, 0xdc, 0x77, 0xa7, 0x93, 0xb9, 0x1d, 0x04, 0xc9, 0x24,
	0x5e, 0x95, 0xcc, 0xa7, 0x22, 0x56, 0x38, 0x23, 0x62, 0x27, 0xc3, 0x52, 0x3c, 0x15, 0x16, 0x77,
	0x1b, 0x6e, 0x9e, 0xfc, 0xf0, 0xde, 0xe4, 0x30, 0xe2, 0x41, 0x67, 0x48, 0x2f, 0x58, 0x48, 0xee,
	0x6f, 0x05, 0x68, 0x2c, 0xb5, 0x8c, 0x0f, 0xbe, 0xab, 0xab, 0xac, 0xdb, 0x80, 0x5a, 0x9a, 0xf1,
	0x63, 0x2a, 0x99, 0x3f, 0x62, 0x53, 0xa5, 0x5d, 0xdd, 0x03, 0x03, 0xbd, 0x60, 0x53, 0xd2, 0xc2,
	0xc6, 0x20, 0x82, 0x8c, 0xa7, 0xa8, 0x97, 0x4a, 0xba, 0xba, 0x97, 0x87, 0xc8, 0x35, 0x28, 0x7f,
	0x91, 0xf0, 0xd8, 0xa4, 0x9c, 0xed, 0x19, 0x8a, 0xdc, 0x04, 0x5b, 0x07, 0x82, 0x85, 0x4e, 0x59,
	0xdd, 0xcc, 0xe9, 0x45, 0x46, 0x54, 0xf2, 0x19, 0xf1, 0x1a, 0x9a, 0x19, 0xfb, 0x72, 0xc2, 0x84,
	0x14, 0xbe, 0x4c, 0x7c, 0x94, 0xe3, 0xd8, 0xaa, 0x31, 0xde, 0x5f, 0xd5, 0x18, 0x0d, 0x7b, 0x3f,
	0x79, 0x9e, 0xf0, 0xd8, 0x5b, 0xcf, 0x96, 0x68, 0xf2, 0x18, 0x6c, 0xc1, 0xa4, 0xe4, 0xf1, 0x40,
	0xa8, 0x5c, 0xad, 0x3d, 0xdc, 0x58, 0x21, 0x68, 0xdf, 0xb0, 0x79, 0xf3, 0x07, 0xe4, 0x36, 0x54,
	0x59, 0x1c, 0x64, 0xd3, 0x54, 0xce, 0x33, 0x7a, 0x01, 0xb8, 0x3f, 0x5b, 0x70, 0xeb, 0x1c, 0x55,
	0x8c, 0xa3, 0xad, 0xb9, 0xa3, 0xef, 0x00, 0xa4, 0x2a, 0xa8, 0xca, 0xcf, 0x3a, 0x70, 0x55, 0x8d,
	0xa0, 0x9b, 0xe7, 0xd1, 0x2a, 0xe6, 0xa3, 0x75, 0x4e, 0xb9, 0x5f, 0x87, 0x4a, 0x30, 0xa4, 0x12,
	0x3b, 0xfa, 0x9a, 0xba, 0x29, 0x23, 0xb9, 0x1b, 0x62, 0xc2, 0xcd, 0x86, 0xc5, 0x14, 0x6f, 0xcb,
	0x3a, 0x62, 0x73, 0x6c, 0x57, 0x79, 0x1f, 0xcb, 0x40, 0x57, 0x77, 0xc9, 0xd3, 0x84, 0xfb, 0x4d,
	0x01, 0x9a, 0x27, 0xf3, 0x90, 0x3c, 0xc9, 0xcd, 0x39, 0x4b, 0x85, 0xe2, 0xee, 0x07, 0xe7, 0x5c,
	0x6e, 0xca, 0x3d, 0x85, 0xba, 0xb1, 0x1a, 0xb5, 0x13, 0x4e, 0x41, 0x89, 0xf8, 0xc7, 0x6a, 0x11,
	0x8b, 0xc4, 0xf7, 0x6a, 0xe9, 0xfc, 0x2c, 0xc8, 0x63, 0xa8, 0x50, 0x5d, 0x8c, 0xca, 0x43, 0xe7,
	0xaa, 0x61, 0xaa, 0xd6, 0x9b, 0xbd, 0xf8, 0x33, 0xb3, 0xf6, 0x11, 0x5c, 0x52, 0xb7, 0xa8, 0x90,
	0xe9, 0x4e, 0x17, 0x2b, 0xc8, 0x8f, 0xe0, 0xea, 0xec, 0xe1, 0x2b, 0x26, 0x04, 0x1d, 0x30, 0xe1,
	0x31, 0x7a, 0xd1, 0xd7, 0x9f, 0xc0, 0x35, 0x7c, 0xdd, 0x0e, 0x24, 0x3f, 0xe6, 0x72, 0xda, 0x61,
	0xb1, 0x64, 0xd9, 0x39, 0xef, 0x9b, 0x50, 0xe4, 0xa1, 0x76, 0x6f, 0xdd, 0xc3, 0xa3, 0xbb, 0xa3,
	0x9b, 0xca, 0xb2, 0x84, 0x76, 0x10, 0x30, 0xcc, 0xde, 0x0b, 0x4b, 0xe9, 0xea, 0x24, 0x5f, 0x96,
	0xb2, 0xc3, 0xc5, 0x98, 0x0b, 0xf1, 0x07, 0xc4, 0x7c, 0x67, 0x41, 0x1d, 0xe5, 0x6c, 0x27, 0xc9,
	0x68, 0x4c, 0xb3, 0xd1, 0xea, 0x87, 0x93, 0x2c, 0x32, 0x6e, 0xc0, 0xe3, 0x7c, 0xeb, 0x28, 0x2e,
	0xb6, 0x0e, 0x72, 0x0b, 0xaa, 0xaa, 0xdd, 0xfa, 0xc8, 0xab, 0xab, 0xc2, 0x56, 0xc0, 0x41, 0x16,
	0xe5, 0x87, 0xca, 0xda, 0xf2, 0x50, 0xb9, 0x03, 0x10, 0xb2, 0x88, 0xe1, 0x70, 0xa6, 0x52, 0x55,
	0x45, 0xc9, 0xab, 0x1a, 0xa4, 0x2d, 0xdd, 0xe7, 0x3a, 0xf9, 0x3b, 0x11, 0xa3, 0xd9, 0x33, 0x2e,
	0x64, 0x92, 0x4d, 0xf3, 0x35, 0x66, 0x2d, 0xd5, 0xd8, 0x1d, 0x80, 0x00, 0x19, 0xb5, 0xac, 0x82,
	0x96, 0x65, 0x90, 0xb6, 0x74, 0x7f, 0xb2, 0x80, 0xa0, 0xb0, 0x3d, 0x3d, 0x08, 0xf6, 0x78, 0x20,
	0x27, 0xd9, 0x62, 0x85, 0xb2, 0x72, 0xc6, 0x38, 0x50, 0x49, 0xe9, 0x34, 0x4a, 0xe8, 0xac, 0x29,
	0xcf, 0x48, 0x74, 0xd1, 0x3b, 0x1e, 0xca, 0xa1, 0xb2, 0xbd, 0xe1, 0x69, 0x02, 0x9b, 0xed, 0x90,
	0xf1, 0xc1, 0x50, 0x2a, 0xcb, 0x1b, 0x9e, 0xa1, 0xd0, 0x29, 0x6a, 0x10, 0x09, 0xfe, 0x9e, 0x29,
	0xcb, 0x1b, 0x9e, 0x8d, 0xc0, 0x3e, 0x7f, 0xcf, 0x70, 0x50, 0x65, 0x0c, 0x6f, 0x7c, 0x49, 0xb3,
	0x01, 0xd3, 0xd6, 0x37, 0xbc, 0xba, 0x06, 0xfb, 0x0a, 0x5b, 0x84, 0xa4, 0x92, 0x0b, 0x89, 0x3b,
	0x84, 0x2b, 0xa7, 0x2d, 0x11, 0xe8, 0x99, 0x11, 0x9b, 0xfa, 0x93, 0x85, 0x67, 0x46, 0x6c, 0x7a,
	0xc0, 0x43, 0xf2, 0x5f, 0xb0, 0x53, 0xc3, 0x64, 0x8a, 0xfd, 0xf6, 0x72, 0x9d, 0x2d, 0x4b, 0xf2,
	0xe6, 0xdc, 0xee, 0x0f, 0x05, 0xb8, 0x8c, 0x0c, 0x6f, 0x69, 0x14, 0x31, 0x79, 0xfe, 0xe4, 0x75,
	0xa0, 0x42, 0xc3, 0x30, 0x63, 0x42, 0xcc, 0xbc, 0x66, 0x48, 0xf4, 0xcf, 0x3b, 0x25, 0x40, 0xb9,
	0xcd, 0xf6, 0x0c, 0x85, 0xbe, 0xc7, 0xd8, 0x29, 0xaf, 0xd9, 0x9e, 0x3a, 0x23, 0xa6, 0x96, 0x5d,
	0xdd, 0x3f, 0xd5, 0x19, 0x25, 0x63, 0xec, 0x71, 0x9a, 0x97, 0x75, 0xc3, 0x35, 0x24, 0x72, 0xa7,
	0x54, 0x0e, 0xcd, 0x46, 0xa4, 0xce, 0x38, 0x22, 0xe6, 0x2d, 0xdc, 0xb1, 0x95, 0x26, 0xb9, 0x9e,
	0x3e, 0x8b, 0x77, 0x35, 0x17, 0x6f, 0xb4, 0x27, 0x89, 0x92, 0x4c, 0x0d, 0x94, 0xaa, 0xa7, 0x09,
	0x15, 0x55, 0x1e, 0x86, 0x2c, 0x36, 0x1b, 0x92, 0xa1, 0x56, 0xaf, 0x48, 0xee, 0x2b, 0x9d, 0x61,
	0x4b, 0xce, 0x12, 0xe4, 0x11, 0xd8, 0xa6, 0xe7, 0xcd, 0xba, 0xf5, 0xad, 0x65, 0xef, 0x2f, 0xf1,
	0x7b, 0x73, 0x66, 0xf7, 0x5b, 0x0b, 0xfe, 0x7e, 0xe6, 0x3c, 0x5c, 0x11, 0x80, 0x93, 0x43, 0x46,
	0x97, 0xec, 0xd2, 0x90, 0xe9, 0xc2, 0xc6, 0x50, 0xd7, 0x91, 0x4f, 0xb3, 0x60, 0xc8, 0x8f, 0x99,
	0x2f, 0x26, 0x69, 0x9a, 0x64, 0xd2, 0x67, 0x31, 0x3d, 0x8c, 0xcc, 0x2e, 0x64, 0x7b, 0xb7, 0x0d,
	0x5b, 0x5b, 0x73, 0xed, 0x6b, 0xa6, 0xae, 0xe6, 0x71, 0x7f, 0xb4, 0x74, 0x07, 0xee, 0xe3, 0xa6,
	0x86, 0xbb, 0x1f, 0xcb, 0x2e, 0xf8, 0xdf, 0xe2, 0x09, 0x94, 0xcd, 0xb2, 0x87, 0xdf, 0x59, 0x3f,
	0xb9, 0x43, 0xe4, 0x04, 0x6e, 0xf5, 0x17, 0x6b, 0xa0, 0x67, 0x1e, 0xb9, 0xff, 0x87, 0x5a, 0x0e,
	0x26, 0x35, 0xa8, 0x1c, 0xf4, 0x5e, 0xf4, 0x5e, 0xbf, 0xed, 0x35, 0xff, 0x86, 0x44, 0xdf, 0x3b,
	0xd8, 0xef, 0x77, 0x77, 0x9a, 0x16, 0xb9, 0x0c, 0x8d, 0x83, 0x9e, 0x22, 0xdf, 0xbe, 0xf6, 0xfa,
	0xcf, 0x3e, 0x6b, 0x16, 0xdc, 0xaf, 0x8b, 0x7a, 0x97, 0x7c, 0x93, 0x5b, 0x44, 0xcd, 0x7e, 0xb0,
	0x42, 0x79, 0x02, 0xa5, 0xa3, 0x2c, 0x19, 0x1b, 0xf5, 0xd5, 0x19, 0x0d, 0x92, 0x89, 0x69, 0x7d,
	0x05, 0x99, 0x60, 0xb6, 0x05, 0x43, 0x0c, 0x60, 0x3c, 0x98, 0xad, 0x03, 0x0b, 0x00, 0x43, 0x62,
	0xb6, 0x1f, 0xdd, 0x95, 0xcc, 0xfe, 0x3f, 0xc7, 0xda, 0x12, 0x37, 0xb2, 0x8c, 0x89, 0x34, 0x89,
	0xc5, 0x2c, 0xbb, 0xe7, 0x34, 0xb6, 0xb4, 0x8c, 0xa5, 0x11, 0xd7, 0x8f, 0x75, 0x0f, 0xa8, 0x1a,
	0xa4, 0x2d, 0x09, 0x3b, 0x7b, 0xe1, 0xb6, 0x95, 0x67, 0xff, 0xb3, 0xec, 0xd9, 0x33, 0xac, 0xde,
	0x7a, 0x73, 0x6a, 0x25, 0x3f, 0x6b, 0x4d, 0x77, 0x3f, 0x05, 0x72, 0x9a, 0xf3, 0x94, 0xef, 0xf7,
	0xba, 0xbd, 0x9d, 0xdd, 0xde, 0xd3, 0xa6, 0x45, 0xea, 0x60, 0xb7, 0x3b, 0x9d, 0xee, 0x1e, 0x46,
	0xa2, 0x80, 0xd4, 0x4e, 0xb7, 0xf3, 0x72, 0xb7, 0xd7, 0xdd, 0x69, 0x16, 0x91, 0xea, 0xb4, 0x7b,
	0x9d, 0xee, 0xcb, 0xee, 0x4e, 0xb3, 0xb4, 0xdd, 0xf8, 0xbc, 0xb6, 0xf5, 0xe0, 0xf1, 0x4c, 0xcf,
	0xc3, 0xb2, 0x3a, 0xfd, 0xfb, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xac, 0x00, 0x9e, 0x9c, 0x12,
	0x10, 0x00, 0x00,
}
