// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pairing.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Backup struct {
	Clock                uint64                       `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Id                   string                       `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Contacts             []*SyncInstallationContactV2 `protobuf:"bytes,3,rep,name=contacts,proto3" json:"contacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *Backup) Reset()         { *m = Backup{} }
func (m *Backup) String() string { return proto.CompactTextString(m) }
func (*Backup) ProtoMessage()    {}
func (*Backup) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{0}
}

func (m *Backup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Backup.Unmarshal(m, b)
}
func (m *Backup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Backup.Marshal(b, m, deterministic)
}
func (m *Backup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Backup.Merge(m, src)
}
func (m *Backup) XXX_Size() int {
	return xxx_messageInfo_Backup.Size(m)
}
func (m *Backup) XXX_DiscardUnknown() {
	xxx_messageInfo_Backup.DiscardUnknown(m)
}

var xxx_messageInfo_Backup proto.InternalMessageInfo

func (m *Backup) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *Backup) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Backup) GetContacts() []*SyncInstallationContactV2 {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type PairInstallation struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	InstallationId       string   `protobuf:"bytes,2,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	DeviceType           string   `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PairInstallation) Reset()         { *m = PairInstallation{} }
func (m *PairInstallation) String() string { return proto.CompactTextString(m) }
func (*PairInstallation) ProtoMessage()    {}
func (*PairInstallation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{1}
}

func (m *PairInstallation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairInstallation.Unmarshal(m, b)
}
func (m *PairInstallation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairInstallation.Marshal(b, m, deterministic)
}
func (m *PairInstallation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairInstallation.Merge(m, src)
}
func (m *PairInstallation) XXX_Size() int {
	return xxx_messageInfo_PairInstallation.Size(m)
}
func (m *PairInstallation) XXX_DiscardUnknown() {
	xxx_messageInfo_PairInstallation.DiscardUnknown(m)
}

var xxx_messageInfo_PairInstallation proto.InternalMessageInfo

func (m *PairInstallation) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *PairInstallation) GetInstallationId() string {
	if m != nil {
		return m.InstallationId
	}
	return ""
}

func (m *PairInstallation) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *PairInstallation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SyncInstallationContact struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ProfileImage         string   `protobuf:"bytes,3,opt,name=profile_image,json=profileImage,proto3" json:"profile_image,omitempty"`
	EnsName              string   `protobuf:"bytes,4,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	LastUpdated          uint64   `protobuf:"varint,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	SystemTags           []string `protobuf:"bytes,6,rep,name=system_tags,json=systemTags,proto3" json:"system_tags,omitempty"`
	LocalNickname        string   `protobuf:"bytes,7,opt,name=local_nickname,json=localNickname,proto3" json:"local_nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncInstallationContact) Reset()         { *m = SyncInstallationContact{} }
func (m *SyncInstallationContact) String() string { return proto.CompactTextString(m) }
func (*SyncInstallationContact) ProtoMessage()    {}
func (*SyncInstallationContact) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{2}
}

func (m *SyncInstallationContact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncInstallationContact.Unmarshal(m, b)
}
func (m *SyncInstallationContact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncInstallationContact.Marshal(b, m, deterministic)
}
func (m *SyncInstallationContact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInstallationContact.Merge(m, src)
}
func (m *SyncInstallationContact) XXX_Size() int {
	return xxx_messageInfo_SyncInstallationContact.Size(m)
}
func (m *SyncInstallationContact) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInstallationContact.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInstallationContact proto.InternalMessageInfo

func (m *SyncInstallationContact) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncInstallationContact) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SyncInstallationContact) GetProfileImage() string {
	if m != nil {
		return m.ProfileImage
	}
	return ""
}

func (m *SyncInstallationContact) GetEnsName() string {
	if m != nil {
		return m.EnsName
	}
	return ""
}

func (m *SyncInstallationContact) GetLastUpdated() uint64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func (m *SyncInstallationContact) GetSystemTags() []string {
	if m != nil {
		return m.SystemTags
	}
	return nil
}

func (m *SyncInstallationContact) GetLocalNickname() string {
	if m != nil {
		return m.LocalNickname
	}
	return ""
}

type SyncInstallationContactV2 struct {
	LastUpdatedLocally   uint64   `protobuf:"varint,1,opt,name=last_updated_locally,json=lastUpdatedLocally,proto3" json:"last_updated_locally,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ProfileImage         string   `protobuf:"bytes,3,opt,name=profile_image,json=profileImage,proto3" json:"profile_image,omitempty"`
	EnsName              string   `protobuf:"bytes,4,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	LastUpdated          uint64   `protobuf:"varint,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	SystemTags           []string `protobuf:"bytes,6,rep,name=system_tags,json=systemTags,proto3" json:"system_tags,omitempty"`
	LocalNickname        string   `protobuf:"bytes,7,opt,name=local_nickname,json=localNickname,proto3" json:"local_nickname,omitempty"`
	Added                bool     `protobuf:"varint,9,opt,name=added,proto3" json:"added,omitempty"`
	Blocked              bool     `protobuf:"varint,10,opt,name=blocked,proto3" json:"blocked,omitempty"`
	Muted                bool     `protobuf:"varint,11,opt,name=muted,proto3" json:"muted,omitempty"`
	Removed              bool     `protobuf:"varint,12,opt,name=removed,proto3" json:"removed,omitempty"`
	HasAddedUs           bool     `protobuf:"varint,13,opt,name=has_added_us,json=hasAddedUs,proto3" json:"has_added_us,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncInstallationContactV2) Reset()         { *m = SyncInstallationContactV2{} }
func (m *SyncInstallationContactV2) String() string { return proto.CompactTextString(m) }
func (*SyncInstallationContactV2) ProtoMessage()    {}
func (*SyncInstallationContactV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{3}
}

func (m *SyncInstallationContactV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncInstallationContactV2.Unmarshal(m, b)
}
func (m *SyncInstallationContactV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncInstallationContactV2.Marshal(b, m, deterministic)
}
func (m *SyncInstallationContactV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInstallationContactV2.Merge(m, src)
}
func (m *SyncInstallationContactV2) XXX_Size() int {
	return xxx_messageInfo_SyncInstallationContactV2.Size(m)
}
func (m *SyncInstallationContactV2) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInstallationContactV2.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInstallationContactV2 proto.InternalMessageInfo

func (m *SyncInstallationContactV2) GetLastUpdatedLocally() uint64 {
	if m != nil {
		return m.LastUpdatedLocally
	}
	return 0
}

func (m *SyncInstallationContactV2) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SyncInstallationContactV2) GetProfileImage() string {
	if m != nil {
		return m.ProfileImage
	}
	return ""
}

func (m *SyncInstallationContactV2) GetEnsName() string {
	if m != nil {
		return m.EnsName
	}
	return ""
}

func (m *SyncInstallationContactV2) GetLastUpdated() uint64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func (m *SyncInstallationContactV2) GetSystemTags() []string {
	if m != nil {
		return m.SystemTags
	}
	return nil
}

func (m *SyncInstallationContactV2) GetLocalNickname() string {
	if m != nil {
		return m.LocalNickname
	}
	return ""
}

func (m *SyncInstallationContactV2) GetAdded() bool {
	if m != nil {
		return m.Added
	}
	return false
}

func (m *SyncInstallationContactV2) GetBlocked() bool {
	if m != nil {
		return m.Blocked
	}
	return false
}

func (m *SyncInstallationContactV2) GetMuted() bool {
	if m != nil {
		return m.Muted
	}
	return false
}

func (m *SyncInstallationContactV2) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

func (m *SyncInstallationContactV2) GetHasAddedUs() bool {
	if m != nil {
		return m.HasAddedUs
	}
	return false
}

type SyncInstallationAccount struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	ProfileImage         string   `protobuf:"bytes,2,opt,name=profile_image,json=profileImage,proto3" json:"profile_image,omitempty"`
	LastUpdated          uint64   `protobuf:"varint,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncInstallationAccount) Reset()         { *m = SyncInstallationAccount{} }
func (m *SyncInstallationAccount) String() string { return proto.CompactTextString(m) }
func (*SyncInstallationAccount) ProtoMessage()    {}
func (*SyncInstallationAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{4}
}

func (m *SyncInstallationAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncInstallationAccount.Unmarshal(m, b)
}
func (m *SyncInstallationAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncInstallationAccount.Marshal(b, m, deterministic)
}
func (m *SyncInstallationAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInstallationAccount.Merge(m, src)
}
func (m *SyncInstallationAccount) XXX_Size() int {
	return xxx_messageInfo_SyncInstallationAccount.Size(m)
}
func (m *SyncInstallationAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInstallationAccount.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInstallationAccount proto.InternalMessageInfo

func (m *SyncInstallationAccount) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncInstallationAccount) GetProfileImage() string {
	if m != nil {
		return m.ProfileImage
	}
	return ""
}

func (m *SyncInstallationAccount) GetLastUpdated() uint64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

type SyncInstallationPublicChat struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncInstallationPublicChat) Reset()         { *m = SyncInstallationPublicChat{} }
func (m *SyncInstallationPublicChat) String() string { return proto.CompactTextString(m) }
func (*SyncInstallationPublicChat) ProtoMessage()    {}
func (*SyncInstallationPublicChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{5}
}

func (m *SyncInstallationPublicChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncInstallationPublicChat.Unmarshal(m, b)
}
func (m *SyncInstallationPublicChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncInstallationPublicChat.Marshal(b, m, deterministic)
}
func (m *SyncInstallationPublicChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInstallationPublicChat.Merge(m, src)
}
func (m *SyncInstallationPublicChat) XXX_Size() int {
	return xxx_messageInfo_SyncInstallationPublicChat.Size(m)
}
func (m *SyncInstallationPublicChat) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInstallationPublicChat.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInstallationPublicChat proto.InternalMessageInfo

func (m *SyncInstallationPublicChat) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncInstallationPublicChat) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SyncCommunity struct {
	Clock                uint64                         `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Id                   []byte                         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	PrivateKey           []byte                         `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Description          []byte                         `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Joined               bool                           `protobuf:"varint,5,opt,name=joined,proto3" json:"joined,omitempty"`
	Verified             bool                           `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"`
	Muted                bool                           `protobuf:"varint,7,opt,name=muted,proto3" json:"muted,omitempty"`
	RequestsToJoin       []*SyncCommunityRequestsToJoin `protobuf:"bytes,8,rep,name=requests_to_join,json=requestsToJoin,proto3" json:"requests_to_join,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SyncCommunity) Reset()         { *m = SyncCommunity{} }
func (m *SyncCommunity) String() string { return proto.CompactTextString(m) }
func (*SyncCommunity) ProtoMessage()    {}
func (*SyncCommunity) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{6}
}

func (m *SyncCommunity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncCommunity.Unmarshal(m, b)
}
func (m *SyncCommunity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncCommunity.Marshal(b, m, deterministic)
}
func (m *SyncCommunity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncCommunity.Merge(m, src)
}
func (m *SyncCommunity) XXX_Size() int {
	return xxx_messageInfo_SyncCommunity.Size(m)
}
func (m *SyncCommunity) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncCommunity.DiscardUnknown(m)
}

var xxx_messageInfo_SyncCommunity proto.InternalMessageInfo

func (m *SyncCommunity) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncCommunity) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SyncCommunity) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *SyncCommunity) GetDescription() []byte {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *SyncCommunity) GetJoined() bool {
	if m != nil {
		return m.Joined
	}
	return false
}

func (m *SyncCommunity) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *SyncCommunity) GetMuted() bool {
	if m != nil {
		return m.Muted
	}
	return false
}

func (m *SyncCommunity) GetRequestsToJoin() []*SyncCommunityRequestsToJoin {
	if m != nil {
		return m.RequestsToJoin
	}
	return nil
}

type SyncCommunityRequestsToJoin struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Clock                uint64   `protobuf:"varint,3,opt,name=clock,proto3" json:"clock,omitempty"`
	EnsName              string   `protobuf:"bytes,4,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	ChatId               string   `protobuf:"bytes,5,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	CommunityId          []byte   `protobuf:"bytes,6,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	State                uint64   `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncCommunityRequestsToJoin) Reset()         { *m = SyncCommunityRequestsToJoin{} }
func (m *SyncCommunityRequestsToJoin) String() string { return proto.CompactTextString(m) }
func (*SyncCommunityRequestsToJoin) ProtoMessage()    {}
func (*SyncCommunityRequestsToJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{7}
}

func (m *SyncCommunityRequestsToJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncCommunityRequestsToJoin.Unmarshal(m, b)
}
func (m *SyncCommunityRequestsToJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncCommunityRequestsToJoin.Marshal(b, m, deterministic)
}
func (m *SyncCommunityRequestsToJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncCommunityRequestsToJoin.Merge(m, src)
}
func (m *SyncCommunityRequestsToJoin) XXX_Size() int {
	return xxx_messageInfo_SyncCommunityRequestsToJoin.Size(m)
}
func (m *SyncCommunityRequestsToJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncCommunityRequestsToJoin.DiscardUnknown(m)
}

var xxx_messageInfo_SyncCommunityRequestsToJoin proto.InternalMessageInfo

func (m *SyncCommunityRequestsToJoin) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SyncCommunityRequestsToJoin) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *SyncCommunityRequestsToJoin) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncCommunityRequestsToJoin) GetEnsName() string {
	if m != nil {
		return m.EnsName
	}
	return ""
}

func (m *SyncCommunityRequestsToJoin) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *SyncCommunityRequestsToJoin) GetCommunityId() []byte {
	if m != nil {
		return m.CommunityId
	}
	return nil
}

func (m *SyncCommunityRequestsToJoin) GetState() uint64 {
	if m != nil {
		return m.State
	}
	return 0
}

type SyncInstallation struct {
	Contacts             []*SyncInstallationContact    `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	PublicChats          []*SyncInstallationPublicChat `protobuf:"bytes,2,rep,name=public_chats,json=publicChats,proto3" json:"public_chats,omitempty"`
	Account              *SyncInstallationAccount      `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Communities          []*SyncCommunity              `protobuf:"bytes,4,rep,name=communities,proto3" json:"communities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SyncInstallation) Reset()         { *m = SyncInstallation{} }
func (m *SyncInstallation) String() string { return proto.CompactTextString(m) }
func (*SyncInstallation) ProtoMessage()    {}
func (*SyncInstallation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{8}
}

func (m *SyncInstallation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncInstallation.Unmarshal(m, b)
}
func (m *SyncInstallation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncInstallation.Marshal(b, m, deterministic)
}
func (m *SyncInstallation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInstallation.Merge(m, src)
}
func (m *SyncInstallation) XXX_Size() int {
	return xxx_messageInfo_SyncInstallation.Size(m)
}
func (m *SyncInstallation) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInstallation.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInstallation proto.InternalMessageInfo

func (m *SyncInstallation) GetContacts() []*SyncInstallationContact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *SyncInstallation) GetPublicChats() []*SyncInstallationPublicChat {
	if m != nil {
		return m.PublicChats
	}
	return nil
}

func (m *SyncInstallation) GetAccount() *SyncInstallationAccount {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *SyncInstallation) GetCommunities() []*SyncCommunity {
	if m != nil {
		return m.Communities
	}
	return nil
}

type SyncChatRemoved struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncChatRemoved) Reset()         { *m = SyncChatRemoved{} }
func (m *SyncChatRemoved) String() string { return proto.CompactTextString(m) }
func (*SyncChatRemoved) ProtoMessage()    {}
func (*SyncChatRemoved) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{9}
}

func (m *SyncChatRemoved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncChatRemoved.Unmarshal(m, b)
}
func (m *SyncChatRemoved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncChatRemoved.Marshal(b, m, deterministic)
}
func (m *SyncChatRemoved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncChatRemoved.Merge(m, src)
}
func (m *SyncChatRemoved) XXX_Size() int {
	return xxx_messageInfo_SyncChatRemoved.Size(m)
}
func (m *SyncChatRemoved) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncChatRemoved.DiscardUnknown(m)
}

var xxx_messageInfo_SyncChatRemoved proto.InternalMessageInfo

func (m *SyncChatRemoved) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncChatRemoved) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SyncChatMessagesRead struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncChatMessagesRead) Reset()         { *m = SyncChatMessagesRead{} }
func (m *SyncChatMessagesRead) String() string { return proto.CompactTextString(m) }
func (*SyncChatMessagesRead) ProtoMessage()    {}
func (*SyncChatMessagesRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{10}
}

func (m *SyncChatMessagesRead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncChatMessagesRead.Unmarshal(m, b)
}
func (m *SyncChatMessagesRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncChatMessagesRead.Marshal(b, m, deterministic)
}
func (m *SyncChatMessagesRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncChatMessagesRead.Merge(m, src)
}
func (m *SyncChatMessagesRead) XXX_Size() int {
	return xxx_messageInfo_SyncChatMessagesRead.Size(m)
}
func (m *SyncChatMessagesRead) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncChatMessagesRead.DiscardUnknown(m)
}

var xxx_messageInfo_SyncChatMessagesRead proto.InternalMessageInfo

func (m *SyncChatMessagesRead) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncChatMessagesRead) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SyncActivityCenterRead struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Ids                  [][]byte `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncActivityCenterRead) Reset()         { *m = SyncActivityCenterRead{} }
func (m *SyncActivityCenterRead) String() string { return proto.CompactTextString(m) }
func (*SyncActivityCenterRead) ProtoMessage()    {}
func (*SyncActivityCenterRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{11}
}

func (m *SyncActivityCenterRead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncActivityCenterRead.Unmarshal(m, b)
}
func (m *SyncActivityCenterRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncActivityCenterRead.Marshal(b, m, deterministic)
}
func (m *SyncActivityCenterRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncActivityCenterRead.Merge(m, src)
}
func (m *SyncActivityCenterRead) XXX_Size() int {
	return xxx_messageInfo_SyncActivityCenterRead.Size(m)
}
func (m *SyncActivityCenterRead) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncActivityCenterRead.DiscardUnknown(m)
}

var xxx_messageInfo_SyncActivityCenterRead proto.InternalMessageInfo

func (m *SyncActivityCenterRead) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncActivityCenterRead) GetIds() [][]byte {
	if m != nil {
		return m.Ids
	}
	return nil
}

type SyncActivityCenterAccepted struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Ids                  [][]byte `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncActivityCenterAccepted) Reset()         { *m = SyncActivityCenterAccepted{} }
func (m *SyncActivityCenterAccepted) String() string { return proto.CompactTextString(m) }
func (*SyncActivityCenterAccepted) ProtoMessage()    {}
func (*SyncActivityCenterAccepted) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{12}
}

func (m *SyncActivityCenterAccepted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncActivityCenterAccepted.Unmarshal(m, b)
}
func (m *SyncActivityCenterAccepted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncActivityCenterAccepted.Marshal(b, m, deterministic)
}
func (m *SyncActivityCenterAccepted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncActivityCenterAccepted.Merge(m, src)
}
func (m *SyncActivityCenterAccepted) XXX_Size() int {
	return xxx_messageInfo_SyncActivityCenterAccepted.Size(m)
}
func (m *SyncActivityCenterAccepted) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncActivityCenterAccepted.DiscardUnknown(m)
}

var xxx_messageInfo_SyncActivityCenterAccepted proto.InternalMessageInfo

func (m *SyncActivityCenterAccepted) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncActivityCenterAccepted) GetIds() [][]byte {
	if m != nil {
		return m.Ids
	}
	return nil
}

type SyncActivityCenterDismissed struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Ids                  [][]byte `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncActivityCenterDismissed) Reset()         { *m = SyncActivityCenterDismissed{} }
func (m *SyncActivityCenterDismissed) String() string { return proto.CompactTextString(m) }
func (*SyncActivityCenterDismissed) ProtoMessage()    {}
func (*SyncActivityCenterDismissed) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{13}
}

func (m *SyncActivityCenterDismissed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncActivityCenterDismissed.Unmarshal(m, b)
}
func (m *SyncActivityCenterDismissed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncActivityCenterDismissed.Marshal(b, m, deterministic)
}
func (m *SyncActivityCenterDismissed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncActivityCenterDismissed.Merge(m, src)
}
func (m *SyncActivityCenterDismissed) XXX_Size() int {
	return xxx_messageInfo_SyncActivityCenterDismissed.Size(m)
}
func (m *SyncActivityCenterDismissed) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncActivityCenterDismissed.DiscardUnknown(m)
}

var xxx_messageInfo_SyncActivityCenterDismissed proto.InternalMessageInfo

func (m *SyncActivityCenterDismissed) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *SyncActivityCenterDismissed) GetIds() [][]byte {
	if m != nil {
		return m.Ids
	}
	return nil
}

type SyncClearHistory struct {
	ChatId               string   `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ClearedAt            uint64   `protobuf:"varint,2,opt,name=cleared_at,json=clearedAt,proto3" json:"cleared_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncClearHistory) Reset()         { *m = SyncClearHistory{} }
func (m *SyncClearHistory) String() string { return proto.CompactTextString(m) }
func (*SyncClearHistory) ProtoMessage()    {}
func (*SyncClearHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_d61ab7221f0b5518, []int{14}
}

func (m *SyncClearHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncClearHistory.Unmarshal(m, b)
}
func (m *SyncClearHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncClearHistory.Marshal(b, m, deterministic)
}
func (m *SyncClearHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncClearHistory.Merge(m, src)
}
func (m *SyncClearHistory) XXX_Size() int {
	return xxx_messageInfo_SyncClearHistory.Size(m)
}
func (m *SyncClearHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncClearHistory.DiscardUnknown(m)
}

var xxx_messageInfo_SyncClearHistory proto.InternalMessageInfo

func (m *SyncClearHistory) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *SyncClearHistory) GetClearedAt() uint64 {
	if m != nil {
		return m.ClearedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Backup)(nil), "protobuf.Backup")
	proto.RegisterType((*PairInstallation)(nil), "protobuf.PairInstallation")
	proto.RegisterType((*SyncInstallationContact)(nil), "protobuf.SyncInstallationContact")
	proto.RegisterType((*SyncInstallationContactV2)(nil), "protobuf.SyncInstallationContactV2")
	proto.RegisterType((*SyncInstallationAccount)(nil), "protobuf.SyncInstallationAccount")
	proto.RegisterType((*SyncInstallationPublicChat)(nil), "protobuf.SyncInstallationPublicChat")
	proto.RegisterType((*SyncCommunity)(nil), "protobuf.SyncCommunity")
	proto.RegisterType((*SyncCommunityRequestsToJoin)(nil), "protobuf.SyncCommunityRequestsToJoin")
	proto.RegisterType((*SyncInstallation)(nil), "protobuf.SyncInstallation")
	proto.RegisterType((*SyncChatRemoved)(nil), "protobuf.SyncChatRemoved")
	proto.RegisterType((*SyncChatMessagesRead)(nil), "protobuf.SyncChatMessagesRead")
	proto.RegisterType((*SyncActivityCenterRead)(nil), "protobuf.SyncActivityCenterRead")
	proto.RegisterType((*SyncActivityCenterAccepted)(nil), "protobuf.SyncActivityCenterAccepted")
	proto.RegisterType((*SyncActivityCenterDismissed)(nil), "protobuf.SyncActivityCenterDismissed")
	proto.RegisterType((*SyncClearHistory)(nil), "protobuf.SyncClearHistory")
}

func init() {
	proto.RegisterFile("pairing.proto", fileDescriptor_d61ab7221f0b5518)
}

var fileDescriptor_d61ab7221f0b5518 = []byte{
	// 850 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0x4f, 0x73, 0xdb, 0x44,
	0x14, 0x1f, 0xd9, 0x8e, 0xed, 0x3c, 0xcb, 0x69, 0x66, 0x27, 0xd3, 0x6c, 0xcb, 0x74, 0xea, 0xaa,
	0x74, 0xc8, 0x29, 0x30, 0xe5, 0xc0, 0x30, 0x85, 0x01, 0xc7, 0x65, 0xc0, 0x05, 0x4a, 0x47, 0xa4,
	0x1c, 0xb8, 0x68, 0x36, 0xab, 0x17, 0x67, 0x89, 0xa4, 0x15, 0xda, 0x95, 0x19, 0x7d, 0x01, 0x0e,
	0x1c, 0xe1, 0x83, 0xf1, 0x3d, 0xf8, 0x14, 0xcc, 0xee, 0xca, 0x8a, 0x9c, 0xe0, 0xc4, 0x1c, 0x7b,
	0x92, 0xde, 0x6f, 0xdf, 0xbf, 0xfd, 0xbd, 0xdf, 0x5b, 0x18, 0xe7, 0x4c, 0x14, 0x22, 0x5b, 0x1c,
	0xe7, 0x85, 0xd4, 0x92, 0x0c, 0xed, 0xe7, 0xac, 0x3c, 0x0f, 0x24, 0xf4, 0x4f, 0x18, 0xbf, 0x2c,
	0x73, 0x72, 0x00, 0x3b, 0x3c, 0x91, 0xfc, 0x92, 0x7a, 0x13, 0xef, 0xa8, 0x17, 0x3a, 0x83, 0xec,
	0x41, 0x47, 0xc4, 0xb4, 0x33, 0xf1, 0x8e, 0x76, 0xc3, 0x8e, 0x88, 0xc9, 0x17, 0x30, 0xe4, 0x32,
	0xd3, 0x8c, 0x6b, 0x45, 0xbb, 0x93, 0xee, 0xd1, 0xe8, 0xf9, 0xd3, 0xe3, 0x55, 0xb2, 0xe3, 0x1f,
	0xab, 0x8c, 0xcf, 0x33, 0xa5, 0x59, 0x92, 0x30, 0x2d, 0x64, 0x36, 0x73, 0x9e, 0x3f, 0x3d, 0x0f,
	0x9b, 0xa0, 0xe0, 0x77, 0x0f, 0xf6, 0xdf, 0x30, 0x51, 0xb4, 0xfd, 0x36, 0xd4, 0xfe, 0x00, 0xee,
	0x89, 0x96, 0x57, 0xd4, 0x34, 0xb2, 0xd7, 0x86, 0xe7, 0x31, 0x79, 0x0c, 0xa3, 0x18, 0x97, 0x82,
	0x63, 0xa4, 0xab, 0x1c, 0x69, 0xd7, 0x3a, 0x81, 0x83, 0x4e, 0xab, 0x1c, 0x09, 0x81, 0x5e, 0xc6,
	0x52, 0xa4, 0x3d, 0x7b, 0x62, 0xff, 0x83, 0x7f, 0x3c, 0x38, 0xdc, 0xd0, 0xf0, 0x96, 0x5c, 0x3c,
	0x85, 0x71, 0x5e, 0xc8, 0x73, 0x91, 0x60, 0x24, 0x52, 0xb6, 0x58, 0x15, 0xf6, 0x6b, 0x70, 0x6e,
	0x30, 0xf2, 0x00, 0x86, 0x98, 0xa9, 0xa8, 0x55, 0x7e, 0x80, 0x99, 0x7a, 0xcd, 0x52, 0x24, 0x4f,
	0xc0, 0x4f, 0x98, 0xd2, 0x51, 0x99, 0xc7, 0x4c, 0x63, 0x4c, 0x77, 0x6c, 0xb1, 0x91, 0xc1, 0xde,
	0x3a, 0xc8, 0xdc, 0x4c, 0x55, 0x4a, 0x63, 0x1a, 0x69, 0xb6, 0x50, 0xb4, 0x3f, 0xe9, 0x9a, 0x9b,
	0x39, 0xe8, 0x94, 0x2d, 0x14, 0x79, 0x06, 0x7b, 0x89, 0xe4, 0x2c, 0x89, 0x32, 0xc1, 0x2f, 0x6d,
	0x91, 0x81, 0x2d, 0x32, 0xb6, 0xe8, 0xeb, 0x1a, 0x0c, 0xfe, 0xe8, 0xc2, 0x83, 0x8d, 0xd3, 0x21,
	0x1f, 0xc1, 0x41, 0xbb, 0x91, 0xc8, 0xc6, 0x26, 0x55, 0x7d, 0x7b, 0xd2, 0x6a, 0xe8, 0x3b, 0x77,
	0xf2, 0x0e, 0x53, 0x61, 0x66, 0xcb, 0xe2, 0x18, 0x63, 0xba, 0x3b, 0xf1, 0x8e, 0x86, 0xa1, 0x33,
	0x08, 0x85, 0xc1, 0x99, 0x19, 0x32, 0xc6, 0x14, 0x2c, 0xbe, 0x32, 0x8d, 0x7f, 0x5a, 0x9a, 0x9e,
	0x46, 0xce, 0xdf, 0x1a, 0xc6, 0xbf, 0xc0, 0x54, 0x2e, 0x31, 0xa6, 0xbe, 0xf3, 0xaf, 0x4d, 0x32,
	0x01, 0xff, 0x82, 0xa9, 0xc8, 0xa6, 0x8d, 0x4a, 0x45, 0xc7, 0xf6, 0x18, 0x2e, 0x98, 0x9a, 0x1a,
	0xe8, 0xad, 0x0a, 0x7e, 0xbb, 0x29, 0xbc, 0x29, 0xe7, 0xb2, 0xcc, 0x36, 0x09, 0xef, 0x06, 0xbb,
	0x9d, 0xff, 0x60, 0xf7, 0x3a, 0x85, 0xdd, 0x1b, 0x14, 0x06, 0x27, 0xf0, 0xf0, 0x7a, 0xe1, 0x37,
	0xe5, 0x59, 0x22, 0xf8, 0xec, 0x82, 0x6d, 0x29, 0xfa, 0xe0, 0xaf, 0x0e, 0x8c, 0x4d, 0x92, 0x99,
	0x4c, 0xd3, 0x32, 0x13, 0xba, 0xba, 0x33, 0xce, 0xb7, 0x0a, 0x79, 0x0c, 0xa3, 0xbc, 0x10, 0x4b,
	0xa6, 0x31, 0xba, 0xc4, 0xca, 0x76, 0xe7, 0x87, 0x50, 0x43, 0xdf, 0x62, 0x45, 0x26, 0x66, 0x89,
	0x15, 0x2f, 0x44, 0x6e, 0xfa, 0xb2, 0x02, 0xf1, 0xc3, 0x36, 0x44, 0xee, 0x43, 0xff, 0x17, 0x29,
	0xb2, 0x5a, 0x1e, 0xc3, 0xb0, 0xb6, 0xc8, 0x43, 0x18, 0x2e, 0xb1, 0x10, 0xe7, 0x02, 0x63, 0xda,
	0xb7, 0x27, 0x8d, 0x7d, 0x35, 0xbd, 0x41, 0x7b, 0x7a, 0x3f, 0xc0, 0x7e, 0x81, 0xbf, 0x96, 0xa8,
	0xb4, 0x8a, 0xb4, 0x8c, 0x4c, 0x1e, 0x3a, 0xb4, 0xaf, 0xd9, 0xb3, 0xf5, 0xd7, 0xac, 0xb9, 0x65,
	0x58, 0xbb, 0x9f, 0xca, 0x57, 0x52, 0x64, 0xe1, 0x5e, 0xb1, 0x66, 0x07, 0x7f, 0x7b, 0xf0, 0xde,
	0x2d, 0xfe, 0x35, 0x1b, 0x5e, 0xc3, 0xc6, 0x23, 0x80, 0xdc, 0x32, 0x6f, 0xc9, 0x70, 0xec, 0xee,
	0x3a, 0xc4, 0x70, 0xd1, 0x50, 0xda, 0x6d, 0x53, 0x7a, 0xcb, 0xfe, 0x1c, 0xc2, 0x80, 0x5f, 0x30,
	0x6d, 0x9e, 0xc8, 0x1d, 0x7b, 0xd2, 0x37, 0xe6, 0x3c, 0x36, 0xaa, 0xe0, 0xab, 0x9e, 0xcc, 0x69,
	0xdf, 0xd1, 0xda, 0x60, 0x73, 0x4b, 0x91, 0xd2, 0x4c, 0xbb, 0x75, 0xe9, 0x85, 0xce, 0x08, 0xfe,
	0xec, 0xc0, 0xfe, 0x75, 0xb1, 0x90, 0xcf, 0x5b, 0xaf, 0xbf, 0x67, 0xf9, 0x7a, 0x72, 0xe7, 0xeb,
	0x7f, 0xf5, 0xf6, 0x93, 0xaf, 0xc1, 0xaf, 0x6f, 0x6d, 0xba, 0x53, 0xb4, 0x63, 0x53, 0xbc, 0xbf,
	0x39, 0xc5, 0x95, 0x3a, 0xc3, 0x51, 0xde, 0xfc, 0x2b, 0xf2, 0x02, 0x06, 0xcc, 0x6d, 0x8c, 0x65,
	0xe8, 0xd6, 0x36, 0xea, 0xd5, 0x0a, 0x57, 0x11, 0xe4, 0x53, 0x68, 0xae, 0x2f, 0x50, 0xd1, 0x9e,
	0x6d, 0xe2, 0x70, 0xd3, 0xdc, 0xdb, 0xbe, 0xc1, 0x27, 0x70, 0xcf, 0x9e, 0x9a, 0x86, 0xea, 0x75,
	0xdf, 0x6e, 0x6b, 0x3e, 0x83, 0x83, 0x55, 0xe0, 0xf7, 0xa8, 0x14, 0x5b, 0xa0, 0x0a, 0x91, 0x6d,
	0x1b, 0xfd, 0x25, 0xdc, 0x37, 0xd1, 0x53, 0xae, 0xc5, 0x52, 0xe8, 0x6a, 0x86, 0x99, 0xc6, 0xe2,
	0x96, 0xf8, 0x7d, 0xe8, 0x8a, 0xd8, 0xd1, 0xeb, 0x87, 0xe6, 0x37, 0x78, 0xe9, 0x36, 0x7f, 0x3d,
	0xc3, 0x94, 0x73, 0xcc, 0x35, 0x6e, 0x9f, 0xe5, 0x2b, 0x27, 0xf2, 0xf5, 0x2c, 0x2f, 0x85, 0x4a,
	0x85, 0x52, 0xff, 0x23, 0xcd, 0x2b, 0xa7, 0xac, 0x59, 0x82, 0xac, 0xf8, 0x46, 0x28, 0x2d, 0x8b,
	0xaa, 0x2d, 0x60, 0x6f, 0x4d, 0xc0, 0x8f, 0x00, 0xb8, 0x71, 0xc4, 0x38, 0x62, 0xda, 0x72, 0xd2,
	0x0b, 0x77, 0x6b, 0x64, 0xaa, 0x4f, 0xc6, 0x3f, 0x8f, 0x8e, 0x3f, 0x7c, 0xb1, 0x9a, 0xdd, 0x59,
	0xdf, 0xfe, 0x7d, 0xfc, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xa6, 0x11, 0x2d, 0xf0, 0x08,
	0x00, 0x00,
}
