// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile_showcase.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProfileShowcaseCommunity struct {
	CommunityId          string   `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	Order                uint32   `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileShowcaseCommunity) Reset()         { *m = ProfileShowcaseCommunity{} }
func (m *ProfileShowcaseCommunity) String() string { return proto.CompactTextString(m) }
func (*ProfileShowcaseCommunity) ProtoMessage()    {}
func (*ProfileShowcaseCommunity) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bcd51b424a05798, []int{0}
}

func (m *ProfileShowcaseCommunity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileShowcaseCommunity.Unmarshal(m, b)
}
func (m *ProfileShowcaseCommunity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileShowcaseCommunity.Marshal(b, m, deterministic)
}
func (m *ProfileShowcaseCommunity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileShowcaseCommunity.Merge(m, src)
}
func (m *ProfileShowcaseCommunity) XXX_Size() int {
	return xxx_messageInfo_ProfileShowcaseCommunity.Size(m)
}
func (m *ProfileShowcaseCommunity) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileShowcaseCommunity.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileShowcaseCommunity proto.InternalMessageInfo

func (m *ProfileShowcaseCommunity) GetCommunityId() string {
	if m != nil {
		return m.CommunityId
	}
	return ""
}

func (m *ProfileShowcaseCommunity) GetOrder() uint32 {
	if m != nil {
		return m.Order
	}
	return 0
}

type ProfileShowcaseAccount struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ColorId              string   `protobuf:"bytes,3,opt,name=color_id,json=colorId,proto3" json:"color_id,omitempty"`
	Emoji                string   `protobuf:"bytes,4,opt,name=emoji,proto3" json:"emoji,omitempty"`
	Order                uint32   `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileShowcaseAccount) Reset()         { *m = ProfileShowcaseAccount{} }
func (m *ProfileShowcaseAccount) String() string { return proto.CompactTextString(m) }
func (*ProfileShowcaseAccount) ProtoMessage()    {}
func (*ProfileShowcaseAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bcd51b424a05798, []int{1}
}

func (m *ProfileShowcaseAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileShowcaseAccount.Unmarshal(m, b)
}
func (m *ProfileShowcaseAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileShowcaseAccount.Marshal(b, m, deterministic)
}
func (m *ProfileShowcaseAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileShowcaseAccount.Merge(m, src)
}
func (m *ProfileShowcaseAccount) XXX_Size() int {
	return xxx_messageInfo_ProfileShowcaseAccount.Size(m)
}
func (m *ProfileShowcaseAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileShowcaseAccount.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileShowcaseAccount proto.InternalMessageInfo

func (m *ProfileShowcaseAccount) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ProfileShowcaseAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProfileShowcaseAccount) GetColorId() string {
	if m != nil {
		return m.ColorId
	}
	return ""
}

func (m *ProfileShowcaseAccount) GetEmoji() string {
	if m != nil {
		return m.Emoji
	}
	return ""
}

func (m *ProfileShowcaseAccount) GetOrder() uint32 {
	if m != nil {
		return m.Order
	}
	return 0
}

type ProfileShowcaseCollectible struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Order                uint32   `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	CommunityId          string   `protobuf:"bytes,3,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileShowcaseCollectible) Reset()         { *m = ProfileShowcaseCollectible{} }
func (m *ProfileShowcaseCollectible) String() string { return proto.CompactTextString(m) }
func (*ProfileShowcaseCollectible) ProtoMessage()    {}
func (*ProfileShowcaseCollectible) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bcd51b424a05798, []int{2}
}

func (m *ProfileShowcaseCollectible) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileShowcaseCollectible.Unmarshal(m, b)
}
func (m *ProfileShowcaseCollectible) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileShowcaseCollectible.Marshal(b, m, deterministic)
}
func (m *ProfileShowcaseCollectible) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileShowcaseCollectible.Merge(m, src)
}
func (m *ProfileShowcaseCollectible) XXX_Size() int {
	return xxx_messageInfo_ProfileShowcaseCollectible.Size(m)
}
func (m *ProfileShowcaseCollectible) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileShowcaseCollectible.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileShowcaseCollectible proto.InternalMessageInfo

func (m *ProfileShowcaseCollectible) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ProfileShowcaseCollectible) GetOrder() uint32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *ProfileShowcaseCollectible) GetCommunityId() string {
	if m != nil {
		return m.CommunityId
	}
	return ""
}

type ProfileShowcaseAsset struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Order                uint32   `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	ContractAddress      string   `protobuf:"bytes,3,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	CommunityId          string   `protobuf:"bytes,4,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileShowcaseAsset) Reset()         { *m = ProfileShowcaseAsset{} }
func (m *ProfileShowcaseAsset) String() string { return proto.CompactTextString(m) }
func (*ProfileShowcaseAsset) ProtoMessage()    {}
func (*ProfileShowcaseAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bcd51b424a05798, []int{3}
}

func (m *ProfileShowcaseAsset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileShowcaseAsset.Unmarshal(m, b)
}
func (m *ProfileShowcaseAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileShowcaseAsset.Marshal(b, m, deterministic)
}
func (m *ProfileShowcaseAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileShowcaseAsset.Merge(m, src)
}
func (m *ProfileShowcaseAsset) XXX_Size() int {
	return xxx_messageInfo_ProfileShowcaseAsset.Size(m)
}
func (m *ProfileShowcaseAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileShowcaseAsset.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileShowcaseAsset proto.InternalMessageInfo

func (m *ProfileShowcaseAsset) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ProfileShowcaseAsset) GetOrder() uint32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *ProfileShowcaseAsset) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *ProfileShowcaseAsset) GetCommunityId() string {
	if m != nil {
		return m.CommunityId
	}
	return ""
}

type ProfileShowcaseEntries struct {
	Communities          []*ProfileShowcaseCommunity   `protobuf:"bytes,1,rep,name=communities,proto3" json:"communities,omitempty"`
	Accounts             []*ProfileShowcaseAccount     `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Collectibles         []*ProfileShowcaseCollectible `protobuf:"bytes,3,rep,name=collectibles,proto3" json:"collectibles,omitempty"`
	Assets               []*ProfileShowcaseAsset       `protobuf:"bytes,4,rep,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ProfileShowcaseEntries) Reset()         { *m = ProfileShowcaseEntries{} }
func (m *ProfileShowcaseEntries) String() string { return proto.CompactTextString(m) }
func (*ProfileShowcaseEntries) ProtoMessage()    {}
func (*ProfileShowcaseEntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bcd51b424a05798, []int{4}
}

func (m *ProfileShowcaseEntries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileShowcaseEntries.Unmarshal(m, b)
}
func (m *ProfileShowcaseEntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileShowcaseEntries.Marshal(b, m, deterministic)
}
func (m *ProfileShowcaseEntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileShowcaseEntries.Merge(m, src)
}
func (m *ProfileShowcaseEntries) XXX_Size() int {
	return xxx_messageInfo_ProfileShowcaseEntries.Size(m)
}
func (m *ProfileShowcaseEntries) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileShowcaseEntries.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileShowcaseEntries proto.InternalMessageInfo

func (m *ProfileShowcaseEntries) GetCommunities() []*ProfileShowcaseCommunity {
	if m != nil {
		return m.Communities
	}
	return nil
}

func (m *ProfileShowcaseEntries) GetAccounts() []*ProfileShowcaseAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *ProfileShowcaseEntries) GetCollectibles() []*ProfileShowcaseCollectible {
	if m != nil {
		return m.Collectibles
	}
	return nil
}

func (m *ProfileShowcaseEntries) GetAssets() []*ProfileShowcaseAsset {
	if m != nil {
		return m.Assets
	}
	return nil
}

type ProfileShowcaseEntriesEncrypted struct {
	EncryptedEntries     []byte   `protobuf:"bytes,1,opt,name=encrypted_entries,json=encryptedEntries,proto3" json:"encrypted_entries,omitempty"`
	EncryptionKeys       [][]byte `protobuf:"bytes,2,rep,name=encryption_keys,json=encryptionKeys,proto3" json:"encryption_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileShowcaseEntriesEncrypted) Reset()         { *m = ProfileShowcaseEntriesEncrypted{} }
func (m *ProfileShowcaseEntriesEncrypted) String() string { return proto.CompactTextString(m) }
func (*ProfileShowcaseEntriesEncrypted) ProtoMessage()    {}
func (*ProfileShowcaseEntriesEncrypted) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bcd51b424a05798, []int{5}
}

func (m *ProfileShowcaseEntriesEncrypted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileShowcaseEntriesEncrypted.Unmarshal(m, b)
}
func (m *ProfileShowcaseEntriesEncrypted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileShowcaseEntriesEncrypted.Marshal(b, m, deterministic)
}
func (m *ProfileShowcaseEntriesEncrypted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileShowcaseEntriesEncrypted.Merge(m, src)
}
func (m *ProfileShowcaseEntriesEncrypted) XXX_Size() int {
	return xxx_messageInfo_ProfileShowcaseEntriesEncrypted.Size(m)
}
func (m *ProfileShowcaseEntriesEncrypted) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileShowcaseEntriesEncrypted.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileShowcaseEntriesEncrypted proto.InternalMessageInfo

func (m *ProfileShowcaseEntriesEncrypted) GetEncryptedEntries() []byte {
	if m != nil {
		return m.EncryptedEntries
	}
	return nil
}

func (m *ProfileShowcaseEntriesEncrypted) GetEncryptionKeys() [][]byte {
	if m != nil {
		return m.EncryptionKeys
	}
	return nil
}

type ProfileShowcase struct {
	ForEveryone           *ProfileShowcaseEntries          `protobuf:"bytes,1,opt,name=for_everyone,json=forEveryone,proto3" json:"for_everyone,omitempty"`
	ForContacts           *ProfileShowcaseEntriesEncrypted `protobuf:"bytes,2,opt,name=for_contacts,json=forContacts,proto3" json:"for_contacts,omitempty"`
	ForIdVerifiedContacts *ProfileShowcaseEntriesEncrypted `protobuf:"bytes,3,opt,name=for_id_verified_contacts,json=forIdVerifiedContacts,proto3" json:"for_id_verified_contacts,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                         `json:"-"`
	XXX_unrecognized      []byte                           `json:"-"`
	XXX_sizecache         int32                            `json:"-"`
}

func (m *ProfileShowcase) Reset()         { *m = ProfileShowcase{} }
func (m *ProfileShowcase) String() string { return proto.CompactTextString(m) }
func (*ProfileShowcase) ProtoMessage()    {}
func (*ProfileShowcase) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bcd51b424a05798, []int{6}
}

func (m *ProfileShowcase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileShowcase.Unmarshal(m, b)
}
func (m *ProfileShowcase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileShowcase.Marshal(b, m, deterministic)
}
func (m *ProfileShowcase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileShowcase.Merge(m, src)
}
func (m *ProfileShowcase) XXX_Size() int {
	return xxx_messageInfo_ProfileShowcase.Size(m)
}
func (m *ProfileShowcase) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileShowcase.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileShowcase proto.InternalMessageInfo

func (m *ProfileShowcase) GetForEveryone() *ProfileShowcaseEntries {
	if m != nil {
		return m.ForEveryone
	}
	return nil
}

func (m *ProfileShowcase) GetForContacts() *ProfileShowcaseEntriesEncrypted {
	if m != nil {
		return m.ForContacts
	}
	return nil
}

func (m *ProfileShowcase) GetForIdVerifiedContacts() *ProfileShowcaseEntriesEncrypted {
	if m != nil {
		return m.ForIdVerifiedContacts
	}
	return nil
}

func init() {
	proto.RegisterType((*ProfileShowcaseCommunity)(nil), "protobuf.ProfileShowcaseCommunity")
	proto.RegisterType((*ProfileShowcaseAccount)(nil), "protobuf.ProfileShowcaseAccount")
	proto.RegisterType((*ProfileShowcaseCollectible)(nil), "protobuf.ProfileShowcaseCollectible")
	proto.RegisterType((*ProfileShowcaseAsset)(nil), "protobuf.ProfileShowcaseAsset")
	proto.RegisterType((*ProfileShowcaseEntries)(nil), "protobuf.ProfileShowcaseEntries")
	proto.RegisterType((*ProfileShowcaseEntriesEncrypted)(nil), "protobuf.ProfileShowcaseEntriesEncrypted")
	proto.RegisterType((*ProfileShowcase)(nil), "protobuf.ProfileShowcase")
}

func init() {
	proto.RegisterFile("profile_showcase.proto", fileDescriptor_5bcd51b424a05798)
}

var fileDescriptor_5bcd51b424a05798 = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x55, 0xe2, 0x34, 0xa4, 0x93, 0x94, 0x84, 0x55, 0x89, 0x0c, 0x07, 0x08, 0x16, 0x12, 0xa9,
	0x90, 0x82, 0x04, 0x12, 0x17, 0xb8, 0x94, 0x10, 0x09, 0x04, 0x07, 0xb4, 0x95, 0x38, 0x70, 0xb1,
	0xec, 0xf5, 0x18, 0x16, 0x6c, 0x6f, 0xb4, 0xeb, 0xb4, 0xf2, 0x3f, 0xe0, 0xc2, 0x85, 0x1f, 0xc0,
	0x6f, 0x45, 0xfb, 0x61, 0xa7, 0xc4, 0x4d, 0x51, 0x4f, 0xde, 0x19, 0xcf, 0xbc, 0x37, 0xef, 0xcd,
	0x2e, 0x4c, 0xd7, 0x52, 0xa4, 0x3c, 0xc3, 0x50, 0x7d, 0x13, 0x17, 0x2c, 0x52, 0xb8, 0x58, 0x4b,
	0x51, 0x0a, 0x32, 0x30, 0x9f, 0x78, 0x93, 0x06, 0x67, 0xe0, 0x7f, 0xb2, 0x35, 0x67, 0xae, 0x64,
	0x29, 0xf2, 0x7c, 0x53, 0xf0, 0xb2, 0x22, 0x8f, 0x60, 0xc4, 0xea, 0x20, 0xe4, 0x89, 0xdf, 0x99,
	0x75, 0xe6, 0x87, 0x74, 0xd8, 0xe4, 0xde, 0x27, 0xe4, 0x18, 0x0e, 0x84, 0x4c, 0x50, 0xfa, 0xdd,
	0x59, 0x67, 0x7e, 0x44, 0x6d, 0x10, 0xfc, 0xea, 0xc0, 0x74, 0x07, 0xf5, 0x94, 0x31, 0xb1, 0x29,
	0x4a, 0xe2, 0xc3, 0xad, 0x28, 0x49, 0x24, 0x2a, 0xe5, 0xe0, 0xea, 0x90, 0x10, 0xe8, 0x15, 0x51,
	0x8e, 0x06, 0xe9, 0x90, 0x9a, 0x33, 0xb9, 0x07, 0x03, 0x26, 0x32, 0x21, 0x35, 0xbb, 0x67, 0xcb,
	0x4d, 0x6c, 0x99, 0x31, 0x17, 0xdf, 0xb9, 0xdf, 0x33, 0x79, 0x1b, 0x6c, 0xe7, 0x39, 0xb8, 0x3c,
	0xcf, 0x57, 0xb8, 0xdf, 0x12, 0x99, 0x65, 0xc8, 0x4a, 0x1e, 0x67, 0x48, 0x26, 0xe0, 0x6d, 0x1a,
	0x75, 0xfa, 0x78, 0xb5, 0xaa, 0x96, 0x1d, 0x5e, 0xcb, 0x8e, 0xe0, 0x77, 0x07, 0x8e, 0x77, 0x85,
	0x2b, 0x85, 0x25, 0x99, 0x42, 0x5f, 0x55, 0x79, 0x2c, 0x32, 0x47, 0xe3, 0xa2, 0x3d, 0x4c, 0x27,
	0x30, 0x61, 0xa2, 0x28, 0x65, 0xc4, 0xca, 0xb0, 0x76, 0xcb, 0xb2, 0x8d, 0xeb, 0xfc, 0xa9, 0x73,
	0x6d, 0x77, 0xa8, 0x5e, 0x7b, 0xa8, 0x3f, 0xdd, 0xd6, 0x36, 0x56, 0x45, 0x29, 0x39, 0x2a, 0xf2,
	0x16, 0x9a, 0x4a, 0x8e, 0x7a, 0x23, 0xde, 0x7c, 0xf8, 0x3c, 0x58, 0xd4, 0xb7, 0x63, 0xb1, 0xef,
	0x6a, 0xd0, 0xcb, 0x6d, 0xe4, 0x35, 0x0c, 0x22, 0xbb, 0x5e, 0xe5, 0x77, 0x0d, 0xc4, 0x6c, 0x2f,
	0x84, 0xbb, 0x07, 0xb4, 0xe9, 0x20, 0xef, 0xb4, 0x82, 0x66, 0x1b, 0x5a, 0xa8, 0x46, 0x78, 0x7c,
	0xcd, 0x10, 0x4d, 0x31, 0xfd, 0xa7, 0x93, 0xbc, 0x84, 0x7e, 0xa4, 0xdd, 0x56, 0x7e, 0xcf, 0x60,
	0x3c, 0xd8, 0x3f, 0x85, 0x2e, 0xa3, 0xae, 0x3a, 0xb8, 0x80, 0x87, 0x57, 0xfb, 0xb3, 0x2a, 0x98,
	0xac, 0xd6, 0x25, 0x26, 0xe4, 0x29, 0xdc, 0xc1, 0x3a, 0x08, 0xd1, 0xfe, 0x35, 0xab, 0x1c, 0xd1,
	0x49, 0xf3, 0xa3, 0x76, 0xf5, 0x09, 0x8c, 0x5d, 0x8e, 0x8b, 0x22, 0xfc, 0x81, 0x95, 0xb5, 0x65,
	0x44, 0x6f, 0x6f, 0xd3, 0x1f, 0xb0, 0x52, 0xc1, 0xcf, 0x2e, 0x8c, 0x77, 0x98, 0xc9, 0x12, 0x46,
	0xa9, 0x90, 0x21, 0x9e, 0xa3, 0xac, 0x44, 0x81, 0x86, 0xe4, 0x3a, 0x43, 0x1d, 0x29, 0x1d, 0xa6,
	0x42, 0xae, 0x5c, 0x13, 0xf9, 0x68, 0x41, 0xf4, 0x65, 0x89, 0x98, 0xd9, 0x8a, 0x06, 0x39, 0xf9,
	0x1f, 0x48, 0xa3, 0xd7, 0xa0, 0x2d, 0x5d, 0x37, 0x89, 0xc1, 0x4f, 0xcd, 0x1b, 0x0c, 0xcf, 0x51,
	0xf2, 0x94, 0x63, 0xb2, 0x45, 0xf6, 0x6e, 0x8a, 0x7c, 0x37, 0xd5, 0xcf, 0xf7, 0xb3, 0x03, 0xaa,
	0x39, 0xde, 0x1c, 0x7d, 0x19, 0x2e, 0x9e, 0xbd, 0xaa, 0x51, 0xe2, 0xbe, 0x39, 0xbd, 0xf8, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0x59, 0x5a, 0x14, 0x58, 0xc1, 0x04, 0x00, 0x00,
}
