// Code generated by protoc-gen-go. DO NOT EDIT.
// source: url_data.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Community struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	MembersCount         uint32   `protobuf:"varint,3,opt,name=members_count,json=membersCount,proto3" json:"members_count,omitempty"`
	Color                string   `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	TagIndices           []uint32 `protobuf:"varint,5,rep,packed,name=tag_indices,json=tagIndices,proto3" json:"tag_indices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Community) Reset()         { *m = Community{} }
func (m *Community) String() string { return proto.CompactTextString(m) }
func (*Community) ProtoMessage()    {}
func (*Community) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f1e15b5f0115710, []int{0}
}

func (m *Community) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Community.Unmarshal(m, b)
}
func (m *Community) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Community.Marshal(b, m, deterministic)
}
func (m *Community) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Community.Merge(m, src)
}
func (m *Community) XXX_Size() int {
	return xxx_messageInfo_Community.Size(m)
}
func (m *Community) XXX_DiscardUnknown() {
	xxx_messageInfo_Community.DiscardUnknown(m)
}

var xxx_messageInfo_Community proto.InternalMessageInfo

func (m *Community) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Community) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Community) GetMembersCount() uint32 {
	if m != nil {
		return m.MembersCount
	}
	return 0
}

func (m *Community) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Community) GetTagIndices() []uint32 {
	if m != nil {
		return m.TagIndices
	}
	return nil
}

type Channel struct {
	DisplayName          string     `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description          string     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Emoji                string     `protobuf:"bytes,3,opt,name=emoji,proto3" json:"emoji,omitempty"`
	Color                string     `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Community            *Community `protobuf:"bytes,5,opt,name=community,proto3" json:"community,omitempty"`
	Uuid                 string     `protobuf:"bytes,6,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f1e15b5f0115710, []int{1}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Channel) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Channel) GetEmoji() string {
	if m != nil {
		return m.Emoji
	}
	return ""
}

func (m *Channel) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Channel) GetCommunity() *Community {
	if m != nil {
		return m.Community
	}
	return nil
}

func (m *Channel) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type User struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Color                string   `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f1e15b5f0115710, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

type URLData struct {
	// Community, Channel, or User
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URLData) Reset()         { *m = URLData{} }
func (m *URLData) String() string { return proto.CompactTextString(m) }
func (*URLData) ProtoMessage()    {}
func (*URLData) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f1e15b5f0115710, []int{3}
}

func (m *URLData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URLData.Unmarshal(m, b)
}
func (m *URLData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URLData.Marshal(b, m, deterministic)
}
func (m *URLData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URLData.Merge(m, src)
}
func (m *URLData) XXX_Size() int {
	return xxx_messageInfo_URLData.Size(m)
}
func (m *URLData) XXX_DiscardUnknown() {
	xxx_messageInfo_URLData.DiscardUnknown(m)
}

var xxx_messageInfo_URLData proto.InternalMessageInfo

func (m *URLData) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// Field on CommunityDescription, CommunityChat and ContactCodeAdvertisement
type URLParams struct {
	EncodedUrlData string `protobuf:"bytes,1,opt,name=encoded_url_data,json=encodedUrlData,proto3" json:"encoded_url_data,omitempty"`
	// Signature of encoded URL data
	EncodedSignature     string   `protobuf:"bytes,2,opt,name=encoded_signature,json=encodedSignature,proto3" json:"encoded_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URLParams) Reset()         { *m = URLParams{} }
func (m *URLParams) String() string { return proto.CompactTextString(m) }
func (*URLParams) ProtoMessage()    {}
func (*URLParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f1e15b5f0115710, []int{4}
}

func (m *URLParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URLParams.Unmarshal(m, b)
}
func (m *URLParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URLParams.Marshal(b, m, deterministic)
}
func (m *URLParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URLParams.Merge(m, src)
}
func (m *URLParams) XXX_Size() int {
	return xxx_messageInfo_URLParams.Size(m)
}
func (m *URLParams) XXX_DiscardUnknown() {
	xxx_messageInfo_URLParams.DiscardUnknown(m)
}

var xxx_messageInfo_URLParams proto.InternalMessageInfo

func (m *URLParams) GetEncodedUrlData() string {
	if m != nil {
		return m.EncodedUrlData
	}
	return ""
}

func (m *URLParams) GetEncodedSignature() string {
	if m != nil {
		return m.EncodedSignature
	}
	return ""
}

func init() {
	proto.RegisterType((*Community)(nil), "protobuf.Community")
	proto.RegisterType((*Channel)(nil), "protobuf.Channel")
	proto.RegisterType((*User)(nil), "protobuf.User")
	proto.RegisterType((*URLData)(nil), "protobuf.URLData")
	proto.RegisterType((*URLParams)(nil), "protobuf.URLParams")
}

func init() {
	proto.RegisterFile("url_data.proto", fileDescriptor_5f1e15b5f0115710)
}

var fileDescriptor_5f1e15b5f0115710 = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x15, 0xda, 0xb4, 0xe4, 0xd2, 0x54, 0x60, 0x3a, 0x78, 0x23, 0xa4, 0x4b, 0x24, 0xa4,
	0x20, 0x60, 0x64, 0xa3, 0x2c, 0x48, 0x15, 0x42, 0x46, 0x59, 0x58, 0x22, 0x27, 0x31, 0xc5, 0x28,
	0xb6, 0x2b, 0xc7, 0x19, 0xfa, 0x4e, 0xbc, 0x04, 0x6f, 0x86, 0x70, 0x62, 0xca, 0xc2, 0xd6, 0x29,
	0x77, 0x9f, 0x4e, 0x7f, 0x3e, 0xfd, 0x32, 0xcc, 0x3b, 0xdd, 0x14, 0x35, 0x35, 0x34, 0xdb, 0x6a,
	0x65, 0x14, 0x3a, 0xb6, 0x9f, 0xb2, 0x7b, 0x4b, 0x3e, 0x3d, 0x08, 0x56, 0x4a, 0x88, 0x4e, 0x72,
	0xb3, 0x43, 0x17, 0x30, 0xab, 0x79, 0xbb, 0x6d, 0xe8, 0xae, 0x90, 0x54, 0x30, 0xec, 0xc5, 0x5e,
	0x1a, 0x90, 0x70, 0x60, 0x4f, 0x54, 0x30, 0x14, 0x43, 0x58, 0xb3, 0xb6, 0xd2, 0x7c, 0x6b, 0xb8,
	0x92, 0xf8, 0x68, 0xb8, 0xd8, 0x23, 0xb4, 0x84, 0x48, 0x30, 0x51, 0x32, 0xdd, 0x16, 0x95, 0xea,
	0xa4, 0xc1, 0xa3, 0xd8, 0x4b, 0x23, 0x32, 0x1b, 0xe0, 0xea, 0x87, 0xa1, 0x05, 0xf8, 0x95, 0x6a,
	0x94, 0xc6, 0x63, 0x1b, 0xd0, 0x2f, 0xe8, 0x1c, 0x42, 0x43, 0x37, 0x05, 0x97, 0x35, 0xaf, 0x58,
	0x8b, 0xfd, 0x78, 0x94, 0x46, 0x04, 0x0c, 0xdd, 0x3c, 0xf6, 0x24, 0xf9, 0xf2, 0x60, 0xba, 0x7a,
	0xa7, 0x52, 0xb2, 0xe6, 0x30, 0xb2, 0x0b, 0xf0, 0x99, 0x50, 0x1f, 0xdc, 0x4a, 0x06, 0xa4, 0x5f,
	0xfe, 0xb1, 0xbb, 0x86, 0xa0, 0x72, 0x55, 0x61, 0x3f, 0xf6, 0xd2, 0xf0, 0xe6, 0x2c, 0x73, 0x4d,
	0x66, 0xbf, 0x2d, 0x92, 0xfd, 0x15, 0x42, 0x30, 0xee, 0x3a, 0x5e, 0xe3, 0x89, 0xcd, 0xb1, 0x73,
	0x42, 0x61, 0x9c, 0xb7, 0x4c, 0x1f, 0xcc, 0xbf, 0x37, 0x1d, 0xfd, 0x31, 0x4d, 0x96, 0x30, 0xcd,
	0xc9, 0xfa, 0x81, 0x1a, 0x8a, 0x30, 0x4c, 0x2b, 0x25, 0x0d, 0x93, 0xc6, 0xfe, 0x60, 0x46, 0xdc,
	0x9a, 0x94, 0x10, 0xe4, 0x64, 0xfd, 0x4c, 0x35, 0x15, 0x2d, 0x4a, 0xe1, 0x84, 0xc9, 0x4a, 0xd5,
	0xac, 0x2e, 0xdc, 0x5b, 0x19, 0x84, 0xe6, 0x03, 0xcf, 0x75, 0x63, 0x03, 0x2f, 0xe1, 0xd4, 0x5d,
	0xb6, 0x7c, 0x23, 0xa9, 0xe9, 0x34, 0x1b, 0xcc, 0x5c, 0xc4, 0x8b, 0xe3, 0xf7, 0xd1, 0x6b, 0x98,
	0x5d, 0xdd, 0xb9, 0x8e, 0xca, 0x89, 0x9d, 0x6e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xcf,
	0x99, 0x77, 0x90, 0x02, 0x00, 0x00,
}
