services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    platform: linux/amd64
    command:
      - anvil --host 0.0.0.0

  deploy-sntv2:
    platform: linux/amd64
    environment:
      - API_KEY_ETHERSCAN="" # API_KEY env var is required, but value isn't used
      - GITHUB_ORG=status-im
      - GITHUB_REPO=status-network-token-v2
    depends_on:
      - anvil
    build:
      context: .
      dockerfile: Dockerfile
    command: |
        forge script script/Deploy.s.sol
            --broadcast
            --fork-url=http://anvil:8545
            --private-key=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

  deploy-communities-contracts:
    platform: linux/amd64
    environment:
    # API_KEY_* env vars are required, but values aren't used
      - API_KEY_ETHERSCAN=""
      - API_KEY_ARBISCAN=""
      - API_KEY_OPTIMISTIC_ETHERSCAN=""
      - GITHUB_ORG=status-im
      - GITHUB_REPO=communities-contracts
    depends_on:
     deploy-sntv2:
      condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile
    command: |
        forge script script/DeployContracts.s.sol
            --broadcast
            --fork-url=http://anvil:8545
            --private-key=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
            --sender=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
