name: Go Lint
on:
  pull_request:
    branches:
      - develop
      - release/**

permissions:
  contents: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Cache Go dependencies
        uses: actions/cache@v4
        id: cache-go-deps
        with:
          path: ~/go/bin
          key: go-deps-${{ runner.os }}-v4.0.2-protoc-gen-go-v1.34.1-gopls-latest
          restore-keys: |
            go-deps-${{ runner.os }}-

      - name: Install Go dependencies
        if: steps.cache-go-deps.outputs.cache-hit != 'true'
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.1
          go install golang.org/x/tools/gopls@latest
          which gopls

      - name: Setup Protocol Buffer Compiler
        uses: arduino/setup-protoc@v3
        with:
          version: "29.3"

      - name: Cache go-generate-fast
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-generate-fast
          key: go-generate-fast-${{ runner.os }}-${{ hashFiles('**/*.go', '**/go.mod', '**/go.sum') }}
          restore-keys: |
            go-generate-fast-${{ runner.os }}-

      - name: Generate
        env:
          GO_GENERATE_FAST_DIR: ~/.cache/go-generate-fast
        run: |
          make generate

      - name: golangci-lint
        env:
          NIM_SDS_HEADER_PATH: "${{ github.workspace }}/third-party/nim-sds/library"
          NIM_SDS_LIB_PATH: "${{ github.workspace }}/third_party/nim-sds/build"
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.3.1
          args: --build-tags=gowaku_no_rln

      - name: lint-panics
        run: |
          make lint-panics

  migration-check:
    name: Check SQL migrations order
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run migration check
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        run: |
          bash _assets/scripts/migration_check.sh
