name: Test Reliability

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'

env:
  FORCE_COLOR: "1"

jobs:
  test-reliability:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: ipv4
            docker_compose_file: test/functional/docker-compose.test.reliability.ipv4.yml
            use_ipv6: "No"
          - name: ipv6
            docker_compose_file: test/functional/docker-compose.test.reliability.ipv6.yml
            use_ipv6: "Yes"
    steps:

    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Set up virtual environment in /test/functional/
      run: |
        python -m venv test/functional/.venv
        echo "test/functional/.venv/bin" >> $GITHUB_PATH  # Add virtualenv to PATH for subsequent steps

    - name: Install dependencies based on requirements.txt
      run: pip install -r test/functional/requirements.txt

    - name: Build status-backend
      run: docker build . --tag "statusgo-local" --build-arg "cache_id=${GITHUB_RUN_ID}"

    - name: Run environment
      run: docker compose -f test/functional/docker-compose.anvil.yml -f ${{ matrix.config.docker_compose_file }} up --build --remove-orphans -d

    - name: Run tests
      env:
        USE_IPV6: ${{ matrix.config.use_ipv6 }}
      run: |
        pytest --reruns 2 \
          -n auto \
          -m "reliability and not light_client_7393" \
          -c test/functional/pytest.ini \
          --junit-xml=pytest_results.xml \
          --tb=short \
          --docker-image="statusgo-local" \
          --waku-fleet=status.staging \
          --waku-fleets-config="" \
          --logs-dir=test/functional/log

    - name: Test Report
      if: always()
      uses: dorny/test-reporter@95058abb17504553158e70e2c058fe1fda4392c2
      with:
        name: Pytest JUnit Test Report (${{ matrix.config.name }})
        path: pytest_results.xml
        reporter: java-junit
        use-actions-summary: 'true'

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: status-backend-logs_${{ matrix.config.name }}
        path: test/functional/log
